### ISSUE TITLE
Bug: Unuable Items via Lore-Requirements

### ISSUE THREAD

**Issue by AmbriusMC** [Eniripsa96/SkillAPI#100]
**Issue**: Removal of items due to lore-requirements

**Patch**: SkillAPI Premium 1.11 Nov 27, 2016

**Bug**: If your entire inventory is full and you select an item using the hotbar, which you cannot use, the item will be permanently removed instead of being dropped.

**Comment by Eniripsa96** [comment]
Fixed in v1.14
