### ISSUE TITLE
Bug: Class Requirements via Lore-Requirements 

### ISSUE THREAD

**Issue by AmbriusMC** [Eniripsa96/SkillAPI#101]
**Issue**: Both _Class Req:_ and  _Class Excluded:_ doesn't recognize classes.

**Patch**: SkillAPI Premium 1.11 Nov 27, 2016

**Bug**: When utilizing the lore-requirements,  _Class Req:_ and  _Class Excluded:_ don't appear to be recognizing the classes properly.  _Class Req:_ removes the item despite you being set as the right class and _Class Excluded:_ won't remove the item even though you're set as the excluded class. I'd assume this broke in SkillAPI Premium 1.6 Oct 30, 2016 since I haven't experienced this issue prior to that patch.

**Comment by Eniripsa96** [comment]
Fixed in v1.14
