### ISSUE TITLE
Citizens (Nametag) support

### ISSUE THREAD

**Issue by Namnodorel** [Eniripsa96/SkillAPI#102]
When i create a player NPC with Citizens, and set its nametag to not be shown, SkillAPI overrides this and displays the nametag (and Level) nonetheless. It would be useful if SkillAPI would respect this (and maybe similar issues when used together with Citizens - NPCs aren't the same thing as players, and sometimes shouldn't be treated the same).

You can detect if a Player-opbject is an NPC like this:

https://wiki.citizensnpcs.co/API#Checking_if_an_entity_is_a_Citizens_NPC

**Comment by Eniripsa96** [comment]
Support added in v1.14

**Comment by Namnodorel** [comment]
Okay, sorry for the looong delay here, but have a look at this:

http://puu.sh/tYQ46/53887b2174.png

This screenshot was taken on a 1.10.2 servr with the newest version of SkillAPI installed. What am i overlooking? I don't need and/or want the nametag or the level shown. Actually, the namtag isn't even shown correctly, it shows just the last two letters.
