### ISSUE TITLE
Problem with Particle Projectile hitting entitys

### ISSUE THREAD

**Issue by DaisukeYami** [Eniripsa96/SkillAPI#103]
I created an Particle Projectile using the Editor but when I launch the projectile at the Mobs it never hits / applies the child component (mainly damage) and at times aiming to the right of the entity hits it for some reason , I am currently on Minecraft 1.11 and am using the latest version of SkillAPI when I used it before around 1.8 the projectiles always worked but now nothing. Maybe adding a variable to how tolerant it is in hitting mobs. Thanks~

**Comment by Eniripsa96** [comment]
Could you share the skill you're having issues with? I have projectile skills myself and the accuracy seems fine with those.

**Comment by DaisukeYami** [comment]
WhiteDragonRoar:
  name: 'WhiteDragonRoar'
  type: 'Dynamic'
  max-level: 5
  skill-req: 'WhiteDragonSlayer'
  skill-req-lvl: 1
  needs-permission: 'False'
  msg: '&6{player} &2has cast &6{skill}'
  combo: ''
  icon: 'Sugar'
  icon-data: 0
  icon-lore:
  - '&d{name} &7({level}/{max})'
  - '&2Type: &6{type}'
  - ''
  - '{req:level}Level: {attr:level}'
  - '{req:cost}Cost: {attr:cost}'
  - ''
  - '&2Mana: {attr:mana}'
  - '&2Cooldown: {attr:cooldown}'
  attributes:
    level-base: 1
    level-scale: 0
    cost-base: 1
    cost-scale: 0
    cooldown-base: 0
    cooldown-scale: 0
    mana-base: 0
    mana-scale: 0
  components:
    Cast-a:
      type: 'trigger'
      data:
        icon-key: ''
      children:
        Particle Projectile-b:
          type: 'mechanic'
          data:
            icon-key: ''
            counts: 'True'
            group: 'Enemy'
            spread: 'Cone'
            amount-base: 5
            amount-scale: 0
            velocity-base: 3
            velocity-scale: 0
            angle-base: 20
            angle-scale: 0
            position: 1.5
            forward-base: 0
            forward-scale: 0
            upward-base: 1
            upward-scale: 0
            right-base: 0
            right-scale: 0
            particle: 'End Rod'
            arrangement: 'Sphere'
            radius-base: 2
            radius-scale: 0
            particles-base: 50
            particles-scale: 0
            visible-radius: 100
            dx: 1
            dy: 1
            dz: 1
            speed: 0.1
            amount: 1
            frequency: 0.05
            lifespan: 100
            use-effect: 'False'
          children:
            Potion-c:
              type: 'mechanic'
              data:
                icon-key: ''
                counts: 'True'
                potion: 'Blindness'
                ambient: 'True'
                tier-base: 1
                tier-scale: 0
                seconds-base: 3
                seconds-scale: 0
            Damage-d:
              type: 'mechanic'
              data:
                icon-key: ''
                counts: 'True'
                type: 'Damage'
                value-base: 3
                value-scale: 0
                true: 'True'
        Particle Projectile-e:
          type: 'mechanic'
          data:
            icon-key: ''
            counts: 'True'
            group: 'Enemy'
            spread: 'Cone'
            amount-base: 1
            amount-scale: 0
            velocity-base: 2
            velocity-scale: 0
            angle-base: 30
            angle-scale: 0
            position: 0
            forward-base: 0
            forward-scale: 0
            upward-base: 0
            upward-scale: 0
            right-base: 0
            right-scale: 0
            particle: 'Red Dust'
            arrangement: 'Sphere'
            radius-base: 2
            radius-scale: 0
            particles-base: 50
            particles-scale: 0
            visible-radius: 100
            dx: 1
            dy: 1
            dz: 1
            speed: 1
            amount: 0
            frequency: 0.05
            lifespan: 50
            use-effect: 'False'
