### ISSUE TITLE
[BUG] A damaging skill dealing no damage

### ISSUE THREAD

**Issue by Hunt3rM4d** [Eniripsa96/SkillAPI#109]
![image](https://cloud.githubusercontent.com/assets/24738674/21462215/a18df174-c959-11e6-9f36-683279d637e7.png)

So, basicly, this should do an amount of damage to all the enemies in a cone. However, it does no damage even though it has a value bigger than 0. Any idea on how to solve this? I am running skillApi 3.98 and craftbukkit 1.10.2 with BuildTools 55.

I've tried running the plugin alone just to check if the problem is because of other plugin and no, that's not the case.

**Comment by Eniripsa96** [comment]
I will try it out and see if I can find out what's happening when I get the chance.
