### ISSUE TITLE
Item Damage/Armor Stats (based off attribute name)

### ISSUE THREAD

**Issue by Zendrex** [Eniripsa96/SkillAPI#110]
So, I am curious if this is currently possible or something that couple be added in the future, but I'm wondering if its possible to make NEW attributes and item stats that directly impact each other based on what they are called.

Long story short, have different elemental damages and different elemental resistances that only work based on what element they are being attacked by. ex. "Armor stat A" only applies resistance to "Damage stat A", while "Damage stat B" is not affected unless "Armor stat B" was present on the target.

**Comment by Zendrex** [comment]
Further more, item durability based on a lord star would be amazing. Would allow for custom items via a resource pack to be made and have wear. Ex. Mace, long sword, daggers, etc all with their own assets.

**Comment by AngDrew** [comment]
element... (you need premium skillapi to make this perfect (to grab value on armor))
you can make it with flag condition its very complex i have created that one on my server and i must change 100 skills then im stopped my mind to create the element. 


i have that on my server resourcepack... its possible.. you can change the durability of the item and make them unbreakable to make them unchanged

**Comment by Zendrex** [comment]
@AngDrew I have premium, just don't know the method to make it work right. If you have any example that you can show, that would be greatly appreciated. Currently i'm not really worrying about skills as I am item attributes for different damage types.

As for resource packs, that's why I brought up lore holding damage information since resource packs would use the actual items durability.

**Comment by AngDrew** [comment]
oll make it for you later im so lazy to create the system :( because its a bit confusing

**Comment by AngDrew** [comment]
here you can see: http://pastebin.com/ACYZvLbm
the element value is in %
this check the hitter and the taker
if the hitter have fire they will granted damage bonus
if the hitter hit people with fire in armor they will reduced

**Comment by Enoceant** [comment]
Hey I heard you guys mention resource pack, so I'm Tryna get some planning done for a resource pack for my rpg server, but I don't know if there is a way to make eggs not spawn entities, or a block not place a block. Pls help me :smile:

**Comment by Enoceant** [comment]
Because I'm making a rpg server with only 1 world and its map is gonna be pretty big with a bit more than 100 lvls, but funnnn

**Comment by Eniripsa96** [comment]
Closing since it looks like it has been resolved. Feel free to reopen if I'm mistaken.
