### ISSUE TITLE
BUG: IllegalArgumentException : Objective [ELF] already exists in this scoreboard

### ISSUE THREAD

**Issue by cubeman7** [Eniripsa96/SkillAPI#111]
Basically when I select any class on my server I get kicked with an error: **IllegalArgumentException : Objective [ELF] already exists in this scoreboard @ com.google.common.base.Preconditions:145**. This occurs on all the classes. 

I use Spigot 1.10 with BungeeCord with the latest version of SkillAPI.

**Comment by Eniripsa96** [comment]
This is a known bug with BungeeCord. I haven't yet been able to figure out a solution for it.

**Comment by Eniripsa96** [comment]
Duplicate of #88
