### ISSUE TITLE
Skill Assignment GUI Bug

### ISSUE THREAD

**Issue by Olf96** [Eniripsa96/SkillAPI#112]
Hey :)
---
Im working with your Skill-Bar technique for my class system.
In an older premium version of SkillAPI everything is fine. "/class skill" opens a GUI with all my skills showing up.
In the current premium version no single skill shows up. I just replaced the old .jar with the new one in my plugins folder and didn't change my code.
Old version: [https://i.imgur.com/SlJV6NW.png](https://i.imgur.com/SlJV6NW.png)
New version: [https://i.imgur.com/Nlo9oVP.png](https://i.imgur.com/Nlo9oVP.png)
---
Second question:
Is it possible to switch between different skill groups, to show their skills with "/class skill"?

I have 3 different groups. Battle, Craft and Race.
If the player has a Battle class but no Craft and Race class, the GUI shows me all my "Battle" Skills.
Professing a Craft class: [https://i.imgur.com/YMoroFg.png](https://i.imgur.com/YMoroFg.png)
Professing a Craft class will get me this screen by typing "/class skill":
[https://i.imgur.com/lUxqjnP.png](https://i.imgur.com/lUxqjnP.png)

**Comment by Eniripsa96** [comment]
Skills should be organized in the menu using "/class customize".
