### ISSUE TITLE
Bug: Class requirements in item lore doesn´t work

### ISSUE THREAD

**Issue by skyybender** [Eniripsa96/SkillAPI#113]
With the latest versions of skill api it is not possible to create class dependet weapons and armor. If you write the text you set up in "lore-class-text" in any line of the item lore you always will switch your item slot. Having the class and the required level or not will not make any differences. In my opinion that still worked in one of your older versions but i don´t know when it crashed. Maybe I´m simply to stupid to use that feature. Thx for checking the code :)

**Comment by Eniripsa96** [comment]
I can double check this, but I'm pretty sure I've tested this a number of times.
