### ISSUE TITLE
RpgItems support and health regen attribute

### ISSUE THREAD

**Issue by Enoceant** [Eniripsa96/SkillAPI#115]
Hi, can you pls add the RpgItems support and an attribute called health regen, also pls update it to the online skill and class maker, sorry forgot what it's called xD

**Comment by Enoceant** [comment]
By RpgItem support I mean to be able to make the requirements for the item, like
Class req, lvl req, and excluded class.

**Comment by Eniripsa96** [comment]
Just include the requirements in the item lore via RpgItem. This isn't something SkillAPI can handle.
