### ISSUE TITLE
Invalid Mechanics Problem (Item Projectile)

### ISSUE THREAD

**Issue by berkinay2** [Eniripsa96/SkillAPI#116]
I tried on 3.99 , 3.96 and 3.89 they all gave me same error:http://pastebin.com/EdaadYqa
And i dont even turn Click Combos on so What can i do ? I tried this on Spigot Latest and 1.9.4

**Comment by berkinay2** [comment]
Invalid Mechanics Componenet Item Projectile

**Comment by Eniripsa96** [comment]
The "-c" at the end should be removed by [this code](https://github.com/Eniripsa96/SkillAPI/blob/master/src/com/sucy/skill/dynamic/EffectComponent.java#L301). Only way I could see it not working is if regex is different in your java version/region or the - is somehow a different, very similar character.
