### ISSUE TITLE
Few suggestions [More targeting options, unstunable bosses, region block for skills]

### ISSUE THREAD

**Issue by WhiteWolfy** [Eniripsa96/SkillAPI#123]
Hello there! I already saw you added entity type condition, but does it fully support damage multiplier? For example, where for all targets you have x1 damage from skill, but for skeletons it's x3. 
Also about bosses, we should have some way where players can't stun or slow down some special mobs (filter it by names for example) from MythicMobs or other custom mob plugins, or these skills gonna be overpowered in boss battles x) 
And the last one - what about to have some list of names of world guard regions where all skills and passive effects just will be blocked? For some parkour challanges for example!

**Comment by Eniripsa96** [comment]
**Multiplier based on entity type**
Just add another damage mechanic within the entity type condition and you're done. If you want it to happen in one go, deal the increased damage within that condition, use an "Else" condition, then deal the regular damage in that condition.

**Filter by names**
There is a name condition.

**World Guard**
Any reason why these challenges couldn't just be in a separate world?

**Comment by WhiteWolfy** [comment]
Thank you for the asnwer! About world guard - 1. Then we will need all other world without SkillAPI working in 2. This dungeon or something with these "parkour challanges" cannot be in main world then, then we should use some TP or something, so it will ruin a part of realistic x)

**Comment by Eniripsa96** [comment]
World guard support has been added. The other two had solutions, so closing this issue
