### ISSUE TITLE
Invalid mechanic component: Particle Effect-e

### ISSUE THREAD

**Issue by SiroQ** [Eniripsa96/SkillAPI#124]
I set "Particle" using "DynamicTool" to use SkillAPI.
However, an error like the URL below will be returned.
What should I do?
http://www.mediafire.com/view/erg2no2dxrda5dx/a8b0b261527e4ec0e0f28e4528bf02da.png

**Comment by Eniripsa96** [comment]
If you're not using the premium version, that mechanic is not available. All components highlighed in blue in the tool are premium-only.
