### ISSUE TITLE
New mechanic

### ISSUE THREAD

**Issue by GlassSpirit** [Eniripsa96/SkillAPI#125]
How about adding a Damage Item (durability) mechanic? 
Would be nice if some skills used durability of sword, pickaxe, ext. instead of mana.

And why not adding "gravity" effect to Particle Projectiles, with x, y and z component.

**Comment by Eniripsa96** [comment]
Gravity is something I will likely add soon. Durability damage might be a bit longer as it seems like a uncommon and likely not very clear side effect.

**Comment by GlassSpirit** [comment]
Why not use your durability methods from MCCore?

**Comment by Eniripsa96** [comment]
Completed:
- [x] Gravity
- [ ] Durability
