### ISSUE TITLE
Force command issue

### ISSUE THREAD

**Issue by WeenoPlow** [Eniripsa96/SkillAPI#126]
Hello,
I add skillapi.force to the permission plugin at op group.
I didn't find out how to make it work as a player, should i write it like this : 
- "skillapi.force: true" ? 
- "skillapi.force.*: true" ?

In addition can you add "force.reset class" command to the plugin ?

Thank you in advance and your plugin is awesome !

**Comment by AngDrew** [comment]
nooo its command only can run from console and you cannot do it as player for any reason

**Comment by Eniripsa96** [comment]
Open commands.yml and change the "sender" option from "CONSOLE_ONLY" to "ANYONE"
