### ISSUE TITLE
[Feature request] [Dynamic Editor] Player movement checking and variables compare

### ISSUE THREAD

**Issue by Demokdawa** [Eniripsa96/SkillAPI#129]
I think two features will be usefull for the skillAPI Dynamic Editor :

1. Add a way to check if the player move.

2. Add a condition to check if one variable is equals/different from another one. With a this kind of check, we will be able to check player movement for example ^^

Thx in advance :p

**Comment by Demokdawa** [comment]
I up this feature request, because it's important for the plugin possiblities !

**Comment by Eniripsa96** [comment]
Skills run on movement will have a high chance of causing lag, so that wouldn't be added. There already is a way to compare values using Value Condition, so that's not a valid request.
