### ISSUE TITLE
Target Skills targeting Players through Walls // API code

### ISSUE THREAD

**Issue by Olf96** [Eniripsa96/SkillAPI#130]
Is it possible that ur Targetskills dont target Player through Walls?
We have a chunk own system where everyone should be safe on their bought chunk when all walls are closed, so the attacker cant come in. But with target Skills u can target those Players throught their safe houses

**Comment by co221133** [comment]
Unless I'm mistaken, when using the dynamic editor online, there's an option to disable targeting through walls for each target option.

**Comment by Olf96** [comment]
Im a programmer so i code my own Plugins; i will never use that edito ;) but ty for your answer

**Comment by Eniripsa96** [comment]
Targeting through walls is handled in the dynamic system as options. Your own hard coded skills would need to check for walls themselves (or use some utility methods I have like TargetHelper.isObstructed)
