### ISSUE TITLE
Automatic Skills

### ISSUE THREAD

**Issue by co221133** [Eniripsa96/SkillAPI#131]
Hey guys! First off, great plugin.

I just wanted to ask if there was a way to have three or four abilities that are automatically granted to a specific class, whether or not skill points are put into them. I've tried setting the max skill level to 0, and it didn't work. Thanks!

**Comment by AngDrew** [comment]
check online dynamic editor and make class with different group
and check for the group.yml after restart or reload and edit them if you want to make 0 attribute point on them

but you cannot choose more than 1 class and at the same group in one account except it spreated with /class acc

**Comment by co221133** [comment]
Thank you for your response, but I'm not 100% clear on what you're saying.

Here's my group.yml:

class: 
  default: 'none'
  permission: 'none'
  profess-reset: 'false'
  can-reset: 'true'
  show-scoreboard: 'true'
  exp-lost-on-death: 0.0
  starting-points: 1
  points-per-level: 1.0
  starting-attribs: 0
  attribs-per-level: 1.0

Which of those would I change to grant specific class abilities without the player needing to put skill points into them?

**Comment by AngDrew** [comment]
sorry for my rip english
you need to make new class on editor
and if uou see:
group class
you can change it to make new group so you can have class more than one but different group

if you want auto levelup skill you just need to set cost to 0
if you dont want player have class skill point or attribute change that on group.yml choose clasa you want and change that points-per-level or attribs-per-level to 0

hope i helped you :)

**Comment by AngDrew** [comment]
please look to the paragraph 2 sorry i dont read your questions lol

**Comment by AngDrew** [comment]
change the max level not to 0 or it will not work
if you want condition on x level the skill increase you just need to put req level a- b
b mean the scale
a mean first level
example
i set a to 10
and b to 5
if i level 10 i unlock the skill on level 1
if i level 15 the skill will be level 2
etc.
till you reach max skill level

**Comment by AngDrew** [comment]
i have to sleep this is 2.45 am and i have to go to school on 6 am

**Comment by co221133** [comment]
Setting the cost to 0 worked! Thank you very much for your help, you're a life saver! :)
