### ISSUE TITLE
Bug with channel mechanic

### ISSUE THREAD

**Issue by GlassSpirit** [Eniripsa96/SkillAPI#135]
In channel mechanics, it is impossible to deal damage with this skill after channel, because tho code looks like `executeChildren(caster, level, targets); FlagManager.removeFlag(caster, StatusFlag.CHANNEL);  FlagManager.removeFlag(caster, StatusFlag.CHANNELING);`
Then damage mechanics checks if the "channel" flag is active, and if it is, damage nullified and message written "you are channeling for another 1 second".
Maybe you need to remove channel flag before executing child components?

**Comment by GlassSpirit** [comment]
Also, if i use "Particle projectile" and it hits target, but I am channeling another spell, damage is nullified too.

**Comment by GlassSpirit** [comment]
And I think it will work same for "passive damaging" skills. Im my oppinion, only physical damage shoud be checked for status flags like channel, stun and disarm.

**Comment by Eniripsa96** [comment]
Good points. I will fix this.

**Comment by Eniripsa96** [comment]
Fixed in premium, will implement fix in free
