### ISSUE TITLE
Skills Requiring Permissions Show Up Either Way

### ISSUE THREAD

**Issue by co221133** [Eniripsa96/SkillAPI#136]
Hey guys.

I have Skill API Premium, and I'm currently having a problem with permission-requiring skills.

Each Skill has needs-permission set to 'true,' but even when I have the permission that removes all permissions for skillapi skills (- -skillapi.skill.*), every skill shows up in the tree regardless. I'm not OP, and I have no other permissions.

This is a pretty big part of my server, can anyone help? Any more details needed?

Thanks, everyone.

EDIT: And yes, you can place points into the skills whether or not you have the permission.

**Comment by AngDrew** [comment]
you can see the skill but
can you use the skill? or increase their level?

**Comment by AngDrew** [comment]
maybe you have the wrong permission node
if you are using editor makesure you add the correct permission
fir example:
need perm true
perm: use.fireball
then you need -use.fireball on your permission plugin

**Comment by AngDrew** [comment]
oh sorry my bad
your perm is correct
this is bug :(

**Comment by co221133** [comment]
The Issue is still active, so if anyone else can provide some help, dev or no, I'd appreciate it.

Thanks for your help thus far, AngDrew.

**Comment by co221133** [comment]
More info found, opening a new Issue so this actually gets some attention.
