### ISSUE TITLE
Does Initialize Passive cause lag?

### ISSUE THREAD

**Issue by setrymagent** [Eniripsa96/SkillAPI#137]
I making Ring system like ' if player's inventory slot 1 is name of item "manahealing ring"
regenerate 10mana/s'
if i make a lot of ring using Initialize passive mechanic , is it cause lag?
sorry im not good at english ;(

**Comment by Eniripsa96** [comment]
Yes, making frequent, numerous inventory checks like that for every player can quickly build up some lag. An alternative is using the "mana-regen" stat on attributes (assuming premium version, you can make an attribute specifically for the items and customize the display text it looks for). The premium version does some efficient caching of items and only checks on changed items, so it would be much faster.
