### ISSUE TITLE
SkillAPI Premium Permissions Not Working

### ISSUE THREAD

**Issue by co221133** [Eniripsa96/SkillAPI#138]
My issue is, I've done some testing, and the Premium version of SkillAPI's permissions simply don't work. With or without the permission, every one of the class' skills shows up on the skill tree, and points can be put into it.

However, with the free version, the permissions work absolutely fine. Only problem being, I want the full access to the editor like I paid for; I'd rather not lose a lot of the effects simply because the paid version is bugged.

**Comment by Eniripsa96** [comment]
This was fixed since this issue was opened.
