### ISSUE TITLE
/class commands not found

### ISSUE THREAD

**Issue by kristin-meshka** [Eniripsa96/SkillAPI#139]
The issue i'm having is that i did a restart of the server and /skill is not working at all, and it's not shoulding up when i do/ help skillapi either.
i have tried to hard reset the plugin and removed different plugins to see if it was a compatibility issue but nothing changes and /plugin shows SkillAPI as green and working fine, i dont get any error code on reload or restart either.

Please help ;_:

**Comment by kristin-meshka** [comment]
I'm using the free version of the plugin at 3.101 and spigot 1.11.2, and if needs be i can put up the other versions of plugins i'm using too.
![2017-05-18_1657](https://cloud.githubusercontent.com/assets/12241212/26226791/8bea3b70-3beb-11e7-87f3-051773bc3962.png)

**Comment by AngDrew** [comment]
Younneed to use /class 
/skill is invalid command..

**Comment by AngDrew** [comment]
😂 please read the wiki before post issue

**Comment by kristin-meshka** [comment]
i feel fing stupid now, and i did read the wiki i've been working so hard that i forgot ;_;
