### ISSUE TITLE
Spigot 1.8.3 Update?

### ISSUE THREAD

**Issue by Zariem** [Eniripsa96/SkillAPI#14]
Hey there!
I had a look at some youtube videos about your plugin and I must say I'm already in love with it.
But for some reasons (other plugins which I really need and which don't work properly on 1.8.1) I am using spigot 1.8.3.
I wanted to ask whether you will update your plugin so it will also run on 1.8.3 or if you don't consider doing that.

**Comment by Eniripsa96** [comment]
Yes, I will be updating for 1.8.3. From what I've heard from others, it should be working for the most part on 1.8.3 already. My main tester actually is running 1.8.4 with it and isn't having problems outside of a few known bugs apparent in earlier versions as well.

**Comment by Zariem** [comment]
Okay, thanks :)
