### ISSUE TITLE
Comparing two values and "equation" addition

### ISSUE THREAD

**Issue by caldersprinkle** [Eniripsa96/SkillAPI#140]
Is there a way to compare two values? 
Example:
I would like to compare a value "Power" from the lore of an item (pulled from said lore with the Value Lore feature) with "Power Tolerance".
Also, Power Tolerance would be a value that is edited by how much of a certain attribute (Let's say "Magic" a player has)

If the "Power" of the item is less than a player's "Power Tolerance", they can use the item. If the "Power" of the item is equal to the "Power Tolerance", they can use the item. But if the "Power" is greater than the "Power Tolerance", bad things happen, such as:
When the "Power" is 1 over, the player is slowed. 2 over, the slowness is increased. Etc. up until the "Power" is 7 over, where the player cannot use the item (their selected slot switches away from the slot the item is in)

If there isn't currently a feature, then one should be added called "equation" where something like the following could be entered.
[ {value} - {value} > 0 ] 
All of the stuff in brackets could be written in, so the skill author could subtract, add, multiply, divide, etc. and also check in greater than (>), equal to (=), or less than (<), maybe even not equal to (!=), greater/equal to (>=) and less/equal to (<=). There would be a lot of possibilities.

You could technically do this with a LOT of else loops, but I don't have the premium version and can't buy it, so it would be awesome for the free version. (The "else" would be awesome in the free version too . . .)

**Comment by Eniripsa96** [comment]
Yes, just use the Value condition and for the min or max value, enter the other value's name. Making the minimum the other value will check if the primary one is larger. You can use else condition (in premium) or flags to handle the checks without equality (e.g. < or >)
