### ISSUE TITLE
Not responding anymore

### ISSUE THREAD

**Issue by QueenKisaki** [Eniripsa96/SkillAPI#141]
Not sure what caused this to happen but the entire plugin is not responding. It shows being loaded but trying to reload gets this error https://pastebin.com/NkFfMJS1 . No commands work at all, no skills work, its like the plugin is not even there.

**Comment by QueenKisaki** [comment]
I have uninstalled the plugin, restarted server, shut down, than reinstalled it and it is responding again but it reset only my player file. I get the error still when logging in: https://pastebin.com/XzWqvf9q

**Comment by AngDrew** [comment]
It just a warn not a error..
But i cant help anything
I think you change something and you dont know what you have done?
Are you spigot / bukkit? Or else?
My server run in spigot and the plugin work without any warn or error

Make sure you have the latest core and skillapi

**Comment by QueenKisaki** [comment]
No haven't changed anything, just been finishing up on adding our class skills. It's been working great until out of nowhere getting those errors. Even now I log out and get https://pastebin.com/DQtWnaY2 . There has to be something going on, I don't want this happening when we open to the public.

**Comment by AngDrew** [comment]
Maybe you should uninstall other scoreboard plugin or disable skillapi scoreboard in config

**Comment by QueenKisaki** [comment]
I dont have another scoreboard plugin though.
