### ISSUE TITLE
Questions about SkillsAPI v3.101

### ISSUE THREAD

**Issue by Turn-Time** [Eniripsa96/SkillAPI#142]
Hello.When i first acquired my skills,i was able to automatically appear in the skill bar,and when i tried to replace the current skills with a new skill,i failed.
It just shows up in the operating field and goes back to the way it was.
I'm sorry.My englis is terrible.

**Comment by AngDrew** [comment]
Dont click the skill it will add the levels
Press 123456789 to place the skill to bar

**Comment by AngDrew** [comment]
Just point your mouse at the skill inside chest
Then press the number
Then skill in bar are replaced
Rightclick on the bar to disable the skill slot

**Comment by Turn-Time** [comment]
NO,i can't.I tried to do it,but it was the same.My minecraft is v1.11.2,SkillAPI v3.101.
Please try to see if this will solve the problem.Tanks.

**Comment by MAtt70725** [comment]
I am having this same issue.

**Comment by MAtt70725** [comment]
![123c41f5b1f2175c520def2d889b0146f5a835e1](https://user-images.githubusercontent.com/15817954/27419247-a6ecd4ec-56d4-11e7-93c8-c4617b63923f.gif)

**Comment by Shuboh** [comment]
Same here

**Comment by Shuunkan** [comment]
Same here

**Comment by MAtt70725** [comment]
So I ended up purchasing Skills API premium and after I did that I obtained access to the command "/class customize" this allowed me to fix the problem. So I'm not 100% sure but I believe you have to spend the $20 to use this functionality... And if that is the case then it is a real shame.

**Comment by Turn-Time** [comment]
@MAtt70725  you buy the SkillAPI premium?Can i get a copy of that call i see it?I have another way to solve this problem,but not all of them.

**Comment by Turn-Time** [comment]
@MAtt70725 If you could just give me your email

**Comment by MAtt70725** [comment]
@Turn-Time Just post your email and ill get around to messaging you.

**Comment by Eniripsa96** [comment]
This bug was fixed for the free version. Also, while I won't argue with sending one build of premium for demo purposes, try to refrain from distributing the premium version yourself.
