### ISSUE TITLE
Custom Experience

### ISSUE THREAD

**Issue by Enoceant** [Eniripsa96/SkillAPI#144]
need help making a custom formula for experience
so basically i want the player to have:
level 1: 200 exp
level 2: 240 exp (200 x 1.2)
level 3: 288 exp (240 x 1.2)
level 4: 345 exp (288 x 1.2)
and so on, please help me
thanks.

**Comment by AngDrew** [comment]
Im thinking...
And i cant make it with math
Your option is limited: lvl and (*+^-/) including ()

**Comment by AngDrew** [comment]
But maybe it can let me think again..

**Comment by AngDrew** [comment]
I found something but dont know is this help you, i post it to:
https://imagebin.ca/v/3R5EuvZwfvWd

**Comment by AngDrew** [comment]
(1.2)^lv × 200

**Comment by Eniripsa96** [comment]
Thanks AngDrew for answering this.

**Comment by Enoceant** [comment]
Yes, thanks AngDrew, sorry for the late response😊
