### ISSUE TITLE
Passive skill keeps loading as null

### ISSUE THREAD

**Issue by JamesTofo** [Eniripsa96/SkillAPI#147]
I made a class that uses its fist to do damage I made a passive that then gives it a damage buff only when its holding air. When ever I load the server, the skill in the console says null. I've done (Trigger) Initialize/ (Mechanic) Passive/ (Condition) Item[Set to air]/ (Mechanic) Damage Buff. This doesn't work and taking out the (Mechanic) Passive doesn't work either. What am I doing wrong. I want this to be a passive that gives only the fists a damage buff. I plan on having other classes like an archer have passive damage buff with a bow so this is necessary to fix.
[New Text Document.txt](https://github.com/Eniripsa96/SkillAPI/files/1143243/New.Text.Document.txt)

**Comment by AngDrew** [comment]
try add target self before condition

**Comment by AngDrew** [comment]
If still not work then you are wrong on the condition
coz i have tried to do like you do before and i made it :)

**Comment by JamesTofo** [comment]
Thank you so much!
