### ISSUE TITLE
Questions about particle

### ISSUE THREAD

**Issue by nguoivohinh811** [Eniripsa96/SkillAPI#148]
[https://www.facebook.com/MineRPGNL/videos/1784993761812179/](url)
How can you make the particles stand still and sequentially use skills like this clip? What must I use?

**Comment by JamesTofo** [comment]
You're link isn't working fam

**Comment by nguoivohinh811** [comment]
Please copy the link and open a new tab and paste it to access the link

**Comment by Eniripsa96** [comment]
Delay mechanic can help time different aspects. While playing particles, change the speed and dx/dy/dz variables to be 0, which I think makes the particles stand still. Formations can be achieved either manually or using the Particle Effect mechanic.
