### ISSUE TITLE
How do you show the lore for a class?

### ISSUE THREAD

**Issue by JamesTofo** [Eniripsa96/SkillAPI#149]
I don't know how to show a classes lore and how to even access a GUI with the class in it.

**Comment by AngDrew** [comment]
You will know it when you use dynamic editor

**Comment by JamesTofo** [comment]
I'm dumb I still don't know.

**Comment by AngDrew** [comment]
When im not wrong..
You will see box at the bottom of the page in class path that box will be lore if you use gui on skills

**Comment by JamesTofo** [comment]
No I know how to set the lore in the editor but I can't access the GUI

**Comment by AngDrew** [comment]
You need to have multiple class then run command /class skill and you will see gui

**Comment by AngDrew** [comment]
Example
My class is novice and i changed to adventurer
The both of novice and adventurer have its own unique skills

**Comment by JamesTofo** [comment]
I do have multiple classes when I /class skill only the class name appears no lore.

**Comment by AngDrew** [comment]
But its worked for me

**Comment by AngDrew** [comment]
Ill try that on house later and looking for the solution if it not work

**Comment by JamesTofo** [comment]
Do you think I need to add an Icon Data? I haven't added any for the skills and they are working just fine.

**Comment by JamesTofo** [comment]
Also is there no way to show the lore before the class is professed? Because what's the point of the lore if a player can't see it before they pick a class.

**Comment by AngDrew** [comment]
Its not possible
You can do it manually with sign

[class]
High damage physical
Low health
Medium defense

**Comment by JamesTofo** [comment]
Alright then I still would like to know how to show it in the GUI.

**Comment by JamesTofo** [comment]
Is there a config that I need to change to get this to work?

**Comment by AngDrew** [comment]
Nope

**Comment by Eniripsa96** [comment]
You need multiple class groups, not just classes. For example, have a class and a race. Once there's multiple groups that you profess into, you will see the menu when using "/class skill"
