### ISSUE TITLE
How do you show skills that don't require point cost?

### ISSUE THREAD

**Issue by JamesTofo** [Eniripsa96/SkillAPI#150]
I want my classes to have passives that they get when you join them, but I don't want them to have a cost to learn. When I make the cost 0 it doesn't show up on the skill menu.

**Comment by AngDrew** [comment]
Just make the skill point cost to 0 and lvl max to 1 or give exp requirement so it will open when player on specific lvl

**Comment by JamesTofo** [comment]
Thank you
