### ISSUE TITLE
Why minecraft 1.7.10 doesn't show special effect.

### ISSUE THREAD

**Issue by Turn-Time** [Eniripsa96/SkillAPI#151]
I trled in different versions.minecraft1.7.10 doesn't show the particle effect.

**Comment by AngDrew** [comment]
Have you try minecraft 1.7.10 particle??

**Comment by Turn-Time** [comment]
@AngDrew I  experimented with the skill ai 1.11.2and 1.7.10.But 1.7.10 doesn't show a particle effect

**Comment by AngDrew** [comment]
http://minecraft.gamepedia.com/Particles
Try all of these particle

And look in your console if you find any error just post it here so steven can check it later

And to debug particle: make passive skill on dynamic editor
Initialize
-passive
--target:self
---particle animation

**Comment by Turn-Time** [comment]
@AngDrew I did it your way.The skill can't show the particles.

**Comment by Eniripsa96** [comment]
Cauldron doesn't work with normal reflection which most particle effects require. Due to this, only specific particles are supported on 1.7.10 (ones that do not have DX/DY/DZ options).
