### ISSUE TITLE
Projectile Issues

### ISSUE THREAD

**Issue by Rkaynjehll** [Eniripsa96/SkillAPI#152]
Using MC 1.11.2 Spigot
I believe there is an issue with Target:Location and carpet. So if you cast this projectile skill at target:location on carpet, it hits the NPC and does damage. But if you cast it on the ground beside the carpet, it doesn't. Even if the NPC isn't currently standing on carpet, it still misses unless your target location is carpet.

[VOLLEY.zip](https://github.com/Eniripsa96/SkillAPI/files/1167230/VOLLEY.zip)

**Comment by Eniripsa96** [comment]
You can either do an offset target to raise up a block and then do area/damage or let it hit through walls.
