### ISSUE TITLE
My AOE Channel skill isn't working.

### ISSUE THREAD

**Issue by JamesTofo** [Eniripsa96/SkillAPI#153]
I have a skill that casts lightning on the player after a 3 second channel its just for effect; at the same time aoe potion projectile is SUPPOSED to hit all enemies in an area ofc and do damage once the potions hit the  targets. This second part isnt working I see no potions at all, how have I set up this skill wrong? 
[New Text Document.txt](https://github.com/Eniripsa96/SkillAPI/files/1171592/New.Text.Document.txt)

**Comment by AngDrew** [comment]
Lightning is damaging
Potion projectile wont damage enemy when you not insert damage as its children
Maybe your code wrong
Because if you correct your potion will not damaging
