### ISSUE TITLE
Help with block mechanic

### ISSUE THREAD

**Issue by JamesTofo** [Eniripsa96/SkillAPI#154]
I have two block mechanic skills on my server and now they won't cast any help or suggestions?

**Comment by AngDrew** [comment]
Seems almost all features doesnt work for you but work for me 😆

You cant target ground
Atleast you have target entity then cast the skill and the ground (deppend on how you setup the block mecha) will changed

**Comment by JamesTofo** [comment]
Thank you so much I'm just dumb

**Comment by AngDrew** [comment]
No prob
Just post anything if you need help
And ill try to help as soon as possible with my best

**Comment by JamesTofo** [comment]
Ok so now it applies the block change but not the damage I've done multiple combos and tried finding whats wrong heres the file. 
[New Text Document.txt](https://github.com/Eniripsa96/SkillAPI/files/1184662/New.Text.Document.txt)

**Comment by AngDrew** [comment]
if you mean that the skill will have area damage and change the block in area
Use this:
Target: single
-block mecha
-target: area
--damage

That skill will damage in area while changing the block in area of your single target
