### ISSUE TITLE
New Condition Request

### ISSUE THREAD

**Issue by JennaDiamonds** [Eniripsa96/SkillAPI#156]
I'd like to request the addition of a "Movement" condition. In which the options of forward/backward, strafing left/right could be recognized.

**Comment by Eniripsa96** [comment]
Movement tends to be a costly event, and to avoid people putting complex skills around it and lagging servers, I've strayed away from it. Unless there's a very solid reason for needing it, I won't be adding it.

**Comment by JennaDiamonds** [comment]
What about detecting a keypress? I could use a "Held Key" condition for asdw keys instead. Rather than detecting movement. If possible :)

**Comment by MWFIAE** [comment]
That's impossible. A Plugin (or bukkit in General) doesn't have access to the pressed keys
