### ISSUE TITLE
ActionBar GUI not visible

### ISSUE THREAD

**Issue by Fharen** [Eniripsa96/SkillAPI#157]
Spigot 1.12
SkillAPI v3.102
MCCore v1.63

I set the server to use actionbar to show HP,MP and stuff,. but after updating to 1.12 and the latest version of Skillapi and MCCore, It doesn't seem to showup anymore. Any idea what the problem could be?

**Comment by stapleshotz** [comment]
Having the same problem with same setup. Console gives 

> ERROR: Failed to setup Action Bar utility - not supported on pre-1.8 servers
which seems silly.

**Comment by Zicerite** [comment]
This was fixed on the premium version awhile ago

**Comment by Eniripsa96** [comment]
Will transfer fix over to free version in a bit
