### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by JennaDiamonds** [Eniripsa96/SkillAPI#159]
Currently I'm using Sentinel/Citizens as enemies on my server. Sometimes they play nice with SkillAPI. Other times not so much. Such as damage being dealt by SkillAPI to the citizens. The calculation just seems weird. For example..

I've set up a skill that "should" be doing damage on it's own to the sentinel **(Simple skill with Cast, Single target, Mechanic:damage)**. On normal mobs and players it works fine. But when I attack a sentinel with it the damage applied is based off of the damage of whatever is in the player's main hand. I am posting this in Sentinel's github as well.
I would think it is SkillAPI's issue, since to my understanding, sentinels should be effected in the same way as a regular player(Which it effects very well in the same state). For that reason I believe it may be an issue with sentinel. But, If/when you have time could you look into the issue? :)

Also, I understand you may not have time to build a test server. If you would like to access my server to take a look at the issue in its current habitat, I can send you the IP via PM.

**Addition: I have found that this is only happening while using weapons created with MyItems and DivineItemsRPG.**

**Addition: I've found with further testing that DamageLore cannot be applied to a Remembered target unless you are within melee range.**

**Comment by JennaDiamonds** [comment]
Addition: I have found that this is only happening while using weapons created with MyItems and DivineItemsRPG.

**Comment by AngDrew** [comment]
Maybe you need to send the error log
So someone can figure what's your problem

**Comment by JennaDiamonds** [comment]
If there were an error, I would send it. Thanks for reading.

**Comment by Eniripsa96** [comment]
**Sentinels taking weapon damage**
From the sounds of it, this could be Sentinels managing their health differently and taking weapon strength (I've seen multiple plugins do this) which would ignore the damage SkillAPI is trying to do. I cannot fix this.

**DamageLore melee range**
This one looks like there's probably some plugin that restricts damage based on distance between things (likely an anti-cheat plugin or custom items plugin that has similar functionality). SkillAPI doesn't have any range restrictions other than ones that are specifically configured.
