### ISSUE TITLE
Critical Bug!

### ISSUE THREAD

**Issue by GlassSpirit** [Eniripsa96/SkillAPI#160]
You have a critical bug in how buff mechanic works.
Example.
In BuffData.java, when you "update" some buff (with passive mech or etc.), you are checking for same buffs from some skill.

     * Checks for buffs with overlapping keys
     *
     * @param buff new buff to check against
     * @param map  map to look through
     *
     * @return ID of overlapping buff or -1 if no conflict
     */
    private long check(Buff buff, HashMap<Long, Buff> map)
    {
        for (Buff active : map.values())
        {
            if (active.getKey().equals(buff.getKey()))
            {
                return active.getId();
            }
        }
        return -1;
    }

If it does not find identifical buffs, it returns -1, but if it does, it returns active.getId(). The problem is that you never set this id for current buff, because you use Maps<Integer, Buff> for this. Therefore, it always returns 0 id, which breacks a lot of stuff.
Fix this please)

**Comment by Eniripsa96** [comment]
Fixed in premium, will implement the fix in free
