### ISSUE TITLE
Bug? My skill is not showing up 

### ISSUE THREAD

**Issue by JamesTofo** [Eniripsa96/SkillAPI#162]
I have a passive that gives 5 strength and two other skills that do the same except give vitality or spirit they show up in their class skill GUI but not the strength one idk why its not working.
[New Text Document.txt](https://github.com/Eniripsa96/SkillAPI/files/1199014/New.Text.Document.txt)

**Comment by JamesTofo** [comment]
Note that version has target self which was another attempt at fixing it, but the other two working skills don't have that so ignore the target.

**Comment by Eniripsa96** [comment]
1. Make sure "show-auto-skills" is set to true in config.yml
2. Use "/class customize" and add it to the menu if you're using Premium
