### ISSUE TITLE
How to skill Strengthen with lore

### ISSUE THREAD

**Issue by crston** [Eniripsa96/SkillAPI#163]
Physical Damage: 
      type: 'trigger'
      indicator: '3D'
      data: 
        icon-key: ''
        mana: 'False'
        cooldown: 'False'
        target: 'True'
        type: 'Both'
        dmg-min: '0'
        dmg-max: '999999'
        indicator: '2D'
      children: 
        Linear-b: 
          type: 'target'
          indicator: '3D'
          data: 
            icon-key: ''
            range-base: '5'
            range-scale: '0'
            tolerance-base: '4'
            tolerance-scale: '0'
            group: 'Enemy'
            wall: 'True'
            caster: 'True'
            max-base: '99'
            max-scale: '0'
            indicator: '2D'
          children: 
            Entity Type-c: 
              type: 'condition'
              indicator: '3D'
              data: 
                icon-key: ''
                types: 
                - 'ZOMBIE'
                indicator: '2D'
              children: 
                Value Set-d: 
                  type: 'mechanic'
                  indicator: '3D'
                  data: 
                    icon-key: 'defx'
                    counts: 'True'
                    key: 'def.value-scale'
                    value-base: '0'
                    value-scale: '25'
                    indicator: '2D'
                  children:  {}
                Defense Buff-e: 
                  type: 'mechanic'
                  indicator: '3D'
                  data: 
                    icon-key: 'def'
                    counts: 'True'
                    type: 'Multiplier'
                    skill: 'False'
                    value-base: '1'
                    value-scale: '0.25'
                    seconds-base: '3'
                    seconds-scale: '0'
                    indicator: '2D'
                  children:  {}
                Value Lore-f: 
                  type: 'mechanic'
                  indicator: '3D'
                  data: 
                    icon-key: 'def.value-base'
                    counts: 'True'
                    key: 'def.value-base'
                    hand: 'Main'
                    regex: 'Damage: {value}'
                    multiplier-base: '1'
                    multiplier-scale: '0'
                    indicator: '2D'
                  children:  {}
                Item-g: 
                  type: 'condition'
                  indicator: '3D'
                  data: 
                    icon-key: ''
                    check-mat: 'False'
                    check-data: 'False'
                    check-lore: 'True'
                    lore: 'PZ: {value}'
                    check-name: 'False'
                    regex: 'True'
                    indicator: '2D'
                  children:  {}
                Armor-h: 
                  type: 'condition'
                  indicator: '3D'
                  data: 
                    icon-key: ''
                    armor: 'Any'
                    check-mat: 'False'
                    check-data: 'False'
                    check-lore: 'True'
                    lore: 'PZ: 1'
                    check-name: 'False'
                    regex: 'True'
                    indicator: '2D'
                  children: 
                    Value Set-i: 
                      type: 'mechanic'
                      indicator: '3D'
                      data: 
                        icon-key: 'defplus'
                        counts: 'True'
                        key: 'def.value-scale'
                        value-base: '100'
                        value-scale: '0'
                        indicator: '2D'
                      children:  {}

I want to use lore to strengthen my skills.

**Comment by AngDrew** [comment]
Just make other skills with passive
And add contidion lore
The children is damage buff

**Comment by AngDrew** [comment]
Make it simple...

Correction:
Its better if you use skill damage trigger than passive
Less lag

Another way:
Use attributes
And put attribute in lore for ex:
Intelligent: 10

If you want for specific skills you can use condition skill level and put the damage buff

**Comment by crston** [comment]
defense buff is like to weaken the zombies
i want weaken the zombies.

**Comment by crston** [comment]
Or even if you upgrade to the maximum level of skill in the premium feature, add the lower in the item to improve the quality of the skill

**Comment by crston** [comment]
I want to use the lore of the item to raise it even higher, even if the skill is at the maximum level.

**Comment by Eniripsa96** [comment]
As AngDrew mentioned, you can either use Value Lore to read from the item or use attributes to enhance skill strengths. Check out the wiki's Attributes page for more information if needed.
