### ISSUE TITLE
Attribute Bonuses cannot use

### ISSUE THREAD

**Issue by zxc96147zxc** [Eniripsa96/SkillAPI#165]
Attribute Bonuses cannot use on weapon
My config setting: {attr}:
I use /class lore Spirit:10   not anything happen
But /class attr can plus player's attribute
Sorry im chinese. My English is not well.

**Comment by zxc96147zxc** [comment]
Minecraft version 1.11.2
Skillapi is the lastest free version

**Comment by AngDrew** [comment]
Try this
Spirit: 10
Add space between the : and number

**Comment by zxc96147zxc** [comment]
I tried. It can't,either.

**Comment by AngDrew** [comment]
You must be changed something
Re install the attribute.yml by delete it
Then try again
If fail then you are not using bukkit or spigot

**Comment by zxc96147zxc** [comment]
It can't,either.
i use spigot.

**Comment by zxc96147zxc** [comment]
ohh it fixed the bug on Skillapi Premium on 7/10
but i use free version.

**Comment by AngDrew** [comment]
Then you have to wait for steven to update the resource
