### ISSUE TITLE
Citizens NPC's Are Killable With Damage Mechanic

### ISSUE THREAD

**Issue by co221133** [Eniripsa96/SkillAPI#166]
Hey everyone, found a bug.

I have a class that passively empowers its basic attacks every 4 seconds. Meaning, every 4 seconds it gives the player the "Empowered" flag, and whenever the player attacks, it checks if the player has that flag. If they do, it does a Damage mechanic for 20 additional damage. Problem being, players with empowered attacks are able to kill otherwise invincible NPC's with a single basic attack. The NPC's are from the Citizens2 plugin, but I assumed that this would be the place to report it, seeing as this is where the damage is coming from. My server version is 1.11.2.

I also can't use an Entity Type condition to check if it's a player, since Citizens are still technically the Player entity. Could you perhaps add an "Is-Player" condition?

**Comment by Eniripsa96** [comment]
Sounds more like an issue with how the other plugin manages "invincibility". It should just cancel damage events which would block anything from SkillAPI.
