### ISSUE TITLE
Bonus Damage Isn't Attributed to Player

### ISSUE THREAD

**Issue by co221133** [Eniripsa96/SkillAPI#167]
I've been having an issue wherein I give a certain class a bonus physical damage boost (with Damage Buff multiplier mechanic), but if that damage boost is what kills a mob or player, then the player with the damage boost isn't credited with the kill. It just says "{Victim} has been killed by null." 

Is there any way you can make sure the player is given credit for any kills done by their abilities or damage-boosted attacks?

**Comment by Eniripsa96** [comment]
Seeing as damage buffs simply modify the amount in Bukkit damage events, this shouldn't be the case unless Spigot has a bug. Are you sure there isn't something else that uses a Damage mechanic or some other skill damage variant? Also, what SkillAPI/Spigot versions are you using?
