### ISSUE TITLE
Support Maven/Gradle for JitPack

### ISSUE THREAD

**Issue by Mishyy** [Eniripsa96/SkillAPI#169]
#58

**Comment by Eniripsa96** [comment]
From what I can tell, that tool is meant to pull code from git repos and doesn't require anything on my part. After plugging in the SkillAPI repo, there's [this](https://jitpack.io/#Eniripsa96/SkillAPI/cbef614fdb)

**Comment by skyybender** [comment]
Sorry for posting in old issues but did someone manage to add SkillAPI to a project this way? I only get the message that there is no build file in this repository. Here the JitPack log for some versions:
https://jitpack.io/com/github/Eniripsa96/SkillAPI/cbef614fdb/build.log -> version of your link
https://jitpack.io/com/github/Eniripsa96/SkillAPI/48a5fb5/build.log -> v3.99
https://jitpack.io/com/github/Eniripsa96/SkillAPI/a692ccb/build.log -> current commit

**Comment by OsipXD** [comment]
@Eniripsa96, can you add tags with version numbers please? It would be cool.
