### ISSUE TITLE
Click Combos Question

### ISSUE THREAD

**Issue by KillOrDi3** [Eniripsa96/SkillAPI#170]
i recently added skillapi its really good plugin and easy to use but i test myself the skills and i didnt need even to /bind an item...it was just etc.l,r,l,r and i could cast my skill with empty hotbar...can i bind the skills to a item so the players need to have the item to cast them?

**Comment by Eniripsa96** [comment]
You can't set specific items in general for binding, but you can make skills require an item to be cast using an Item condition. You can also disable click combos if you don't want that to be something players can do.
