### ISSUE TITLE
Skills show up on offline server, but not on online server.

### ISSUE THREAD

**Issue by WeasomeKarma** [Eniripsa96/SkillAPI#171]
Hello, firstly this plugin is amazing and is incredibly useful to me and my server :)

Here are some images I took for you: http://imgur.com/gallery/S6ILf

I have run into an issue I cannot seem to give a method for replication where skills will load on my online server but not show up, but on my offline server they work just fine (kind of, will get back to it later)

In here I have a lot of images for you to look through. If you notice on the online server two of the skills are shifted more to the left, I can only imagine that after the skills are loaded they fail on being added to some kind of data structure for the GUI menu.

I think it could be a plugin incompatibility with CustomRecipies, CustomItems, ChatItem??, and maybe MythicMob Artifacts. 

I have deleted the online server SkillAPI folder and put an EXACT copy of the offline server folder up (same jar too) and the issue still persists.

I will check to see if it is a incompatibility.
---------------------------------------------------------------------------
My other issue is that I have premium SkillAPI but the Slot condition and Else condition don't see to work. In one of the images you can see my hotbar filled with buttons, but when testing (using slot numbers 0-8, all put into separate lines in the Dynamic Editor (0,1,2,3,4..8) ) it doesn't trigger inside of a passive skill. And when testing to see if a player is holding a wooden sword, if they are not the else doesn't trigger. My else blocks are not inside the condition blocks for which they are intended to catch, but bellow on the same level of indentation.

Other premium features, such as EntityType work just fine.

**Comment by Eniripsa96** [comment]
Would you be able to provide your skill config so that I can maybe see what's going on? As for the server issue with the skill tree, have you tried using "/class customize"? how does that menu behave?

**Comment by WeasomeKarma** [comment]
Thank you for the GUI explanation, I didn't know that command existed.

Here is my config files for Backstab and my config file for Light Armor

I also attached the classes.yml and skills.yml incase u wanted to see it in
the dynamic editor.

**Comment by WeasomeKarma** [comment]
Whoa... Okay... it magically just fixed itself...

Thanks! You're plugin is absolutely amazing, and so are you :)

**Comment by Eniripsa96** [comment]
Glad it is working
