### ISSUE TITLE
Skill points per class

### ISSUE THREAD

**Issue by SaitDev** [Eniripsa96/SkillAPI#172]
We give player some skill points per level but these points can be used on any class that they turned in. How to make these points separate to each class?

Thanks in advance

**Comment by Eniripsa96** [comment]
Why do you need them per class? If you want some classes to learn more skills than others, just make the skills cost less skill points.

**Comment by SaitDev** [comment]
to balance all build possible, something like they keep almost points from a utility class then max all skills on other damager classes. So I want divide same points to each class they can use, they must decide for them, cant max all skills

**Comment by Eniripsa96** [comment]
Different class groups have separated skill points already.

**Comment by SaitDev** [comment]
I see. Can a class turn into other classes in other group?

**Comment by AngDrew** [comment]
Its impossible for now
Because they have separated data

**Comment by SaitDev** [comment]
I hope separate skill points will be supported. Or maybe not?

**Comment by AngDrew** [comment]
It should be able now
Steven replied that read it 👆

**Comment by SaitDev** [comment]
But u mean use different class groups right? that made impossible for player turn into classes on other group. if put all those classes to same group, then no separate skill points. if use many group, main class of each group can profess from starting lv, doesnt it? this make player got all classes at the beginning, i love the way skillapi support parent class though

**Comment by Eniripsa96** [comment]
Right now, you can only be one class from any given group at a time, so I'm not sure what you're looking for. Do you mean when you profess into a specialization, you want to reset the skill points as if it were a new class? Have you tried the "profess-reset" option in "groups.yml"?

**Comment by SaitDev** [comment]
Sorry for not explain clearly enough. Like a player has main class A in default group. At max level of class A, he has 10 skill points, he used 6 of them for some class A's skills. Now he profess to new class B. When max level of class B he gets more 10 skill points, so he can use 14points on class B's skill.
But I wanna he can only use 4 points remain from class A on class A's skills, and 10 points for class B's skills. Same with future skill points if he profess to class C, he can not use them back on class B's skills

**Comment by Eniripsa96** [comment]
Sounds like what would be more useful is a new requirement option for skills, being needing a number of skill points spent before unlocking/upgrading the skill. That seems like it would cover your case along with skills within the same class tree for others if desired. I'll mark it as an enhancement and get around to it when I get the chance.

**Comment by Eniripsa96** [comment]
Wad added in 1.52

**Comment by SaitDev** [comment]
your idea using points-spent-req is nice too but it seem doesnt really cover my case. To prevent player using points from newest class to upgrade skills on old classes, we need something like points-spent-min-req and points-spent-max-req. I have an idea like saving skill point of each class in player's data but it may break ur database management

**Comment by Eniripsa96** [comment]
Storing data in the "getExtraData()" object shouldn't impact anything with how SkillAPI stores things. It's designed for generic data being put into it.
