### ISSUE TITLE
Dynamic Editor changes files

### ISSUE THREAD

**Issue by Whisk3yFire** [Eniripsa96/SkillAPI#175]
Generating skills ourselves doesn't work using the editor. So we used the examples as a baseline and those worked. So we loaded up the example to the dynamic editor and then saved it, nothing else was done to it. The code was different and the new skill no longer worked. Tried using it on skillAPI 3.01 on 1.11 sever and SkillAPI 3.01,3.03 on 1.12 sever and both didn't work.

https://pastebin.com/keJM1wFZ  (example)
https://pastebin.com/su4bvhbZ   (changed)

**Comment by Eniripsa96** [comment]
Just tried both layouts with 3.103 and they seem to work fine, so a couple questions:

1. Are there any errors in the console on startup or when you cast the skill?
2. Where are you placing the files in the server?
3. What are the files named?
4. How are you reloading the changed files?

**Comment by Whisk3yFire** [comment]
1.  errors in the console stating that they failed to load.
 2. Placing the files in the  plugins/API/Dynamic/skills
 3. Names are example "No hunger.yml"
 4. Reloading the files by removing the old ones, adding in the new ones and removing the skills.yml file in the dynamic folder before restarting

**Comment by Eniripsa96** [comment]
Does the failure message say anything in particular?

**Comment by Whisk3yFire** [comment]
No, nothing useful, just that it failed to load

**Comment by Eniripsa96** [comment]
What server are you using?
