### ISSUE TITLE
Some attri not display properly on skill lore

### ISSUE THREAD

**Issue by SaitDev** [Eniripsa96/SkillAPI#177]
As I tried `{attr:level}` and `{attr:spent}` keep result as 0 regardless of how skill attribute settings has. The problem appear on premium version only. Test on free version `{attr:level}` work fine with same settings. 
Not sure about other attribute, havent tried all

Both are latest version: 1.59 and 3.103

**Comment by Eniripsa96** [comment]
Level and spend go through requirements and have different keys: "{req:lvl}" and "{req:min-points-req}"

**Comment by SaitDev** [comment]
please check it. yes both {req:lvl} and {req:level} work. but I mean about `{attr:level}` It display properly on free version (display as next skill level if not max yet). on premium version it alway display as 0

**Comment by Eniripsa96** [comment]
I just tried {attr:level} and it shows the level correctly. Also, the spent attribute shows up when you use {attr:points-spent-req}

**Comment by SaitDev** [comment]
thats strange. Im using same config files when test with premium and free version. But only free version works correctly

**Comment by SaitDev** [comment]
@Eniripsa96 Can u please help me make it work out. I tried reset skillapi config, use default class + default skill from dynamic editor tool `{attr:level}` still not display correctly

**Comment by Eniripsa96** [comment]
Is there a reason you can't just use {req:level}?

**Comment by SaitDev** [comment]
Hmm in my case, Yea I add another name to Icon Key to use it in skill's lore instead of {attr:level} But its strange when with same config skillapi works but skillapi premium not

**Comment by Eniripsa96** [comment]
It does sound odd, particularly when I am unable to get the same result. I would fix it if I were able to get the issue myself, but without being able to replicate it, it makes it difficult to figure out what could cause it.
