### ISSUE TITLE
SKILLS CANNOT WORK!

### ISSUE THREAD

**Issue by SnUncle** [Eniripsa96/SkillAPI#179]
zh: 
  name: 'zh'
  type: 'Dynamic'
  max-level: 5
  skill-req-lvl: 0
  needs-permission: 'false'
  attributes: 
    level-base: '1'
    level-scale: '1'
    cost-base: '1'
    cost-scale: '0'
    cooldown-base: '0'
    cooldown-scale: '0'
    mana-base: '0'
    mana-scale: '0'
    points-spent-req-base: '1'
    points-spent-req-scale: '0'
    incompatible: 
    - ''
  msg: '&6{player} &2has cast &6{skill}'
  icon: 'IRON_SWORD'
  icon-data: 0
  icon-lore: 
  - '&d{name} &7({level}/{max})'
  - '&2Type: &6{type}'
  - ''
  - '{req:level}Level: {attr:level}'
  - '{req:cost}Cost: {attr:cost}'
  - ''
  - '&2Mana: {attr:mana}'
  - '&2Cooldown: {attr:cooldown}'
  desc:  []
  components: 
    Cast: 
      type: 'trigger'
      indicator: '3D'
      data: 
        icon-key: ''
        indicator: '2D'
      children: 
        Self-b: 
          type: 'target'
          indicator: '3D'
          data: 
            icon-key: ''
            indicator: '2D'
          children: 
            Chance-c: 
              type: 'condition'
              indicator: '3D'
              data: 
                icon-key: ''
                chance-base: '100'
                chance-scale: '0'
                indicator: '2D'
              children: 
                Attribute-d: 
                  type: 'mechanic'
                  indicator: '3D'
                  data: 
                    icon-key: ''
                    counts: 'True'
                    key: 'Intelligence'
                    amount-base: '5'
                    amount-scale: '2'
                    seconds-base: '3'
                    seconds-scale: '0'
                    indicator: '2D'
                  children:  {}
                Message-e: 
                  type: 'mechanic'
                  indicator: '3D'
                  data: 
                    icon-key: ''
                    counts: 'True'
                    message: '你好厉害啊！'
                    indicator: '2D'
                  children:  {}
 I write the config like this ,put it in my skill floder and write into my class like this 

Soldier: 
  name: 'Soldier'
  prefix: '&6卫兵'
  group: 'Class'
  mana: '&2耐力'
  max-level: 40
  parent: ''
  needs-permission: 'false'
  attributes: 
    health-base: '30'
    health-scale: '1'
    mana-base: '10'
    mana-scale: '1'
    vitality-base: ' {}'
    vitality-scale: '0'
    spirit-base: '0'
    spirit-scale: '0'
    intelligence-base: '0'
    intelligence-scale: '0'
    dexterity-base: '0'
    dexterity-scale: '0'
    strength-base: '2'
    strength-scale: '0'
  mana-regen: 1.0
  tree: 'LEVEL_HORIZONTAL'
  skills: 
  - 'zh'
  icon: 'JACK_O_LANTERN'
  icon-data: 0
  icon-lore: 
  - '&a波尔图&f的卫兵。'
  exp-source: 273

BUT in the game when type "/class skill" nothing in the gui 
and when i type "/class bind zh“ my server answer me "you have not unlocked that skill" !!

btw i copy the class and skills from ur wiki and the skills can not damage anybody !

Apologize for my bad English

**Comment by Eniripsa96** [comment]
First, make sure it doesn't have any problems on startup. Second, make sure both are added to the server properly ([guide here](https://github.com/Eniripsa96/SkillAPI/wiki/_Tutorial-Adding-to-Server)). Third, use "/class customize" and use the bottoms along the bottom to get to the skill tree for your class to see if anything shows up.

**Comment by SnUncle** [comment]
i type class "/class customize" but nothing in the gui :(

**Comment by SnUncle** [comment]
thx for you
