### ISSUE TITLE
Skillapi DynamicEditor Broken!

### ISSUE THREAD

**Issue by MWFIAE** [Eniripsa96/SkillAPI#181]
Hey there, 

the editor is broken, as far as I could test every browser is affected and it's impossible to create functioning files as long as this bugs persists.
One cannot assign skills to classes among other things. It even deletes previously assigned skills.  

That is because after "Mana" every attribute is duplicated and overwrites the real field as seen in this screenshot.

![image](https://user-images.githubusercontent.com/6072971/31319294-ea95f7a0-ac60-11e7-8b1f-585359ea0750.png)

The bug lies within this method/call:
https://github.com/Eniripsa96/SkillAPI/blob/36112787187b41f64d8e4ec3f9a38aa6a382dd6a/editor/js/class.js#L98

Before the call everything is fine, but messed up afterwards.

I think the index for this call shouldn't be "i+1", but "10" instead. 

PS: If you want to reward bug reports... I wouldn't mind the premium version of skillapi ;) :)

**Comment by Eniripsa96** [comment]
Should be fixed now. Also, I'm not sure what you mean by "reward" for bug reports.

**Comment by MWFIAE** [comment]
As Skillapi is a commercial resource it would be nice to give contributors at least a free copy of it. 
That way I could find more bugs ;)

Not to mention that this was a critical issue and could turn down a few of the users that wanted to buy skillapi otherwise :)

**Comment by AngDrew** [comment]
Dude the free version is more than enough for that 😂
The premium version dont have much differences with the free one
People help steven just for free. Its like "thank you" for the plugin

You shouldnt ask for the premium for free thats the point
Respect his work dude

**Comment by MWFIAE** [comment]
You can't find bugs in the premium features of the plugin if you don't have it :) 
 
So wouldn't the plugin be like a "thank you" to the people who help out steven for free? ;) 

Also note that I'm neither demanding it, nor have I said I wouldn't help out otherwise. It was just a question and it doesn't hurt to ask.

Also to be honest I'm not a fan of premium plugins in general. Most of the time we apply our own patches to plugins, either because or demands are to specific to be included in the plugin itself or the plugin isn't even updated anymore and we make it work with our mc-version or add features we need (we even had a custom version of skillapi running at some point, before we decided we would extract the code into an addon, to make updating easier at the cost of performance and usability), but the point is: with premium you won't get the sourcecode, you can't decompile, basically anything is more difficult just to prevent leaks so that people who wouldn't have bought it in the first place can't use it without some effort. It is even worse if the author decides at one point to just vanish. 

So yes, I do respect his work, but the extra trouble wouldn't legitimate the price in my (somewhat special) case. Basically I would just use the premium version to test out some features and backporting them to the "opensource version" if needed and of course reporting any bugs I would find with that.


tl,dr: I wasn't trying to be rude or anything, but premium is never worth the money for us.
