### ISSUE TITLE
DynamicEditor input bug (Replicate-able)

### ISSUE THREAD

**Issue by WeasomeKarma** [Eniripsa96/SkillAPI#183]
Hey this plugin is amazing, which is why I want to point out a bug to help.

If you add a Mechanic: Particle in the DynamicEditor, and in Particle Speed but a decimal value, it will error out in game. Took me a while to figure out because I thought that the skill lacked a proper target or something, but when I checked the console to forcecast the skill I found out this issue.

Just a user being dumb related issue, but an issue none the less I guess.

Thanks for making an awesome plugin!

**Comment by Eniripsa96** [comment]
What is the error you get? Look at the code, it parses as a double so it should be ok

**Comment by Eniripsa96** [comment]
Closing due to no response
