### ISSUE TITLE
Dynamic Editor Duplicate Sound

### ISSUE THREAD

**Issue by MWFIAE** [Eniripsa96/SkillAPI#184]
If one duplicates a sound-mechanic like this:

![image](https://user-images.githubusercontent.com/6072971/31349808-105f5e3a-ad25-11e7-8873-2eec3db91355.png)

The new sound-mechanic has duplicated sound-fields, as seen here: 
![image](https://user-images.githubusercontent.com/6072971/31349824-1b889d30-ad25-11e7-8941-ada0b87b5495.png)

Resulting in a broken skill.

As the dropdown contains different soundvalues I'm suspecting it has something to do with the Server-Version field

Greetings,
MW

**Comment by Eniripsa96** [comment]
I've pushed a fix. It should apply to the site shortly.
