### ISSUE TITLE
TrueDamage not playing the Hit-Animation

### ISSUE THREAD

**Issue by MWFIAE** [Eniripsa96/SkillAPI#188]
We are forced to use the truedamage flag in the damage mechanic as we have other plugins handling the normal damage-event.
But with this the "hit animation" (meaning the player turning red) isn't played.
Can we get this? :)

**Comment by Eniripsa96** [comment]
I can try finding a way to do so, but ignoring all damage modifiers within SkillAPI and other plugins isn't an easy task. The only sane solution I knew of skips what seems to cause the damage effect, so this wouldn't be trivial.

**Comment by MWFIAE** [comment]
I don't think we can use the normal damage event and do some crazy stuff to make that work without bugs, but I've read that it could work with the EntityEffect HURT, but I never tried using it myself
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/EntityEffect.html#HURT
Source https://www.spigotmc.org/threads/protocollib-damage-animation.252134/#post-2509382


As an alternativ you could try using packets, here is a old comment from comphenix on this subject:
https://bukkit.org/threads/damage-effect-with-no-damage.136545/#post-1600776

`
        if (sender instanceof Player)  {
            Player player = (Player) sender;
            PacketContainer entityStatus = new PacketContainer(Packets.Server.ENTITY_STATUS);
 
            entityStatus.getIntegers().write(0, player.getEntityId());
            entityStatus.getBytes().write(0, (byte) 2);
 
            try {
                ProtocolLibrary.getProtocolManager().sendServerPacket(player, entityStatus);
            } catch (InvocationTargetException e) {
                e.printStackTrace();
            }
            return true;
        }
        return false;
`

Or, if not using protocolLib
`import net.minecraft.server.v1_5_R2.Packet38EntityStatus;
import org.bukkit.craftbukkit.v1_5_R2.entity.CraftPlayer;
 
public class ExampleMod extends JavaPlugin implements Listener {
    @Override
    public boolean onCommand(CommandSender sender, Command command, String label, String[] args) {
        if (sender instanceof Player)  {
            Player player = (Player) sender;
            Packet38EntityStatus status = new Packet38EntityStatus(player.getEntityId(), (byte) 2);
 
            ((CraftPlayer) player).getHandle().playerConnection.sendPacket(status);
            return true;
        }
        return false;
    }
}`

Unfortunatly it is really old and I'm not sure if this is the valid way to do it nowadays. And the protocol wiki always leaves me more confused. 

Also sorry for the formatting, it seems as the github markup leaves me confused, too.

**Comment by Eniripsa96** [comment]
Since true damage causes other problems than just not playing the hurt effect, I'd rather investigate a more comprehensive solution. I'll close out this issue since problems with true damage are listed elsewhere and cover the problem as a whole.
