### ISSUE TITLE
NullpointError

### ISSUE THREAD

**Issue by DrkMatr1984** [Eniripsa96/SkillAPI#191]
Running latest version of SkillAPI Premium, McCore, Spigot, etc.

Getting this nullpoint whenever I hit anything, here are my logs. Initially thought it was due to not having any classes or skills created, so I created a basic skill and class, and I still get the error.

[latest.log](https://github.com/Eniripsa96/SkillAPI/files/1386276/latest.log)

**Comment by Eniripsa96** [comment]
Looks like it's a bug with click combo tracking. I'll fix it for the next version.

**Comment by DrkMatr1984** [comment]
You were right, it's definitely something with click combos. If I disable them, I don't get the error. Anyway, here is my config.yml to help you diagnose the root cause.


[config.zip](https://github.com/Eniripsa96/SkillAPI/files/1387995/config.zip)

**Comment by Eniripsa96** [comment]
Should be fixed in 1.64
