### ISSUE TITLE
Custom Attributes Icons not Loading in /class attr GUI

### ISSUE THREAD

**Issue by DrkMatr1984** [Eniripsa96/SkillAPI#192]
I created this Custom attributes.yml, all the skills seem to load fine in my server logs, but in the gui in game it doesn't show them all.

![image of gui](https://image.prntscr.com/image/4IDhpqUyQnOFcPCIvBKQQQ.png)

[my attributes.yml zipped up](https://github.com/Eniripsa96/SkillAPI/files/1397134/attributes.zip)

**Comment by AngDrew** [comment]
It seems like you have unsupported item id on your att.yml

**Comment by DrkMatr1984** [comment]
Yeah, I thought that also, but initially I had "golden sword" instead of "gold sword" in my yml, and SkillAPI gave an error saying unsupported material name. I fixed that, ran through .yml parser, etc. I got the gold sword to show up but not sure which other material might be messed up.

**Comment by AngDrew** [comment]
I forgot about something
Is the att.yml support spacing through the material name (like ink sack or ink_sack instead)

**Comment by Eniripsa96** [comment]
If there's not an error, it is likely a block material being used, as those are valid materials but vanish as soon as you add them to an inventory. I will likely be adding something to detect such materials and give appropriate warnings/errors.

**Comment by DrkMatr1984** [comment]
`
# Attributes.yml

# For full details, visit
# http://dev.bukkit.org/bukkit-plugins/skillapi/pages/attributes/

# List of available stats to modify:
#   health           - the max health of the player
#   mana             - the amount of mana the player has
#   mana-regen       - how much mana the player regenerates over time
#   physical-damage  - damage dealt without using skills
#   physical-defense - damage taken from non-skill attacks
#   skill-damage     - damage dealt with skills
#   skill-defense    - damage taken from skills
#   move-speed       - movement speed of the player
strength:                     #Red
  display: 'Strength'
  max: '999'
  icon: 'gold sword'
  icon-data: '0'
  icon-lore: 
  - '&6Strength &7(&2{amount}&7)'
  - ''
  - '&7&oGrants &e3.5%&7&o increased'
  - '&cphysical damage&7&o per'
  - '&7&opoint invested'
  global: 
    condition:  {}
    mechanic:  {}
    target:  {}
  stats: 
    physical-damage: 'a*0.035+1*v'
dexterity: 
  display: 'Dexterity'
  max: '999'
  icon: 'elytra'
  icon-data: '0'
  icon-lore: 
  - '&6Dexterity &7(&2{amount}&7)'
  - ''
  - '&7&oGrants &e3.5% &7&oincreased'
  - '&amovement speed &7&oand &e3.5%'
  - '&7&oincreased &2attack speed'
  - '&7&oper point invested'
  global: 
    condition:  {}
    mechanic:  {}
    target:  {}
  stats:
    move-speed: 'a*0.035+1*v'
    attack-speed: 'a*0.035+1*v'
focus: 
  display: 'Focus'
  max: '999'
  icon: 'spectral arrow'
  icon-data: '0'
  icon-lore: 
  - '&6Focus &7(&2{amount}&7)'
  - ''
  - '&7&oGrants &e3.5% &7&oincreased'
  - '&erange &7&oper point invested'
  global: 
    condition:  {}
    mechanic:  {}
    target: 
      Cone-range: 'a*0.035+1*v'
      Linear-range: 'a*0.035+1*v'
      Location-range: 'a*0.035+1*v'
      Nearest-radius: 'a*0.035+1*v'
      Single-range: 'a*0.035+1*v'
constitution:                #Dark Red and Blue
  display: 'Constitution'
  max: '999'
  icon: 'shield'
  icon-data: '0'
  icon-lore: 
  - '&6Constitution &7(&2{amount}&7)'
  - ''
  - '&7&oGrants &e2 &4health &7&oand'
  - '&e3.5%&7&o increased'
  - '&1physical defense &7&oper'
  - '&7&oper point invested'
  global: 
    condition:  {}
    mechanic:  {}
    target:  {}
  stats: 
    health: 'a*2+v'
    physical-defense: 'a*0.035+1*v'
intelligence: 
  display: 'Intelligence'
  max: '999'
  icon: 'enchanted book'
  icon-data: '0'
  icon-lore: 
  - '&6Intelligence &7(&2{amount}&7)'
  - ''
  - '&7&oGrants &e&o3.5% &7&oincreased'
  - '&3magic damage &7&oand &e&o3.5%'
  - '&7&oincreased &5magic defense'
  - '&7&oper point invested'
  global: 
    condition:  {}
    mechanic:  {}
    target:  {}
  stats:
    skill-defense: 'a*0.035+1*v'
    skill-damage:  'a*0.035+1*v'
wisdom: 
  display: 'Wisdom'
  max: '999'
  icon: 'written book'
  icon-data: '0'
  icon-lore: 
  - '&6Wisdom &7(&2{amount}&7)'
  - ''
  - '&7&oGrants &e2 &bmana &7&oand &e3.5%'
  - '&dmana regeneration &7&oper'
  - '&7&opoint invested'
  global: 
    condition:  {}
    mechanic:  {}
    target:  {}
  stats: 
    mana: 'a*2+v'
    mana-regen: 'a*0.035+1*v'
luck: 
  display: 'Luck'
  max: '999'
  icon: 'rabbit foot'
  icon-data: '0'
  icon-lore: 
  - '&6Luck &7(&2{amount}&7)'
  - ''
  - '&7&oGrants &e3.5% &7&oincreased'
  - '&6luck &7&oand &e3.5% &7&oincreased'
  - '&fexperience &7&oper point'
  - '&7&oinvested'
  global: 
    condition:  {}
    mechanic:  {}
    target:  {}
  stats: 
    mana: 'a*0.035+1*v'
    mana-regen: 'a*0.035+1*v'
`

**Comment by DrkMatr1984** [comment]
https://pastebin.com/raw/Hnt6t0Bg

**Comment by Eniripsa96** [comment]
There's not a limit, no. Have you tried using "/class customize" and looking at the attribute menu there? It could be some of the icons just aren't placed in the menu.

**Comment by DrkMatr1984** [comment]
No, I haven't! I'll check it out later and let you know if it's working.

**Comment by DrkMatr1984** [comment]
Yeah, it's working Fine :P I didn't realize I had to add them through the GUI. I haven't used SkillAPI since 1.7 versions haha
