### ISSUE TITLE
Chat prefixes not working

### ISSUE THREAD

**Issue by durson54** [Eniripsa96/SkillAPI#193]
Hey, so I have a problem. Chat prefixes for classes aren't working and I'm not using any prefix plugin like nametagedit etc.

**Comment by Eniripsa96** [comment]
Are there any errors? Is "show-class-name" enabled? Is "chat-enabled" set to true for MCCore? What server version are you running?

**Comment by durson54** [comment]
There's no errors in console, "show-class-name" is enabled,"chat-enable" is true. Server is 1.12

**Comment by durson54** [comment]
._.

**Comment by durson54** [comment]
Ok, so it's really wierd...It's working now, I enable scoreboard in config but it shows only in tablist and it's showing level now too...but it's not showing scoreboard and I want prefix also in chat but it's only in tablist.

**Comment by Eniripsa96** [comment]
Do you have any chat-related plugins?

**Comment by durson54** [comment]
I have Essentials chat format and group formats

**Comment by AngDrew** [comment]
Then you need to setup your essentials config.. i have the same problem on past

**Comment by AngDrew** [comment]
Something about prefix search it and edit it
Search "prefix"
Let other plugin bla bla bla... set to true

**Comment by durson54** [comment]
Yeah it's change-displayname. Thanks man :D

**Comment by AngDrew** [comment]
Sure..
Please close this issue
[solved] from my phone xD

**Comment by durson54** [comment]
xd
