### ISSUE TITLE
/class options not showing GUI

### ISSUE THREAD

**Issue by durson54** [Eniripsa96/SkillAPI#194]
Hello, so when I started using skillapi I think that when i typed /class options it showed GUI with classes But now it just says it in chat which classes are here.

**Comment by Eniripsa96** [comment]
It did not. If you type "/class profess" with no arguments, it shows the GUI.

**Comment by durson54** [comment]
It doesn't. It shows in chat what classes you can profess into not GUI

**Comment by Eniripsa96** [comment]
"/class profess" - GUI
"/class options" - text list

**Comment by durson54** [comment]
When i type /class profess it shows in chat not GUI. It shows this in chat:
---------------------------------------------------
/class profess <class>
---------------------------------------------------
Will choose class ( I have trasnlated it to my language so it's probably like that )
---------------------------------------------------
And when i type /class options it shows this: ( Again, I translated it so it should be like that )
--------------------- Classes ---------------------
Classes: None or list of classes
---------------------------------------------------
