### ISSUE TITLE
MaterialData not working for unassigned skills?

### ISSUE THREAD

**Issue by MWFIAE** [Eniripsa96/SkillAPI#195]
I'm trying to use colored dye for my skills, but it isn't working as expected.

![image](https://user-images.githubusercontent.com/6072971/31865312-5134b9e4-b76d-11e7-919d-c158c6df1890.png)

It shows an ink sack in the skillbar and not the right dye. 
Please help :)

**Comment by durson54** [comment]
replace 'INK_SACK' with 'DYE' and try again :)

**Comment by MWFIAE** [comment]
hey there!
thanks for the reply :)

Unfortunatly DYE doesn't work at all (showing pumpkin seeds instead). That's because bukkit internal its called INK_SACK. 


Also I just realized it does change the data value in the config from an int to a string after reload, so maybe there is a problem with the way it is saved.

**Comment by Eniripsa96** [comment]
It converting to a string shouldn't affect it. What is happening exactly, just showing as a plain ink sack?

**Comment by MWFIAE** [comment]
Yes, just a plain black ink sack. 

We also tested with wool once, but it was just white instead of colored

**Comment by durson54** [comment]
try to replace data with icon-data: maybe it will work, try it

**Comment by MWFIAE** [comment]
Well, as far as I can tell from reading the code "data" would be right.
        unassigned.setData(new MaterialData(mat, (byte) icon.getInt("data", 0)));

But just to be sure I will try it out once I'm at home. ~6h

**Comment by MWFIAE** [comment]
Sry, I didn't had the time yesterday... 

Today I tested "icon-data", but this also doesn't work.

**Comment by MWFIAE** [comment]
Anybody else an idea? 
Can you reproduce it @Eniripsa96 ?

**Comment by Eniripsa96** [comment]
Fixed in 1.69
