### ISSUE TITLE
Class unlock thru skill

### ISSUE THREAD

**Issue by durson54** [Eniripsa96/SkillAPI#197]
I have a class and I want to have it like skill : When he reaches lvl 48 he'll get this skill and he can use it. The skill is Cast - Self - Command : "pex user %player_name% add skillapi.class.demon-hunter" > Console
But when I activate that skill it adds permission not permission to player, I have installed PlaceHolderAPI and I have downloaded Player placeholder so idk what's wrong. Maybe i'd work thru OP not Console but I don't have permissions if I have OP. Or is there some way that he'll have permission to that class when he levels up? So it doesn't have to be skill? ._.

**Comment by AngDrew** [comment]
Condition class level 48
Run command mechanic as console
Pex user %player% add skillapi.newclass
But i dont know if you use placeholderapi
If the skillapi supporting placeholderapi, i think it will be something like %skillapi......%

**Comment by durson54** [comment]
pex user %player% add skillapi.class.demon-hunter isn't working. It just adds permission "skillapi.class.demon-hunter" to permissions not to player. PAPI is supporting skillapi but there's no placeholder for player.

**Comment by Eniripsa96** [comment]
If using the command mechanic, use {player} instead of %player%

**Comment by durson54** [comment]
Ok, it's working now :D thank you :D
