### ISSUE TITLE
/Class profess not showing GUI

### ISSUE THREAD

**Issue by durson54** [Eniripsa96/SkillAPI#199]
So when I type /class profess It doesn't show GUI, idk what's wrong...It was working but it isn't now. It just says in chat /class profess class.

**Comment by durson54** [comment]
So?... I really need GUI so help me please ._.

**Comment by durson54** [comment]
I tried on another server if it'll work. It doesn't it shows the same thing.

**Comment by durson54** [comment]
Please... @Eniripsa96 Why it's not working???... I REALLY need it! My skills GUI is working so why isn't this???...

**Comment by MWFIAE** [comment]
It seems like Eniripsa wasn't active for the last 1 1/2 months, so I wouldn't expect a solution soon.

**Comment by Eniripsa96** [comment]
`/class profess` only shows a GUI on the premium version

With the free version, you can instead use:
`/class options` - shows list of classes you can profess as
