### ISSUE TITLE
Custom formula isn't working.

### ISSUE THREAD

**Issue by durson54** [Eniripsa96/SkillAPI#200]
I have enabled use-custom and this is my formula: `'x*(lvl + y)^2 + z*lvl + z'` It's not using custom formula but it's using that basic: `'x*lvl*lvl + y*lvl + z'` and my formula is:  `x: '12'`
                                                                                                                 `y: '15'`
                                                                                                                 `z: '14'`
so for example my custom formula level 30 should need 24 734 exp but instead he needs 11 264 exp.
I tried to restart server if it'll help but it's still the same...

**Comment by durson54** [comment]
So I found this error in console but idk what's wrong with it..
`Invalid equation: v+y`
`Invalid equation: x*(v+y)^2+z*v+z `

**Comment by AngDrew** [comment]
You missed x in your formula

**Comment by AngDrew** [comment]
If you dont want x just set the x value to 1 and multiply your formula with x
x*(your formula)

**Comment by durson54** [comment]
I want x in it

**Comment by durson54** [comment]
I don't understand. How did I miss x in my formula??

**Comment by AngDrew** [comment]
(v+y)^2+z*v+z    ====>Add "x" with "+-*/"(equation)

**Comment by durson54** [comment]
I added +x at the end of it and it's still not working.

**Comment by Eniripsa96** [comment]
The "custom" formula doesn't use x, y, and z. The only variable available is "lvl". x, y, and z were for the default formula since you can't otherwise change it. For your custom formula, you can just replace x, y, and z with actual numbers.
