### ISSUE TITLE
Request: Dodge Status

### ISSUE THREAD

**Issue by durson54** [Eniripsa96/SkillAPI#201]
Add a status "Dodge" = It will block any incoming damage ( not spell dmg ), add a duration to it and chance of dodge.

**Comment by AngDrew** [comment]
I created my own dodge rate and hit rate system with skills instead of attribute

**Comment by durson54** [comment]
I don't want it to be attribute,  I want it to be status like Stun,Root,Silence...

**Comment by AngDrew** [comment]
It become more easy
You will need 2 skills
1: trigger took physical dmg, targeting self, condition flag (dodge), cancel mechanic
2: the skill that cause flag to the target
Example for skill 2 trigger cast, target self, flag mechanic (dodge) for x seconds

**Comment by AngDrew** [comment]
Good night and good luck
Ill reply when i woke ;D
Feel free to ask
Ill help around skill, editor, attribute

**Comment by durson54** [comment]
I just did it on my skill with trigger: took physical dmg, target: self , condition: chance , mechanic: cancel
and it's working :D so thanks for the idea :P

**Comment by AngDrew** [comment]
Sure anytime you want to ask just ask and please close the issue
