### ISSUE TITLE
[BUG] Could not create own attributes

### ISSUE THREAD

**Issue by sumdream** [Eniripsa96/SkillAPI#204]
I`m tring to create an my own attribute,but in  attr GUI only display default attr.
The lore-attributes is work fine.

**Comment by AngDrew** [comment]
Maybe u have the same id like

Strength:

Strength: 

Vitality: 

Agility: 

Etc.

**Comment by DrkMatr1984** [comment]
https://github.com/Eniripsa96/SkillAPI/issues/192

**Comment by sumdream** [comment]
yeah it`s useful,THX!!!!
And more the attr does not work when I use right click to equip item but it work when use other way to equip.

**Comment by Eniripsa96** [comment]
Closing due to age of the issue and being unable to reproduce the lingering problem. Feel free to re-open if you still need the help.
