### ISSUE TITLE
Question: How can I make passive skill give mana?

### ISSUE THREAD

**Issue by durson54** [Eniripsa96/SkillAPI#205]
So I want a skill that's Initialize so it'll be passive and that it'll give player more mana. Not restore mana. So is it possible? But I don't want it with value bcs it would take his mana and then give it to him if I understand it.

**Comment by AngDrew** [comment]
It is possible with attribute not skills
Create attribute drop it on editor then add attribute everytime they are leveled up...
And if you dont want player use the attribute, set the max level to 0
