### ISSUE TITLE
Item blacklist not working.

### ISSUE THREAD

**Issue by durson54** [Eniripsa96/SkillAPI#206]
So when I'm making class with dynamic editor I add items to "Unusable items". For example "bow". And when I look in config it's there as "Blacklist:" and items, but when I put class file in folder it just disappears and it's not here. I also tried with "BOW", "MINECRAFT:BOW" and "261" but it's just not here.

**Comment by AngDrew** [comment]
Is it premium features?

**Comment by AngDrew** [comment]
If its premium i cant ✓ for you :3

**Comment by durson54** [comment]
It's not...If it would be it would be really stupid...I mean like wtf? Why would it be premium. You couldn't create for example class archer and he could use swords and everything. Or warrior and he would be able to use bow.

**Comment by MWFIAE** [comment]
You can add a class requirement via item-lore.

**Comment by durson54** [comment]
I don't want it like that. I just want it simply thru item blacklist.

**Comment by Zeuscp1** [comment]
could you guys figure this out?

**Comment by Eniripsa96** [comment]
This is currently only available in premium.
