### ISSUE TITLE
Bugs + Issues

### ISSUE THREAD

**Issue by WeasomeKarma** [Eniripsa96/SkillAPI#207]
Hey awesome plugin, and sorry for not responding in my last idea post.

I have an issue where mobs will not be targeted based on their name, and they will become invincible too.

The issue is in the file attached (Banish.yml). It doesn't test if the target has "Summoned" in their name. Is that condition exclusively for players? Also in (Banish1.yml) the mob will become invincible, and commands with mythicmobs such as ./mm mobs killall will not kill it. Only ./butcher -t works (wont work without -t) Potential plugin conflict? The invincibility is not an issue for me (since the Banish skill will teleport the mob to the void) but I thought it would be something you'd like to be aware of.

Also with prefixes, I can't seem to figure out how to make some class groups show their prefix, and how to make some not. 

I have these class groups, Core, Race, and Profession. I want Race and Profession to not show a prefix, but I want Core to show a prefix. However if I leave the prefix for Race and Profession blank it will show no prefix at all. I saw that if I do give each class group a prefix they will override each other. This is fine, almost ideal, but I can't figure out in what order the override happens. I tried changing the prefixes to alphabetical order (such that a Core prefix will come before a Profession prefix) but no luck. I also tried changing the order in which they are parsed in the groups.yml config but also no luck. 

Again fantastic plugin, I couldn't imagine my server without it :)
I will do my best to frequently check my email for responses this time.

**Comment by WeasomeKarma** [comment]
Oops I forgot to attach the files despite reminding myself many times while writing this.

Banish.yml
`Banish:
  name: 'Banish'
  type: 'Cast'
  max-level: 5
  skill-req: ''
  skill-req-lvl: 1
  needs-permission: 'False'
  msg: '&6{player}&8: &3&l"I banish you!"'
  combo: ''
  indicator: '2D'
  icon: 'Iron Door'
  icon-data: 0
  icon-lore:
  - '&d{name} &7({level}/{max})'
  - '&aType: &6{type}'
  - ''
  - '&a{req:level}Level: &a{attr:level}'
  - '&a{req:cost}Cost: {attr:cost}'
  - ''
  - '&2Mana: {attr:mana}'
  - '&2Cooldown: {attr:cooldown}'
  - ''
  - '&8 *&7 Activates on cast.'
  - '&8 *&7 Requires a target.'
  - '&8&l -&3Deal 8 damage to a target within 2 meters. If it is'
  - '&8&l -&3a summoned creature with less health than you it is '
  - '&8&l -&3instantly killed, and you get Strength I for 4 seconds.'
  - '&8&l -&3Otherwise it gets Weakness V for 10 seconds.'
  - '&8&l -&3At skill level 5 the summoned target is killed regardless'
  - '&8&l -&3Of its health.'
  - ''
  - '&3"This world is burdened by your presence. I relinquish it of you."'
  attributes:
    level-base: 41
    level-scale: 0
    cost-base: 1
    cost-scale: 1.75
    cooldown-base: 0
    cooldown-scale: 0
    mana-base: 0
    mana-scale: 0
    points-spent-req-base: 0
    points-spent-req-scale: 0
    incompatible:
    - ''
  components:
    Cast-a:
      type: 'trigger'
      data:
        icon-key: ''
      children:
        Single-b:
          type: 'target'
          data:
            icon-key: ''
            range-base: 2
            range-scale: 0
            tolerance-base: 4
            tolerance-scale: 0
            group: 'Enemy'
            wall: 'False'
          children:
            Damage-c:
              type: 'mechanic'
              data:
                icon-key: ''
                counts: 'True'
                type: 'Damage'
                value-base: 8
                value-scale: NaN
                true: 'False'
                classifier: 'default'
            Name-d:
              type: 'condition'
              data:
                icon-key: ''
                contains: 'True'
                regex: 'False'
                text: 'Summoned'
              children:
                Skill Level-e:
                  type: 'condition'
                  data:
                    icon-key: ''
                    skill: 'Banish'
                    min-level: 5
                    max-level: 99
                  children:
                    Sound-f:
                      type: 'mechanic'
                      data:
                        icon-key: ''
                        counts: 'True'
                        version: '1.9+'
                        newsound: 'Block Portal Travel'
                        volume-base: 100
                        volume-scale: 0
                        pitch-base: 1
                        pitch-scale: 0
                    Particle-g:
                      type: 'mechanic'
                      data:
                        icon-key: ''
                        counts: 'True'
                        particle: 'Ender Signal'
                        arrangement: 'Circle'
                        radius-base: 4
                        radius-scale: 0
                        particles-base: 10
                        particles-scale: 0
                        direction: 'XZ'
                        data: 0
                        forward: 0
                        upward: 0
                        right: 0
                    Warp-h:
                      type: 'mechanic'
                      data:
                        icon-key: ''
                        counts: 'True'
                        walls: 'True'
                        forward-base: 0
                        forward-scale: 0
                        upward-base: -300
                        upward-scale: 0
                        right-base: 0
                        right-scale: 0
                Health-i:
                  type: 'condition'
                  data:
                    icon-key: ''
                    type: 'Difference'
                    min-value-base: 0
                    min-value-scale: 0
                    max-value-base: -10000
                    max-value-scale: 0
                  children:
                    Sound-j:
                      type: 'mechanic'
                      data:
                        icon-key: ''
                        counts: 'True'
                        version: '1.9+'
                        newsound: 'Block Portal Travel'
                        volume-base: 100
                        volume-scale: 0
                        pitch-base: 1
                        pitch-scale: 0
                    Particle-k:
                      type: 'mechanic'
                      data:
                        icon-key: ''
                        counts: 'True'
                        particle: 'Ender Signal'
                        arrangement: 'Circle'
                        radius-base: 4
                        radius-scale: 0
                        particles-base: 10
                        particles-scale: 0
                        direction: 'XZ'
                        data: 0
                        forward: 0
                        upward: 0
                        right: 0
                    Warp-l:
                      type: 'mechanic'
                      data:
                        icon-key: ''
                        counts: 'True'
                        walls: 'True'
                        forward-base: 0
                        forward-scale: 0
                        upward-base: -300
                        upward-scale: 0
                        right-base: 0
                        right-scale: 0
                Else-m:
                  type: 'condition'
                  data:
                    icon-key: ''
                  children:
                    Potion-n:
                      type: 'mechanic'
                      data:
                        icon-key: ''
                        counts: 'True'
                        potion: 'Weakness'
                        ambient: 'True'
                        tier-base: 5
                        tier-scale: 0
                        seconds-base: 10
                        seconds-scale: 0
`

Banish1.yml

`Banish:
  name: 'Banish'
  type: 'Cast'
  max-level: 5
  skill-req: ''
  skill-req-lvl: 1
  needs-permission: 'False'
  msg: '&6{player}&8: &3&l"I banish you!"'
  combo: ''
  indicator: '2D'
  icon: 'Iron Door'
  icon-data: 0
  icon-lore:
  - '&d{name} &7({level}/{max})'
  - '&aType: &6{type}'
  - ''
  - '&a{req:level}Level: &a{attr:level}'
  - '&a{req:cost}Cost: {attr:cost}'
  - ''
  - '&2Mana: {attr:mana}'
  - '&2Cooldown: {attr:cooldown}'
  - ''
  - '&8 *&7 Activates on cast.'
  - '&8 *&7 Requires a target.'
  - '&8&l -&3Deal 8 damage to a target within 2 meters. If it is'
  - '&8&l -&3a summoned creature with less health than you it is '
  - '&8&l -&3instantly killed, and you get Strength I for 4 seconds.'
  - '&8&l -&3Otherwise it gets Weakness V for 10 seconds.'
  - '&8&l -&3At skill level 5 the summoned target is killed regardless'
  - '&8&l -&3Of its health.'
  - ''
  - '&3"This world is burdened by your presence. I relinquish it of you."'
  attributes:
    level-base: 41
    level-scale: 0
    cost-base: 1
    cost-scale: 1.75
    cooldown-base: 0
    cooldown-scale: 0
    mana-base: 0
    mana-scale: 0
    points-spent-req-base: 0
    points-spent-req-scale: 0
    incompatible:
    - ''
  components:
    Cast-a:
      type: 'trigger'
      data:
        icon-key: ''
      children:
        Single-b:
          type: 'target'
          data:
            icon-key: ''
            range-base: 2
            range-scale: 0
            tolerance-base: 4
            tolerance-scale: 0
            group: 'Enemy'
            wall: 'False'
          children:
            Damage-c:
              type: 'mechanic'
              data:
                icon-key: ''
                counts: 'True'
                type: 'Damage'
                value-base: 8
                value-scale: NaN
                true: 'False'
                classifier: 'default'
            Name-d:
              type: 'condition'
              data:
                icon-key: ''
                contains: 'True'
                regex: 'False'
                text: 'Summoned'
              children:
                Skill Level-e:
                  type: 'condition'
                  data:
                    icon-key: ''
                    skill: 'Banish'
                    min-level: 5
                    max-level: 99
                  children:
                    Sound-f:
                      type: 'mechanic'
                      data:
                        icon-key: ''
                        counts: 'True'
                        version: '1.9+'
                        newsound: 'Block Portal Travel'
                        volume-base: 100
                        volume-scale: 0
                        pitch-base: 1
                        pitch-scale: 0
                    Particle-g:
                      type: 'mechanic'
                      data:
                        icon-key: ''
                        counts: 'True'
                        particle: 'Ender Signal'
                        arrangement: 'Circle'
                        radius-base: 4
                        radius-scale: 0
                        particles-base: 10
                        particles-scale: 0
                        direction: 'XZ'
                        data: 0
                        forward: 0
                        upward: 0
                        right: 0
                Health-h:
                  type: 'condition'
                  data:
                    icon-key: ''
                    type: 'Difference'
                    min-value-base: 0
                    min-value-scale: 0
                    max-value-base: -10000
                    max-value-scale: 0
                  children:
                    Sound-i:
                      type: 'mechanic'
                      data:
                        icon-key: ''
                        counts: 'True'
                        version: '1.9+'
                        newsound: 'Block Portal Travel'
                        volume-base: 100
                        volume-scale: 0
                        pitch-base: 1
                        pitch-scale: 0
                    Particle-j:
                      type: 'mechanic'
                      data:
                        icon-key: ''
                        counts: 'True'
                        particle: 'Ender Signal'
                        arrangement: 'Circle'
                        radius-base: 4
                        radius-scale: 0
                        particles-base: 10
                        particles-scale: 0
                        direction: 'XZ'
                        data: 0
                        forward: 0
                        upward: 0
                        right: 0
                Else-k:
                  type: 'condition'
                  data:
                    icon-key: ''
                  children:
                    Potion-l:
                      type: 'mechanic'
                      data:
                        icon-key: ''
                        counts: 'True'
                        potion: 'Weakness'
                        ambient: 'True'
                        tier-base: 5
                        tier-scale: 0
                        seconds-base: 10
                        seconds-scale: 0
`

**Comment by AngDrew** [comment]
Why you dont use pastebin or upload your yml to dropbox or other cloud storage
Its easier ppl to read it in editor :|

**Comment by AngDrew** [comment]
Ah you updated it :3
Sorry

**Comment by WeasomeKarma** [comment]
Yeah I put it in a comment just incase you got here before I made the paste bin

**Comment by WeasomeKarma** [comment]
Also, could you per chance add a condition for riding a boat? Pirates arrrr.

**Comment by AngDrew** [comment]
I think you cant target mobs based on their name in minecraft
You can only do that in player

And command mythicmobs killall onlu affected mythicmobs mobs (you can test it by spawning mm mob and minecraft vanilla mob the  run cmd mm killall or kill -a you will see the mm dead or vanilla dead)

**Comment by AngDrew** [comment]
You cant hide some class prefix.. not enabled yet
But if you want show prefix on chat or tablist, you can use permission based by turn off it in skillapi config then use other plugin to edit the chat and tablist

**Comment by WeasomeKarma** [comment]
Very good fix for the prefix thank you. 

Yeah I used the Banish skill on a mythic mob, and mm killall wouldn't kill it. Im pretty sure its because of the name condition that gives it some weird form of invincibility. 

As for a temp fix I think I will have all mobs on my server typed with "summoned" be determined by a Unluck debuff instead relying on the name. If targeting based on mob names is possible that would be a REALLY neat feature.

**Comment by WeasomeKarma** [comment]
Thank you for your response, all of my issues are resolved. A potential bug is still possible, but it isn't so severe that it breaks things. Just a unexpected user behavior (me misusing a condition resulting in a bug) Feel free to resolve/archive again thank you for your help and for your amazing plugin :)

**Comment by AngDrew** [comment]
If that feature is enabled, it would target every mob named "mondter" (for example) in whole server

**Comment by AngDrew** [comment]
Btw this is not my plugin i just helping
Plugin dev:
@eniripsa96
