### ISSUE TITLE
How can I make class switch "modes" thru skill?

### ISSUE THREAD

**Issue by durson54** [Eniripsa96/SkillAPI#208]
So I have a class and I want it to switch "modes". So first mode should be "Combat" only weapons usable,no bow and different skills. Second is "Ranged" only bow, no weapons and different skills too. It could be done with 2 different skills like "Combat Mode" and "Ranged Mode" so it'll just add flag "combat" / "ranged" and i'll add condition flag to skills.. But I want it in one skill. So that they'll switch to Ranged mode if they're in Combat mode and if in Combat then in Ranged. If u understand what I mean. Also how can I make that in these "modes" they can use only bow or swords etc.?

**Comment by AngDrew** [comment]
1. Weapon specify:
Physical dmg:target self
-condition:flag(combat)
--condition:main hand(bow)
---cancel event
-condition:flag(disabled combat)
--condition:main hand(weapon?)
---cancel event

2. Flag changer:
Cast
-target:self
--flag toggle:combat

3. Diferrent skills:
add permission to each skills
Passively give you skill permission when the skill is casted
You can handle this with cast trigger,
Add permission mechanic in the my help number 2

**Comment by AngDrew** [comment]
Make the skill dmg trigger like the physical one
Im too lazy to type something in my phone
