### ISSUE TITLE
How can I make a "Power" point

### ISSUE THREAD

**Issue by durson54** [Eniripsa96/SkillAPI#209]
So I have a class and I want to make it that there'll be some skills that'll give "Power".  And there'll will be another skills that require "Power" So for example I have a skill and it requires only 3 Power. How can I do it? Also How can I make it that it'll show somewhere how much "Power" they have? Only option I see is chat but I hope there's a way to add it to actionbar

**Comment by durson54** [comment]
So I tried it with value, I have a skill that deals dmg and then adds value "power" for 1. And for another skill I added condition value and set it to 3. It deals dmg too and then it'll set value to 0. It works but just for 1 use. Then it just "freezes" and I can't use it again

**Comment by durson54** [comment]
Ok, so It works now. I forgot to add target self to set value. But how can I make it show for example in action bar? I don't want it with chat... :/

**Comment by durson54** [comment]
Another thing, how can I set value to max 3?? I don't want it to go up more than 3.

**Comment by AngDrew** [comment]
Action bar support value read in config
Limiting power:
Make the power gain skill with condition
Condition value "x" vamue min 0-3 add value
So it eill gain power pnly when you have 0-3 power
Then add something like condition when the power 4-99 it will cap power to 3

**Comment by AngDrew** [comment]
Ive play with value before
My skills a bit diferrent so it will charge my arrow when im not attacking outside combat, it will charge increase damage every sec. And ehen i hit enemy with my arrow add the value to damage and set it to 0
