### ISSUE TITLE
Is there a way to create a skill that revives?

### ISSUE THREAD

**Issue by durson54** [Eniripsa96/SkillAPI#210]
So I want to make a skill that'll revive ally and give him mana and health. But I really don't know how to revive him... O.o

**Comment by AngDrew** [comment]
Not possible because minecraft limitation

**Comment by AngDrew** [comment]
I have think about this before and im tired lol

**Comment by durson54** [comment]
:D but would It be somehow possible to use totem of undying on them? Or like give it to them and they'll have to use it or it will automatically use? O.o :D

**Comment by AngDrew** [comment]
It can be work if you code your own plugin
Algorythm:
When player death set its current location to variable
When player respawn they eill be teleported to that location
To limit it you can use skillapi api so you can check if the player have flag or value then they will be respawned

Easier way:
Install essentials
Make a skill that will remember target
When the target is dead cast other skill to make the target rum command /back
Thats how i make my resurrection skills :)
Good luck
