### ISSUE TITLE
auctionbar toggle

### ISSUE THREAD

**Issue by Kuass** [Eniripsa96/SkillAPI#211]
skillapi의 actionbar를 사용중입니다.
원하는 유저는 끌 수 있도록 토글명령어를 만들어주시면 안될까요?

You are using skillapi's actionbar.
Can you make a toggle command so that the user can turn it off?
please..

**Comment by AngDrew** [comment]
/class bar
Or just rightclick the slot if you want to custom the slot
Change config so you can lock the slot(un changeable with rightclick)

**Comment by Poseidon23** [comment]
What I'm talking about is AuctionBar, not SlotBar.

**Comment by AngDrew** [comment]
"You are using skillapi's actionbar.
Can you make a toggle command so that the user can turn it off?
please.."
U say actionbar..
There are no "auctionbar" in skillapi
Maybe you have entered the wrong github haha

**Comment by AngDrew** [comment]
Then if you want to turn it off
Just use command /class bar or edit the config file in use actionbar set it to false

**Comment by Poseidon23** [comment]
If you enter /class bar, SkillBar is disabled, but the ActionBar is still active.
I want to toggle the ActionBar.

**Comment by AngDrew** [comment]
Ah command to disable text upside of the hotbar
