### ISSUE TITLE
Frostbolt skill

### ISSUE THREAD

**Issue by durson54** [Eniripsa96/SkillAPI#212]
I want to create a skill "Frostbolt" and it will fire a snowball at enemy and I want snowball to have some particles. But how can I make it follow the target? Because there's only "Cone" in Projectile and It'll go random..So how can I make it to go to target? And also, how will I add particles to that projectile and particles will follow it?

**Comment by AngDrew** [comment]
Use effect mechanic for partivle follow the projectile (paid version)

You cant make hoaming projectile its limited by minecraft how ever this plugin cannot change that

**Comment by durson54** [comment]
And how can I make it slow down the player? I mean %, So for example Frostboll will slow down target for 50% of their current speed

**Comment by AngDrew** [comment]
Speed mechanic
Multiplyer: 0.5

**Comment by durson54** [comment]
Ooohh... :D And I was wondering why it wasn't working... :D I type "-0.5" not "0.5" :D and does it also work on mobs?

**Comment by AngDrew** [comment]
Ofcourse

**Comment by durson54** [comment]
OK, thanks :)
