### ISSUE TITLE
All professions have instant health?

### ISSUE THREAD

**Issue by chetnikk** [Eniripsa96/SkillAPI#213]
I have about 10 Races, each comes with 2-3 skills

Races cannot use skills outside of their race, and all the skills work perfectly

However - every race has a completely random occuring instant health that just sticks and makes the user basically immortal.

Im looking for some help on this, thanks

**Comment by MWFIAE** [comment]
I'm pretty sure this is caused by the "New" vanilla Minecraft behaviour that regenerates your life extremly fast while you have a full foodbar

**Comment by chetnikk** [comment]
I suspected as much, how do i resolve said issue, disable it in server properties?

**Comment by MWFIAE** [comment]
I think there is a /gamerule for that, but maybe you find a config for it :)

**Comment by chetnikk** [comment]
Nope, still persisting after disabling it, i see the Instant Health **:** on my gui like a potion

**Comment by chetnikk** [comment]
It isnt related to SkillApi upon removal of the plugin

closing topic
