### ISSUE TITLE
Parties 

### ISSUE THREAD

**Issue by aaTking** [Eniripsa96/SkillAPI#216]
我是中国的一名玩家,非常感谢您开发这么棒的插件
我有1个问题,想请教您.
Parties 插件怎么调成队友免伤,我已经是skillapi里同一个阵营了.但并没有预计的那样互相不能伤害.经验也没有共享.我找不到相关的配置.

非常感谢您的插件!这是我使用过最棒的!
期待您的回答!

I am a Chinese player, thank you very much for developing such a wonderful plug-in
I have one question for you.
I have been in the same camp in the skillapi. However, I did not expect to be able to hurt each other. The experience has not been Shared. I can't find the relevant configuration.
Thank you very much for your plug-in! This is the best I've ever used!
Looking forward to your reply!

=============================================
    mechanic:
      Damage-value: 'a+v'          #v
      Health-value: 'a+v'            #x

why?  0..0

**Comment by Tiplish** [comment]
Hi,

Same problem here.

The trick is that the first time i made a party, they where ally with me.

I try it in the same zone with the same group leader but with different people and... they were not ally anymore. 

Any clue? I haven't seen anything in the configuration to solve it.

**Comment by AngDrew** [comment]
dev said that party is not perfect yet
He will update that plugin later maybe

**Comment by Eniripsa96** [comment]
Closing in favor of #253 as they are about the same issue
