### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by durson54** [Eniripsa96/SkillAPI#222]
So I want to make it that when they switch acc they'll be teleported to spawn if they just created it, I know how to do that. But can I make it if they switch acc for example their current is lvl 10 and they switch to lvl 5 they'll be back where they were? Idk. And If they make quests would they be on that 1 account or all quests on all accs? It would be kinda bad cuz they could've just complete quest then switch acc and come and recieve XP and they'll have  boost... Also what's best plugin for creating items? I currently use RPGItems but can I make the items require a level and make them add attributes? Thanks ^^

**Comment by AngDrew** [comment]
If you want it
Just make a java plugin for handle this
Use event that will be called when you level up and save the player current location
But you cant downgrade the level like you want :/
Its complicated im confused when reading a lot of stuff like this... hehehe pardon me

**Comment by durson54** [comment]
:D It's okay, but I mean its like  when their current account is for example number 10 and have a class 10 lvl and when they switch to number 9 account and have a class lvl 5. And what about quests? Will they be on all accounts? Well I think I'll just add requirement for lvl. @AngDrew do you know anything about some good plugin to create items that works well with SkillAPI? So that the items have level requirements and can add attributes?

**Comment by AngDrew** [comment]
Ah i see
its like you want to separate the account inventory location etc.
Ive ask about this before and eniripsa will think about it.. but till now i worked by my self to create my separation (inventory, location, health) each class using skript
How?
Create a command that wil backup every single data you need
Then command to restore it when the class is changed
Its confusing but its work
To create item..
I just add the lore on it and its good for me i think thats enough
I use lore editor from spigot..
To add attribute and requirement:
Add "Strength: 1" for example to the lore of something and add "Class Req: Warrior" for example..
You can change that in config for requirement and you can use every attributes available on attributes.yml

**Comment by AngDrew** [comment]
I havent use quest for a long time..
So i dont know how to separate it

**Comment by AngDrew** [comment]
Btw, i created my own program to generating item easier with visual studio.. so i can use the same format for my server :D

**Comment by durson54** [comment]
Ummm..How did you  create that command to backup data and other one to restore it when they change class? Did you use Skript plugin or what? Cuz idk :D Can you tell me how to do it? :D And when I added lore to item it didn't work. I added lore "Vitality: 100" and it didn't work. I have it in my config like this: "attribute-text: '{attr}: '

**Comment by AngDrew** [comment]
you have to enable the attribute on your config first

I use skript plugin and code it by my self

**Comment by durson54** [comment]
I have attributes enabled in lore and it still doesn't work, any ideas? Would it work if I changed attribute-text: '{attr}: ' to something else? How do you have it?

**Comment by AngDrew** [comment]
If its not working.... review your attribute.yml look if there any problem
If you didnt see any, maybe your server out of ram or something.. try to restart the server..

Just learn how to code skript its easy and powerful

**Comment by AngDrew** [comment]
If restarted and still not working..
Then backup your skillapi folder then delete the original
Try to start with a fresh skillapi
And try to use your attribute..
If its still not work maybe you can try it on clean server.. (only skillapi and its dependencies inside it)

**Comment by AngDrew** [comment]
If still not work..
Download the latest free version
Because its working for me xD
And use spigot 1.8-1.11
Because i tested it on that version xD

**Comment by AngDrew** [comment]
And look at the space and tab in your yml..
In my case i forgot to replace the tab to space (its ling time ago) i think yml only support spaces

**Comment by AngDrew** [comment]
Count it carefully
Use comment (# comment can be anything after hastag in yml)
Try to check the comment
Maybe you uncommented something accidentally

**Comment by AngDrew** [comment]
i havent try to change the "{attr}: " for safety

**Comment by durson54** [comment]
Ok, thanks mate for the help :) It works now, the problem was in attributes,yml, idk what but I deleted it and restarted skillapi and it's working :D

**Comment by Eniripsa96** [comment]
It seems like the issue was fixed, so I'll close the issue. Feel free to re-open if there's still something left.
