### ISSUE TITLE
No Attributes.yml

### ISSUE THREAD

**Issue by YukiNerdCubed** [Eniripsa96/SkillAPI#223]
I downloaded SkillAPI v3.103.
I started up my server and I expected a attributes.yml file to appear but only these 4 appeared.
https://gyazo.com/d6c4f24f5c29bc4265f352a96a9e723e

**Comment by durson54** [comment]
Just create a attributes.yml file and copy it from Default Configs in Wiki here.

**Comment by AngDrew** [comment]
Lol you should enable it on config before it appears :3

**Comment by AngDrew** [comment]
Seriously guys
At least you should to read the config before use a plugin
Then you must read their wiki(if available)

**Comment by durson54** [comment]
:D Oh I forgout about It sorry, I haven't looked in config for a long time.. :D

**Comment by YukiNerdCubed** [comment]
Thanks for the help, sorry that I didnt read the config.

**Comment by AngDrew** [comment]
Nice

**Comment by Eniripsa96** [comment]
Closing since the issue seems to be resolved (Thanks AngDrew). Feel free to re-open if you're still having issues.
