### ISSUE TITLE
Half of the skills are not available

### ISSUE THREAD

**Issue by aaTking** [Eniripsa96/SkillAPI#224]
Using premium
Half of the skills are not available from free versions
----------------
What should I do

**Comment by Zicerite** [comment]
You have to add them back in, using /class customize
And make sure your config.yml is how you want it, as upgrading to premium changes things in the config.

**Comment by aaTking** [comment]
Sorry, my English is not good
I mean, after upgrading to premium

The free version of [Target] is fundamentally different from premium
It makes the previous free version of the spell work on premium

**Comment by aaTking** [comment]
examples:
![image](https://user-images.githubusercontent.com/34217827/33863448-b9525bda-df22-11e7-936a-f2399deb9ac5.png)

**Comment by Zicerite** [comment]
Ah, okay I see. 
Instead of the commands, try using the Item mechanic in the editor.

**Comment by aaTking** [comment]
examples2:
![image](https://user-images.githubusercontent.com/34217827/33863926-26e09976-df25-11e7-8c37-7d61f46376f3.png)

**Comment by aaTking** [comment]
So you should buy me a hamburger.  
![image](https://user-images.githubusercontent.com/34217827/33865554-3290b9c4-df2d-11e7-8277-84fcd9dcadc7.png)

**Comment by Zicerite** [comment]
Have the flag check come before damage, so that it can register correctly.

**Comment by aaTking** [comment]
Or I'll give you a doughnut
Fix it at the next update

**Comment by Zicerite** [comment]
I'm not a dev, just someone who uses this plugin a lot
The dev is inactive currently

**Comment by aaTking** [comment]
Oh, I see. Then I have to wait

**Comment by Eniripsa96** [comment]
Premium splits up "{player}" into "{player}" being the caster and "{target}" being who you're targeting. If you use "{target}" for the one giving the item to the target, it should work.
