### ISSUE TITLE
Premium Question: Force Skill Improvement?

### ISSUE THREAD

**Issue by WeasomeKarma** [Eniripsa96/SkillAPI#226]
Hey amazing plugin,

Is there a way to force players into professing into a skill? For example, if someone picks the race "human" how can i make them automatically have a point in "will save"?

Thanks!

**Comment by AngDrew** [comment]
The dev is currently inactive

Maybe i can help you
But i dont understand with your post..
Im confused (i have read it more than 5 times :/  )

Please describe it clearly

**Comment by WeasomeKarma** [comment]
Thank you, and will do

So I have a skill named "Will Save", its cost to upgrade is 0 at level 1, and this skill is for the class "Human". When a player professes into Human this skill is at 0/3 (No skill points in it). A player can simply choose never to put a point into it, and I want to prevent that. How can I have skills automatically have points in them when a player professes into the class? I notice that when the skill is at 0 skill point cost it will do this automatically, but its very hit or miss.

I can send pictures if you're still confused :)

**Comment by AngDrew** [comment]
If you want to do it..
You can set the cost to 0 so it will automatically make the player have the skill
And you can make a level requirement for feel of growing
Note: the skill wont show in skill gui (changeable in config you can read and scrolling through it)

**Comment by WeasomeKarma** [comment]
Alright thank you

**Comment by AngDrew** [comment]
Is it solved?
If it solved please close the issue
