### ISSUE TITLE
Targets don't work corectly

### ISSUE THREAD

**Issue by sirjavlux** [Eniripsa96/SkillAPI#228]
i have set up a skill that i want to target area  and i have turned include caster to false but still the area targetting includes me and the targets

**Comment by Eniripsa96** [comment]
I'm guessing you're using "Ally" or "Both" for the group, in which case, I can see why that would happen. Will change up the logic to make it more intuitive.

**Comment by Eniripsa96** [comment]
Changed the logic in 1.66
