### ISSUE TITLE
Fry day炸天！

### ISSUE THREAD

**Issue by aaTking** [Eniripsa96/SkillAPI#233]
SkillAPI v3.103 Total: 5.277 s	Pct: 11.01%
   Pct Total	Pct Tick	   Total	      Avg	 PerTick	     Count		Event
       8.14%	7,807.21%	  3.90 s	 3,903.60 ms	 0.0	       0.0k	    Task: SaveTask(interval 6000)

**Comment by Eniripsa96** [comment]
See #235
