### ISSUE TITLE
[Question Premium]How use particle effect on multiple target?

### ISSUE THREAD

**Issue by Tiplish** [Eniripsa96/SkillAPI#234]
Hi,

I try to use "particle effect" premium mecanic but it only works on one target at the same time. There is a way to apply the particle effect on every target that i have?

Thanks :)

**Comment by AngDrew** [comment]
I think it works like particle effect..
Just put the particle inside target and it should be work fine

I havent test any premium feature because i dont have it lol

**Comment by Tiplish** [comment]
Ok because i have test with free particle, it works for any target but if you look at the premium particles, there is a "key". I don't how to haven't any key and so, could apply particle effect on every target :(

**Comment by Eniripsa96** [comment]
The "keys" used for particle effects are used per target. The only thing the key limits is playing multiple effects with the same key on the same target.

You should be able to use "Particle Effect" on multiple targets normally.
