### ISSUE TITLE
help!!

### ISSUE THREAD

**Issue by aaTking** [Eniripsa96/SkillAPI#235]
![image](https://user-images.githubusercontent.com/34217827/35324500-d995f2f0-012b-11e8-8b18-a5c819a85a18.png)

**Comment by Eniripsa96** [comment]
Saving requires disk writes which are an expensive operation. The task happens infrequently, however, so it should not normally be a problem. I can investigate turning it into an asynchronous task in order to avoid impacting the main thread, however.
