### ISSUE TITLE
Hello, i need help. Im trying to make an Archer class but the skills are casted inmediatly and not when you fire the arrow, what could i do?

### ISSUE THREAD

**Issue by Zeuscp1** [Eniripsa96/SkillAPI#236]

**Comment by Devillion** [comment]
I have a discord for getting help with skillapi, come ask your question there - we have 60+ members and most are very active.

https://discord.gg/UwJMXGv

**Comment by Eniripsa96** [comment]
"Initialize" trigger will happen immediately. To trigger when firing an arrow, use the "Launch" trigger. To trigger when an arrow hits something, use the "Physical Damage" trigger.
