### ISSUE TITLE
/class exp Can not work with two groups

### ISSUE THREAD

**Issue by SnUncle** [Eniripsa96/SkillAPI#238]
I got two group "race" and "class" but when i type /class exp <myname> 100 race . nothing happend

**Comment by Devillion** [comment]
Your using the command wrong, it's: /class exp [player] <amount>

I have a discord community for getting help with skillapi, come check it out: https://discord.gg/UwJMXGv

**Comment by Eniripsa96** [comment]
Found the bug where it required a player to be defined in order to use a group. Will fix it so your usage works.

**Comment by Eniripsa96** [comment]
Fixed in 1.67
