### ISSUE TITLE
Permission Basic

### ISSUE THREAD

**Issue by WeasomeKarma** [Eniripsa96/SkillAPI#244]
Is it possible to have commands like ./class cast <skill> not use the permission "skillapi.basic"? I went into the config for commands.yml and tried to set the permission to "skillapi.cast" but it still uses "skillapi.basic". 

I'm trying to do this to set up a method for silencing abilities, so if there is another way I can simulate this without using perms that will resolve my issue too.

**Comment by Eniripsa96** [comment]
Make sure you reload the server after changing the option.

There also is the "Silence" status ("Status" mechanic with the silence option) which is built for exactly that.

**Comment by WeasomeKarma** [comment]
Oh the more you know, thank you very much!
