### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by Bensz6216** [Eniripsa96/SkillAPI#245]
How can I setup this GUI for myself?(above the action bar)
http://youtu.be/kPplX477qEo

**Comment by Zicerite** [comment]
If you mean the bar with the Hp and Mana, etc display above the inventory, that is done in the config.yml. in skillapi. Available both in free and premium version.
The hearts and mana star are from a custom resource pack however...

Ps. Interesting to see my video used as an example for a question.

**Comment by Eniripsa96** [comment]
Adding specifics here:

In "config.yml", use the "action-bar-text" option to format that GUI. Values you can add there are documented in config.yml. Also make sure "use-action-bar" is set to "true" for it to work.
