### ISSUE TITLE
the /class exp and /class level commands do not work

### ISSUE THREAD

**Issue by silverforte** [Eniripsa96/SkillAPI#250]
Using the latest free version, worldguard and only parties and Mccore.  Using the commands results in the correct string of text in the chat saying the player was granted X levels or experience, but the display on the right does not reflect this, nor does /class info.

**Comment by silverforte** [comment]
Nevermind, my stupidity. Had commands disabled as an xp source.

**Comment by Zicerite** [comment]
Then if there is no other issue, you should close this
