### ISSUE TITLE
Dynamic Editor Duplicate Issues

### ISSUE THREAD

**Issue by co221133** [Eniripsa96/SkillAPI#251]
Hey guys, just a couple issues I've noticed when duplicating mechanics on the dynamic editor:
- Counts as Cast is reset to "True," even if the duplicate target has Counts as Cast set to "False."
- The message at the top of the screen describing what the current mechanic does disappears when editing a duplicated mechanic/condition/target.

This just amounts to me having to go through each duplicated option to set the "Cast" to the proper value; not game-breaking, but it does eat up time.

**Comment by Zicerite** [comment]
Dev is inactive, and this is a known issue in the community.

**Comment by co221133** [comment]
Ah, that's too bad. This is an excellent plugin, simple quality of life fixes like that would go a long way.
Thanks for the response anyway!

**Comment by Eniripsa96** [comment]
Fixed
