### ISSUE TITLE
Custom atributes no work [SkillApi Premium]

### ISSUE THREAD

**Issue by drAkeTool** [Eniripsa96/SkillAPI#252]
Hello friends
I would like to report to bug
custom attributes do not appear in the gui
I leave the image so you can see it

https://i.gyazo.com/4ff7c35db3aa205a236e48194b92b052.png

Atribbutes.yml
https://pastebin.com/tqaTu1yN

it seems that if you change the name of the default attributes
fails to detect them and do not appear in the gui for example "discipline or strenght2"

**Comment by Devillion** [comment]
The dev of this plugin hasn't been active in a while, however we started a discord community for this plugin and some others here if you would like to join and maybe get some help: https://discord.gg/UwJMXGv

**Comment by Eniripsa96** [comment]
Options to fix:
1) Delete "gui.yml" and reload the plugin/server
2) Use "/class customize" to change the menu

Closing since this is an old request. Feel free to re-open if the above does not work and the help is still needed.
