### ISSUE TITLE
Class bar Error

### ISSUE THREAD

**Issue by B4TT3RY** [Eniripsa96/SkillAPI#254]
Version: PaperSpigot 1.12.2 (Build 1342)

When "/class acc [number]" use, hotbar's item isn't in inventory.
not full inventory, i'm using SkillApi Premium.

sorry for my bad english.

**Comment by Zicerite** [comment]
There is no support for Paper

**Comment by B4TT3RY** [comment]
So I'll test it out at Spigot.
