### ISSUE TITLE
 Invalid mechanic component: value distance

### ISSUE THREAD

**Issue by EnderGriefeur99** [Eniripsa96/SkillAPI#257]
This is normal ? Invalid mechanic component: value distance

**Comment by Eniripsa96** [comment]
Hmm, looks like I have it coded but not registered. Will fix.

**Comment by EnderGriefeur99** [comment]
and antoher problem with this                                                                                                                                                                                                                                                    {req:level}Level: {attr:level}
{req:cost}Cost: {attr:cost}
the  {attr:level} display 0
and the {attr:cost} diplay 0
then {attr:cost} is 5
and the  {attr:level} is 2

**Comment by Eniripsa96** [comment]
Value distance is fixed.

I'm not sure what you mean by the issue with the filters, it's 0 then 5? What do you mean? How is it both? Do you have your base values as 0?

Taunt was also fixed when MythicMobs is present on the server. Note that it doesn't work on older servers due to a Spigot/Bukkit bug.

**Comment by EnderGriefeur99** [comment]
{attr:level} display 0 and the {attr:cost} diplay 0 then {attr:cost} is 5 and the {attr:level} is 2

**Comment by Eniripsa96** [comment]
What is the "then" for changing from 0/0 to 5/2?

If you're on 1.11.2, it should be fixed with the latest version then.

**Comment by EnderGriefeur99** [comment]
then because the spells display 0 then they set to another number
