### ISSUE TITLE
Physical-Damage Split

### ISSUE THREAD

**Issue by SirMittens** [Eniripsa96/SkillAPI#259]
Hey, I was wondering if it is possible to split arrow Projectile damage from the strength attribute to another attribute as I am trying to make an archer and a warrior class

Thanks

**Comment by Eniripsa96** [comment]
Currently, there's no split. Closest thing would be to override firing arrows with a skill (Launch trigger, cancel mechanic, projectile mechanic, damage mechanic) and use attributes to decide the damage from there.

I can keep the concept in mind thought and probably add an option to specifically raise melee vs projectile damage.

**Comment by Louis-BloodRose** [comment]
Launch > Condition Item Bow > Damage Buff (Icon Key: DEX_DMG_BUFF)(Create attr with this key).

Thats how i handle arrows. :)

**Comment by Eniripsa96** [comment]
Added in 1.87
