### ISSUE TITLE
SkillAPI isn't working...

### ISSUE THREAD

**Issue by KookaiPLZ** [Eniripsa96/SkillAPI#260]
My problem is as follows:
I installed SkillAPI, did the first skill, deleted it after a while - and of course I also reset class and skills - but it did not work anymore! I was able to restart, stop, reload, anything but nothing! It remained empty (Class Profess) .. I really need help within 2 months ..
Thanks, someone should help!

**Comment by Eniripsa96** [comment]
Is the console showing anything as loaded? Did you try using "/class options" to view available classes?

**Comment by Eniripsa96** [comment]
Closing due to age of the request. Feel free to open if you still need the help, just provide the above information.
