### ISSUE TITLE
[PREMIUM] icon-data changing values after reload/restart

### ISSUE THREAD

**Issue by TerraPrimal** [Eniripsa96/SkillAPI#262]
This is a bit of a weird one.

I have all my skills using SHEARS as the material and each skill using a different icon-data: to display a different icon for each skill.
This works until a restart or reload of the software, then its set to a random -value like -50 which breaks the display.

I have added a video below showing the example.
https://www.youtube.com/watch?v=yolciiPUcrY&feature=youtu.be

Here's hoping it can be fixed if Eniripsa96 ever returns <3

**Comment by Eniripsa96** [comment]
Stange, will investigate to see if it's pulling the wrong values when updating the config or something.

**Comment by TerraPrimal** [comment]
Thanks, let me know if you need anymore info (configs, etc)

**Comment by Eniripsa96** [comment]
Looks like it loaded the value into durability but saved it as the material data value. Woops. Will be fixed in the next version.

**Comment by Eniripsa96** [comment]
Fixed in 1.69
