### ISSUE TITLE
Skill bar gamebreaking bug

### ISSUE THREAD

**Issue by Vyrgax** [Eniripsa96/SkillAPI#263]
When you do the following, you can duplicate any icon/seed from the skill bar:
Gamemode 0, with the 9 main slots empty except the skill bar
Then open inventory, hover above (for example) the first ability in slot 1, and press 9 on keyboard
Then it is copied. (9th slot must be no skill bar though)

This is very annoying for survival servers which have this plugin, I had to close the server down for maintenance and I have no idea how long it should be.

I understand Eniripsa is trying to get out of Gold, but it sucks to see this great plugin suffer from this glitch.

**Comment by Eniripsa96** [comment]
Which server are you running? Which version of the plugin are you using? Free? Premium? Which casting option are you using? Regular skill bars? Combat bars?

**Comment by Eniripsa96** [comment]
I'm unable to replicate the issue, so I'll close this issue. Feel free to re-open if you're still having the issue, but provide the information requested above.
