### ISSUE TITLE
SkillApi NoClassDefFoundError

### ISSUE THREAD

**Issue by magemaster808** [Eniripsa96/SkillAPI#265]
![image](https://user-images.githubusercontent.com/30489073/41041867-d82acc64-69d2-11e8-95e3-1d768717c6bf.png)

I get this error when skillapi tries to enable. Any idea how to fix this?

**Comment by Eniripsa96** [comment]
Make sure you have MCCore https://dev.bukkit.org/projects/mccore/files/2465208

**Comment by magemaster808** [comment]
I realized I used a different MCCore. The one posted in the spigot forums is apparently not identical to this one. Thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Eniripsa96** [comment]
Seems like someone decided to use the same name as me 4 years later

**Comment by magemaster808** [comment]
Thanks for the help

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
