### ISSUE TITLE
Target: Location - NoSuchMethodError

### ISSUE THREAD

**Issue by keahie** [Eniripsa96/SkillAPI#267]
I want to use a Location as a Target but every time when I cast the skill I get this error message:

![screen](https://user-images.githubusercontent.com/5269347/41401303-c96bccd0-6fbf-11e8-9ea3-a9de8f0824bf.PNG)

Pls fix this

**Comment by Eniripsa96** [comment]
Which server are you running? (type and version)

**Comment by keahie** [comment]
I managed it to work again. I just deleted the plugin, downloaded it again and now it works. I have no idea why this bug was at my machine, but I'm glad that it works now.
The server is running on Spigot 1.12.2

**Comment by Eniripsa96** [comment]
Odd, but glad it's working now
