### ISSUE TITLE
[PREMIUM FEATURE] Mechanic Value PlaceholderAPI.

### ISSUE THREAD

**Issue by TerraPrimal** [Eniripsa96/SkillAPI#268]
Greetings @Eniripsa96,

Now you're back, I thought it might be an ok time to suggest a new Mechanic that I'd love to see. (I'd given up hope it would be added due to your break, and there was no method I could find for adding our own Mechanics via the API)

This would be a Value Mechanic much like the Value Lore Mechanic, however this would get it's data from the placeholder API you put there.
There would be three options, String, Int or Double and you would be able to use these values in other Mechanics much like the Value Lore Mechanic.

I've added two (basic) examples below on how this could work.
-

![Screenshot](https://i.gyazo.com/9d7899bb4608bd215f2bd39b317b9f9b.png)
This would grab the current health, then you could use it for say a damage Mechanic and have damage based on how much HP you have, or ping, w/e grabs you fancy.

![Screenshot](https://i.gyazo.com/3549f0aac482a407056695388b9ef8c2.png)
This would grab the casters rank, you could add it to a message Mechanic.

**Comment by Eniripsa96** [comment]
Very thorough, will look into adding this

**Comment by Eniripsa96** [comment]
Added in 1.67
