### ISSUE TITLE
Suggestion: New Attributes in 1.9

### ISSUE THREAD

**Issue by Devillion** [Eniripsa96/SkillAPI#27]
**New options for the online editor** (made available in MC 1.9)
- Attack Speed Attribute
- Armor Attribute
- Luck Attribute
- ArmorToughness Attribute

info found here at the bottom under history: http://minecraft.gamepedia.com/Attribute

**Factions Hook**
Set Faction Allies and own Faction as "ally" and anyone else would be set as "enemy". This would allow for more options when creating skills, so that we can target enemy and allies easier. (besides just mobs)

**Comment by Eniripsa96** [comment]
Added (finally) in premium 1.52
