### ISSUE TITLE
Particle Projectile applying child multiple times

### ISSUE THREAD

**Issue by Zicerite** [Eniripsa96/SkillAPI#270]
Particle projectile applies child mechanics multiple times. This can be seen with all mechanics, including damage, value add, etc.

Strangely enough, this doesn't happen if you have it set to pierce. Or at least, from what I've tested myself.

Spigot Version: Various (I have heard from versions 1.10, 1.11, and 1.12, more so 1.12 from what I've heard)
Skillapi Version: Premium 1.65/1.66

To Reproduce: Create a skill that shoots out a particle projectile (Spread: Cone) onto an enemy mob. Set a Value from Value Add, and have it display in chat via Message.

It seems a bit random from how many times the child components are triggered, sometimes twice, sometime much higher.

![2018-06-16_10 32 42](https://user-images.githubusercontent.com/30883277/41501011-22b1960c-7151-11e8-8ce2-c8b7b6162e5f.png)

**Comment by Eniripsa96** [comment]
Pierce has specific checks to avoid hitting the same target more than once, so some events must be finding multiple collisions, and without that logic it just spams effects. Will investigate the issue.

**Comment by Eniripsa96** [comment]
Should be fixed in 1.67
