### ISSUE TITLE
Skillapi editor 

### ISSUE THREAD

**Issue by EnderGriefeur99** [Eniripsa96/SkillAPI#271]
Problem the editor is empty 
<a href="https://imgur.com/XD8OnLS"><img src="https://i.imgur.com/XD8OnLS.png" title="source: imgur.com" /></a>

**Comment by miglas** [comment]
me too

**Comment by Zicerite** [comment]
It seems to be down for everyone. @Eniripsa96 will need to tell us when it will be fixed.

**Comment by Eniripsa96** [comment]
Should be fixed, sorry for the downtime
