### ISSUE TITLE
Class Advancement Lore-Checking weapons thingy broken

### ISSUE THREAD

**Issue by Zicerite** [Eniripsa96/SkillAPI#272]
Only appears in the premium version. Tested with 1.11/1.12.x

The class advancement thingy for Lore-Checking weapons is broken.
Like if "Fighter" advanced to "Brawler", any weapons labeled as "Fighter" as a class requirement won't work for brawlers. This isn't broken in the free version, but is broken in premium.

**Comment by Eniripsa96** [comment]
Fixed in 1.68
