### ISSUE TITLE
Category Defense not working

### ISSUE THREAD

**Issue by Zicerite** [Eniripsa96/SkillAPI#273]
Tested: Skillapi 1.65+
Versions: Confirmed with 1.12.2

Premium version has a feature to allow for category damage and defense. Damage works fine, but category defense doesn't.
I know the configuration is "skill-defense-<classification>", but no matter which formula i use, or if lowercase or uppercase, this doesn't seem to work.
I have confirmed with others in the community that skill defense classification doesn't work with anyone.

To reproduce, simply make yourself an item with, say "WaterDEF: 100" that increases your water defense by 100%. Get hit by a water damaging skill. Damage taken doesn't get decreased.

**Comment by Eniripsa96** [comment]
Fixed in 1.68
