### ISSUE TITLE
[Feature Request] Level up message

### ISSUE THREAD

**Issue by Lix3nn53** [Eniripsa96/SkillAPI#274]
A message that shows stats gained from leveling up
Like this:

Level up! You are now level (new level) (class)
max hp +5
max mana +5
(attribute1) +2
(attribute2) +3

**Comment by Zicerite** [comment]
That would be neat actually. I would think it would read off from the class.yml of each increase.

**Comment by Eniripsa96** [comment]
There is the "level-up-skill" option which links leveling up to a skill you make, allowing you to use any mechanics available to skills for leveling up, including messages, particles, other commands, etc.

That should cover what you're looking for and more.
