### ISSUE TITLE
Tool.yml Icons appear in customize but not on actual menu. BUG

### ISSUE THREAD

**Issue by Louis-BloodRose** [Eniripsa96/SkillAPI#275]
When you add an icon at tool.yml, it appears on the Customize menu but not when you open the actual menu where you put it.

How to reproduce:

1: Add any item to tool.yml
2: Open class customize and add the item.
3: Open the menu you added the item, TADA its not there.

**Comment by Eniripsa96** [comment]
Fixed in 1.68
