### ISSUE TITLE
[Suggestion] Disable click combos in spectator mode

### ISSUE THREAD

**Issue by Zicerite** [Eniripsa96/SkillAPI#276]
Lets say if a server owner wanted to use spectator mode for spectating pvp arenas or similar. Spectator mode is still able to use click combos and possibly interfere with the match. 
Would it be possible to disable click combos if a player is in spectator mode?

**Comment by Tiplish** [comment]
Or maybe a command to disable the Skillapi interface? 

Some players have the display and have to switch between player mod and "admin mod" where they don't use classes. It could be usefull in this case.

**Comment by Zicerite** [comment]
Maybe both an automatic and a command option then, just so that servers have options.

**Comment by Tiplish** [comment]
Yeah. For the moment, players on our server use /class acc 2 (because they can't have more than one account with classes) to suppress combo/GUI of Skillapi but it's not very clean :s

**Comment by Zicerite** [comment]
Wait, why did this close?
Is it added in your most recent version?

**Comment by Zicerite** [comment]
Oh silly me, lol nvm

**Comment by Eniripsa96** [comment]
This was added awhile ago, I just forgot to update the status of this issue.
