### ISSUE TITLE
[Suggestion] Add more durability to stuff

### ISSUE THREAD

**Issue by Tiplish** [Eniripsa96/SkillAPI#277]
Hi,

On my server, i would add more damage to physical attack and spells. It will damage the armor and so, break stuff faster (i won't make unbreakable stuff so it's not a solution :p). 

I wanna know if it's possible to add a lore, which will replace the native durability? Or something like this?

The goal is, when a player up his level, he could up his damage a lot. So the native durability of Minecraft is not enough to manage the stuff breaking... One attack, one break stuff :p

Any clue?

**Comment by Eniripsa96** [comment]
MCCore (dependency of SkillAPI) actually has settings for durability. "durability-enabled" in config.yml, when set to true, makes MCCore use hidden text you can add to items to have increased durability. It's a fairly experimental feature that I haven't heard of anyone using yet, but you could try it out and make suggestions from there.

How you would use it is if you already have custom items, add something like the following to the end of the name:

§y§5§0§0§0§z§5§0§0§0

And that would be for 5,000 durability. Basically §y starts the max durability, §z starts the current durability, and each digit is prefixed with § as well so it is all invisible.

**Comment by Tiplish** [comment]
Thx i will try it asap :D

**Comment by Tiplish** [comment]
It works :D thx for the tips o/
