### ISSUE TITLE
[Question] How to determinate the behaviour of particles?

### ISSUE THREAD

**Issue by Tiplish** [Eniripsa96/SkillAPI#278]
When i've try to make custom visual effects with particles, it was hard to know what combo of data/particles will make what i want in game. I've try many tests to found what i would as visual effect.

Have you a documentation to see what change of "Particle Speed" or "Packet amount" will change as visual effect? Maybe i've miss it somewhere :s

**Comment by Eniripsa96** [comment]
I don't have documentation myself, but these are common values for anything using particles. Speed usually changes how fast a particle travels. Packet Amount is mostly used for colored particles like redstone dust, where 0 lets you choose the color by specifying the X Y Z values. Packed Amount greater than 0 would randomize it.

You can probably search around and find more detailed answers. I'm unfotunately not an expert in this area, so I don't know many details myself outside of the above.

**Comment by Tiplish** [comment]
Ok thx :)
