### ISSUE TITLE
[Suggestion]Critical hit

### ISSUE THREAD

**Issue by Tiplish** [Eniripsa96/SkillAPI#279]
There is a possibility to add as condition for physical damage the "critical hit" condition? I don't know if you could catch it :s

**Comment by Eniripsa96** [comment]
I don't know of a way (a sane way at least) to determine whether or not an attack was a crit. This might just be a limitation of Spigot/Bukkit.

**Comment by Zicerite** [comment]
So you labeled it as an enhancement, then closed it imminently? 
Intentional?

**Comment by Eniripsa96** [comment]
Initially noted it as an enhancement since that was the nature of the request, then did some initial investigation and found out that there was no clear way to find whether or not an attack was crit, so I added the  comment above and closed it.
