### ISSUE TITLE
Annoyance/Bug - Selecting a skill casts it

### ISSUE THREAD

**Issue by Catreina** [Eniripsa96/SkillAPI#28]
When using mouse scrolling, if you scroll onto a skill in the hotbar, with the hotbar enabled, it will attempt to cast the skill before automatically deselecting. If you have a high cooldown skill in that position, it will trigger and automatically put it on cooldown.

This is a huge annoyance. May be an oversight/bug.

**Comment by Eniripsa96** [comment]
This has been known, but there isn't a way (at least that I'm aware of) to differentiate between scrolling and number keys in terms of changing the held item slot. Due to this, no action can be taken.
