### ISSUE TITLE
[Question]Is it possible to detect if the weapon is fully recharge?

### ISSUE THREAD

**Issue by Tiplish** [Eniripsa96/SkillAPI#281]
It's me again :o

I would know if is it possible to detect when a weapon (in minecraft 1.12) is fully recharge. For example, you have a weapon very slow (a woodstaff? o/) and you would trigger the maximum power to launch a spell. Is it possible to trigger it with skillapi?

Thanks :)

**Comment by Eniripsa96** [comment]
Not within the Spigot/Bukkit API at least. There's probably some hidden field in NMS players, but probably not something I would add. What you could do instead is use the Physical Damage trigger and set a flag for the time it takes for the staff to recharge. In other triggers or eve skills, you can then use that flag to check whether or not the staff would be fully charged.
