### ISSUE TITLE
Disable messages

### ISSUE THREAD

**Issue by Lix3nn53** [Eniripsa96/SkillAPI#285]
Dont send message if its empty ('') in language.yml
Or any other way to disable them?

**Comment by Eniripsa96** [comment]
Which messages? Some have explicit disable options, others should not send when empty. Let me know of any I missed.

**Comment by Lix3nn53** [comment]
Errors.on-cooldown and Errors.no-mana sends empty message ("")

**Comment by Eniripsa96** [comment]
Should be fixed in most recent MCCore
