### ISSUE TITLE
API Bonus attributes problem

### ISSUE THREAD

**Issue by Lix3nn53** [Eniripsa96/SkillAPI#290]
Need new method
SkillAPI.getPlayerData(p).getBonusAttribute("attrName"); 
and
SkillAPI.getPlayerData(p).clearBonusAttribute("attrName"); which clears bonuses of only one attr

This is really important for me because I made a inventory plugin that has passive slots. When you equip passive items (rings, parrots etc) you get attr bonuses. I am having problems because of this update and this 2 method can fix that. 

1.70
- Changed how attribute bonuses from skills/items work
bonuses can be negative
will not drop total attribute amount below 0

**Comment by Lix3nn53** [comment]
Sorry I just found this: 
`public static int getBonusAttr(Player p, String attr){
		PlayerData sdata = SkillAPI.getPlayerData(p);
		int bonus = 0;
		int invested = 0;
		int total = 0;
		if(attr.equals("end")){
			invested = sdata.getInvestedAttribute("earth");
			total = sdata.getAttribute("earth");
		}else if(attr.equals("str")){
			invested = sdata.getInvestedAttribute("fire");
			total = sdata.getAttribute("fire");
		}else if(attr.equals("dex")){
			invested = sdata.getInvestedAttribute("water");
			total = sdata.getAttribute("water");
		}else if(attr.equals("spr")){
			invested = sdata.getInvestedAttribute("air");
			total = sdata.getAttribute("air");
		}else if(attr.equals("int")){
			invested = sdata.getInvestedAttribute("lightning");
			total = sdata.getAttribute("lightning");
		}else if(attr.equals("offhand")){
			invested = sdata.getInvestedAttribute("offhand");
			total = sdata.getAttribute("offhand");
		}else{
			invested = sdata.getInvestedAttribute(attr);
			total = sdata.getAttribute(attr);
		}
		bonus = total - invested;
		return bonus;
	}`

But still, that two methods can make it easier for me :D

**Comment by Eniripsa96** [comment]
Ideally, your code should track how much you personally added and refund that exact amount afterwards. If the value comes from an item or something, that can be the "tracking". Unequiping it, for instance, would have you subtract it's bonus instead of adding it. 

With that in mind, you probably shouldn't know about the total bonus value nor be able to reset it entirely, so I don't think I'd add these functions.

**Comment by Lix3nn53** [comment]
Yes, I am able to track bonuses added by me. You are right I didnt know that total bonus values are from item lores etc.
Thanks for the explanation!
