### ISSUE TITLE
Some bugs about the database

### ISSUE THREAD

**Issue by df20** [Eniripsa96/SkillAPI#291]
I'm using MySQL, Spigot
When I use command /class backup, it shows "SQL database backup failed - backed up 0 entries."

When I use command /class reload, after a long time of loading, 
The max.health and mana will be changed to a low value(some time is 5, some time is 4). 
The skills in hotbar will become ghost items(which can hold in hand, and cannot cast skill)
When you hold the ghost items, the problem of max.health and mana will be fixed.
Also, you can't use the skillbar again.
You can reconnect the server to fix all these problems

The message that appear in console when use the command /class reload is
21.06 12:27:58 [Server] WARN at com.sucy.skill.thread.MainThread.run(MainThread.java:66)
21.06 12:27:58 [Server] WARN at com.sucy.skill.thread.RepeatThreadTask.tick(RepeatThreadTask.java:62)
21.06 12:27:58 [Server] WARN at com.sucy.skill.task.GUITask.run(GUITask.java:122)
21.06 12:27:58 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.setExp(CraftPlayer.java:821)
21.06 12:27:58 [Server] WARN at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191)
21.06 12:27:58 [Server] WARN java.lang.IllegalArgumentException: Experience progress must be between 0.0 and 1.0 (8.57475)

**Comment by Eniripsa96** [comment]
SQL issues fixed in 1.72
