### ISSUE TITLE
Attribute Icons not "Unbreakable", causing durability bar to show

### ISSUE THREAD

**Issue by Zicerite** [Eniripsa96/SkillAPI#292]
Using 1.12.2 spigot, 1.71 premium

Attribute item icons are not "unbreakable", and show their durability and their durability bar.
This seems a bit inconsistent, since skill icons **are** "unbreakable", and don't show a durability bar nor their durability, like how it should be.

This is important, for servers, like mine, which are using custom textured items for icons.

Attribute Icon using a custom textured item with a damage value:
![2018-06-21_02 01 46](https://user-images.githubusercontent.com/30883277/41709108-3bf40326-74f7-11e8-8a0e-b89e2b3dbba3.png)

Skill Icon using a custom textured item with a damage value: (This recolored magma cream is a retextured pickaxe)
![2018-06-21_02 02 02](https://user-images.githubusercontent.com/30883277/41709206-7cdc9e84-74f7-11e8-8d4c-4aecb31c2371.png)

**Comment by Zicerite** [comment]
I'm not talking about the text that shows minecraft:golden_pickaxe, etc. That's just a vanilla thing i always forget to turn off when im on my server.

**Comment by Eniripsa96** [comment]
Fixed in 1.73
