### ISSUE TITLE
[Feature Request] Mechanic: Cast Skill

### ISSUE THREAD

**Issue by Zicerite** [Eniripsa96/SkillAPI#294]
I feel like this would be neat to have, and it would keep single files smaller, and easier to edit. 
Like you'd put in the conditions for something for a skill, and you just put in a single mechanic to cast the skill in a separate file. 

This would allow users like myself to make very complex, condition heavy skills, without it being a huge mess in a single skill, due to how much stuff you'd put into it.

It would have a few fields:

Icon-key (of course)
Skill name
Skill level + ()

**Comment by Zicerite** [comment]
https://www.youtube.com/watch?v=mcOFqLXynF8
This is mainly why im requesting this feature...

**Comment by Eniripsa96** [comment]
You can already do this with the command mechanic. Have an initial Value Set mechanic with 1 + ( 1 ) and let's say the key is "skillLevel". To trigger a skill, just run the command:
"/class forcecast {player} otherSkillName {skillLevel}"

**Comment by Zicerite** [comment]
Well Im stupid lol. I didn't even think about that...
Thanks
