### ISSUE TITLE
Another skill bar problem :/

### ISSUE THREAD

**Issue by Lix3nn53** [Eniripsa96/SkillAPI#295]
I get stacks of empty skill slot item after plugin reload

![untitled](https://user-images.githubusercontent.com/40330870/41786681-dc0c1f30-764e-11e8-8e75-52d044c1849a.png)

**Comment by Zicerite** [comment]
I just got that too, though idk what is causing it.
Got an error though while it was happening.
[Error Log.txt](https://github.com/Eniripsa96/SkillAPI/files/2129319/Error.Log.txt)

**Comment by TerraPrimal** [comment]
Having it my end as well. All I wanted to do was reload a darn skill :D
https://pastebin.com/8gJLfJHF

**Comment by Eniripsa96** [comment]
Fixed in 1.73
