### ISSUE TITLE
[Bug] Old class doesn't work with new version of skillapi

### ISSUE THREAD

**Issue by Tiplish** [Eniripsa96/SkillAPI#297]
Hi, i've try to get the last version of skillapi Premium, but when i try to switch on the classes, they don't work anymore... i've try to generate classes and spells with the new dynamic editor but it doesn't work more :s any clue?

**Comment by Eniripsa96** [comment]
Not sure, I haven't changed profession recently, but will do some digging to see what's going on.

**Comment by Eniripsa96** [comment]
Fixed in 1.74

**Comment by Tiplish** [comment]
Fast reaction o/ thx
