### ISSUE TITLE
Request: Unbreakable Option for Icons

### ISSUE THREAD

**Issue by RacerN2O** [Eniripsa96/SkillAPI#300]
I'd like to see an option to have the items which are displayed as icons be unbreakable. There's a trick with resource packs involving model data which allows the game to show different textures depending on damage (ie. data) values on unbreakable tools.

So if there was an option to have the icons show unbreakable items with data values, we could use completely custom icons for our skills using resource packs! :)

**Comment by Zicerite** [comment]
Um, you can already do that. It is what im doing with some of my skills, and all of my attribute icons.

**Comment by RacerN2O** [comment]
Oh, are the icon items unbreakable already? I wouldn't want to change breakable items in my resource pack. I didn't test it, that's true.

**Comment by RacerN2O** [comment]
Oh yes it works. Seems like this is a newer feature I missed. Thanks!

**Comment by Zicerite** [comment]
Its actually a very old feature, but yeah
Good luck on your server lol.
