### ISSUE TITLE
Multiplier based Buffs are not working!

### ISSUE THREAD

**Issue by RacerN2O** [Eniripsa96/SkillAPI#303]
I've run into issues with new **and old** skills and it seems like (at least multiplier based) Buff mechanics aren't working. This is a pretty big deal and I hope it'll get fixed ASAP as it broke a lot of thing and possibilities.

**Comment by Zicerite** [comment]
You have to specify which version of skillapi (free/premium with version number) as well as spigot version when you are reporting issues.

**Comment by RacerN2O** [comment]
I've been running into these problems with SkillAPI Premium 1.74 (and 1.73) on Spigot 1.12.2 (I don't know if there's more detailed version info to find for that)

It seems like a Defense Buff mechanic works on one older skill, but a Damage Buff mechanic from another one is non-functional.

**Comment by Zicerite** [comment]
I am also using premium 1.74 with spigot 1.12.2, and i haven't had issues with the Defense Buff nor Damage Buff mechanic, when using multipliers. 

The editor says "Negative flag amounts or multipliers less than one will reduce damage taken while the opposite will increase damage taken."
So if you would want to take 10% less damage, you'd do 0.90 as the value.

I will go double check, but i don't ever recall it ever breaking.

ps. The age of a skill shouldn't matter whether or not it works or not, unless you are upgrading from free to premium.

**Comment by Zicerite** [comment]
Some time has passed, and some people of the skillapi community, including myself, have not been able to replicate this issue based on the details you have provided.
Are you still having issues with it? If so, send in the skill file (in a zip, not copy and pasted in here) to your next reply.

**Comment by RacerN2O** [comment]
It should be fixed I think. I'll check and close the thread if so.

**Comment by RacerN2O** [comment]
I'm currently having issues with buffs but things seem to have worked in a recent older version so I'll close this.
