### ISSUE TITLE
Request : Falling execute

### ISSUE THREAD

**Issue by EnderGriefeur99** [Eniripsa96/SkillAPI#304]
It's a new mechanic to make when a player fall and touch the ground this mechanic is executing when the player touch the ground and you can use another mechanic with this for example the mecanic block with this for change the ground when the player touch the ground after this fall. 

For create an example spell ground hit ^^

**Comment by Zicerite** [comment]
um...
Trigger: Land

**Comment by EnderGriefeur99** [comment]
this request is not a trigger:land

**Comment by Zicerite** [comment]
That's what values/flags and value/flag conditions are for.
[Electric Smite.zip](https://github.com/Eniripsa96/SkillAPI/files/2136454/Electric.Smite.zip)

**Comment by Eniripsa96** [comment]
The "Land" mechanic should only trigger when hitting the ground and accomplish what you want. If Land is triggering while still in midair or while just running on the ground, open a different issue saying that functionality isn't working. What Zicerite provided should be good for this case, so I will close the issue.
