### ISSUE TITLE
Plugin Kicks Players

### ISSUE THREAD

**Issue by ghost** [Eniripsa96/SkillAPI#306]
Once plugin is reloaded players will be kicked with this showing in console
`Internal Exception: java.io.IOException: |
Error while write(...): Connection reset by peer`
After the /class reload any of the following commands will kick the executor with the above message:

- /class reset
- /class acc
- /class profess

Server Running PaperSpigot 1.8.8 on a BungeeCord Network

**Comment by Zicerite** [comment]
I don't see PaperSpigot as a supported version.
Also, 1.8.8 is a super old version.

**Comment by Eniripsa96** [comment]
Is there any stack trace in the console?

**Comment by Eniripsa96** [comment]
Closing due to no response. Feel free to reopen with response if it is still an issue.
