### ISSUE TITLE
Question in regard to skillapi.skill.<skill-name> permission

### ISSUE THREAD

**Issue by huangrkul** [Eniripsa96/SkillAPI#308]
I downloaded the plugin yesterday to test it out, made a skill with permission required.

Then after uploading / reloading skillapi plugin with the new skill, I went to my permission plugin and added the said skill to default group.  However, the skill won't show up and I can't cast it when I use either /class cast or /class skill

My question is, does it absolutely needs a class in order to use the skill?  Or can I simply pick and choose the skill I want to use in my default group?

Thanks in advance!

**Comment by Zicerite** [comment]
You should be using a default class to put the skills in anyway. Its more organized and less of a hassle to do it that way.

**Comment by huangrkul** [comment]
Gotcha.  Thank you for the quick response!
