### ISSUE TITLE
Question: Can I use a constant + saved value for skills?

### ISSUE THREAD

**Issue by TheBrusselSprout** [Eniripsa96/SkillAPI#309]
For example, is it possible to set a value called additionalDamage and use it in a skill like this:
    Damage: 3 + additionalDamage

**Comment by Zicerite** [comment]
Combination of Value Set and Value add, but i dont remember what

**Comment by Eniripsa96** [comment]
Where you want the 3 + additionalDamage, you would probably do something like:

Value Set - key = dealtDamage and value = 3
Value Add - key = dealtDamage and value = additionalDamage
Damage - value = dealtDamage
