### ISSUE TITLE
Request: Adding unbreakable meta to items with set data durability

### ISSUE THREAD

**Issue by Flawd** [Eniripsa96/SkillAPI#31]
Why?
Because this enables servers to give skills an own icon and also in case of ProjectileMechanic an own image for the projectiles.

**Comment by Flawd** [comment]
I think this is a very great addition and it would make SkillAPI even better imo.

**Comment by Devillion** [comment]
Might it be better to have an option to hide flags for the item, then you can hide the unbrekable flag and it would never break.

**Comment by Flawd** [comment]
I think both should be available to change in the options
