### ISSUE TITLE
[Premium] Change to Combos

### ISSUE THREAD

**Issue by TerraPrimal** [Eniripsa96/SkillAPI#310]
Hi Eniripsa96,

I am hoping a small change/feature could be done for combos.
Currently, only one combo can be assigned to one skill and I'd like an option to change it so any number of skills can be assigned to a single combo.

The reason for this is to make it simpler on the users end, for example you have 3 classes. 
Each class as a Primary, Secondary and Utility skill. The way combos are set up now, each individual skill would have to have a separate combo (example Class 1's primary might have to be L L S R and Class 2's Primary L L S L).
It would make it easier if I could just have all primary's for any class assigned to L L S R so it would be universal.

Thanks for your time.

**Comment by Tiplish** [comment]
You could force the combo of a skill when you create the skill in the dynamic tool. It doesn't work?

**Comment by TerraPrimal** [comment]
Pretty sure It doesn't as soon as you reload to swaps it to an "empty combo" I was thinking it might be possible from the API.
However it would be nice to have the option built in.

**Comment by Eniripsa96** [comment]
Is there a reason why you want to cast multiple skills? This would cause problems with displaying combos in the action bar since it shows the skill name of the combo you entered. If you want the cast to be broken up into multiple skills, create one skill that just invokes the others and tie that to the combo.

**Comment by TerraPrimal** [comment]
Sorry, I might have not explained it correctly Eniripsa96.

I want to have the same combo connected to multiple skills, but only one of those skills would be for the class they have chosen.

For example, A player can choose to be a Knight, Wizard or Archer (only one).
Each one of these classes has 3 skills, an offensive, defensive and utility, For the sake of the example, we will only focus on Offensive.

Currently, each of the skills below would have to have a separate combo which makes sense if the player is able to access all of the skills, however they can only access one per class.

Sword Slash (Off) - Knight (L L R L)
Magic Missile (Off) - Wizard (L L R L)
Power Shot (Off) - Archer (L L R L)

Being able to have the same combo, can allow easier communication to players on how to activate their offensive, defensive and utility skill regardless of class.


The only other way I though of doing this is listening to the combo via the API (if there is an event for that) and then firing the skill for the player.
But Im not sure if that would work, take into effect cooldowns, mana cost etc.

**Comment by Eniripsa96** [comment]
Skills should only conflict when the player has access to multiple skills with the same combo. Skills from separate classes should not conflict and should be able to have the same combo as-is. Have you had problems with this or is this just conceptual?

**Comment by TerraPrimal** [comment]
I'm sure I have tried before and as soon as I reload, it assigns a random combo if there is duplicates.
I guess I'll have to test again to be sure.

**Comment by Eniripsa96** [comment]
Not a problem, glad it's working.

Will close the issue. Feel free to reopen or open a new issue if the problem pops up again.
