### ISSUE TITLE
"/class customize" Icon Previews not Unbreakable

### ISSUE THREAD

**Issue by RacerN2O** [Eniripsa96/SkillAPI#316]
The icon previews when using /class customize aren't unbreakable, unlike the actual icons. This makes it hard to see which skill is which when using custom icons from resource packs.

**Comment by Zicerite** [comment]
I mean, there is the names you can look at. But yeah i agree that they need to be unbreakable in the customize thing.

**Comment by Eniripsa96** [comment]
Fixed in 1.77
