### ISSUE TITLE
Class give Level command problem

### ISSUE THREAD

**Issue by minepaoz** [Eniripsa96/SkillAPI#319]
Plugin: SkillAPI Premium v1.76
Java Version: Jre 8 64bit
Spigot Version: TacoSpigot-1.8.8-latest
Console Errors: No
Player names are numbers can't be given level
ex: /class level 019 200
(Give player named 019 for 200 level)
the plugin said:  /class level [player] amount group
**please note that problem with 
Player names are numbers.**

**Comment by minepaoz** [comment]
Something like a player's name is a number, causing Plugin to become confused.

**Comment by Eniripsa96** [comment]
Will change the logic to check if the second argument is also a number to support numeric player names.

**Comment by Eniripsa96** [comment]
Fixed in 1.77
