### ISSUE TITLE
[PREMIUM] NPE with Placeholder Value Mechanic.

### ISSUE THREAD

**Issue by TerraPrimal** [Eniripsa96/SkillAPI#324]
Hi,

I've been trying to play around with the PlaceHolder Value Mechanic, however its throwing an NPE.
NPE: https://pastebin.com/GAUHc8F7
SKILL:  https://pastebin.com/zq7kwEJk

Thanks.

**Comment by TerraPrimal** [comment]
Just to make things easier to fix (and if anyone else runs into this issue)
Line 43 is String #getString("type").toUpperCase(); and the Dynamic editor has it at Type, so the online editor just needs updating to have it use type not Type.

**Comment by Eniripsa96** [comment]
Updated the editor with the fix, thanks for pointing it out.
