### ISSUE TITLE
[Request] Make Item Projectiles and Icon Crack Unbreakable

### ISSUE THREAD

**Issue by RacerN2O** [Eniripsa96/SkillAPI#329]
Just like the skill icons, item projectiles mechanics and icon crack particles could do with using Unbreakable variants for the items they display. For use with resource packs, just like with the skill icons.

**Comment by Eniripsa96** [comment]
I wasn't even aware you could do something like that with particles. Can look into it when I get the chance.

**Comment by RacerN2O** [comment]
I'm not entirely sure if it is possible for the crack particles either but I threw it in the suggestion here as well in order to mention all uses of items that aren't unbreakable for visuals. My main point was changing the projectiles and I just thought it wouldn't hurt throwing another potential thing of the same "kind" as well.

**Comment by Eniripsa96** [comment]
Added in 1.87
