### ISSUE TITLE
Passive Skill does not work

### ISSUE THREAD

**Issue by KookaiPLZ** [Eniripsa96/SkillAPI#330]
Heyy, can anyone plz help me?
I made a passive attack for my
League of Legends in Minecraft 
project, but it just does not work.
The Skill goes like this:
Intialize
Passive
Self
Con Health 15%
Launch
delay 0.2
Channel
Heal
Invincible
Delay
Heal
Delay
Heal
And it just does not show.
------------------------------------------------
The Passive should set the Player everytime
he drops under 16% HP Channeling and
let him heal 3x 10% with 1s Delay in
between. The Player should get launched
like 2 Blocks in the air while channeling
and get invincible.
------------------------------------------------
Plz, everytime I do a passive its
the same error, plz help me﻿

LG

**Comment by Eniripsa96** [comment]
Please share the actual .yml so I can better understand what you have tried. The flat text here makes it hard to tell exactly what's going on.
