### ISSUE TITLE
Defense buff seems to don't work

### ISSUE THREAD

**Issue by Tiplish** [Eniripsa96/SkillAPI#331]
Hi,

I've try some test. 
When a player is under skill defense buff & physical defense buff with a multiplier of 0.8 (so reducing damage by 20%), i hit the player with 15 skills damage. After this he has 5/20 health.

I've try the same without defense buff and he still has 5/20 health. Like if the defense buff doesn't work.

I use 1.77 version of skillAPI. Is it the same for you? Have i miss something?

Thanks

**Comment by Zicerite** [comment]
Are you using the BUFF mechanic, or Defense Buff Mechanic?

**Comment by Tiplish** [comment]
Defense buff mechanic

**Comment by Zicerite** [comment]
Skill Defense and Physical Defense buff works fine for me through the Defense Buff mechanic.
Could you drag and drop your skill into this reply? (Litterally drag the file into your reply, not through paste pin.)

**Comment by Tiplish** [comment]
[Coup puissant.zip](https://github.com/Eniripsa96/SkillAPI/files/2210901/Coup.puissant.zip)

**Comment by Eniripsa96** [comment]
Is the 15 damage coming from the damage mechanic in that skill? The Defense Buff mechanic either works on physical attacks (you hitting them with your weapon) or skills (the damage dealt via skills). Your skill has it set up for physical attacks, so the damage from the skill would not be mitigated.

**Comment by Zicerite** [comment]
No, your skill is only set to reduce *physical damage*, not *skill damage.*
You have to add in another defense buff, but set Skill Damage to true on that one.

Defense Buff works perfectly fine, it was just an error on your part, with your skill.

**Comment by Tiplish** [comment]
Hum is it possible that, when i make a change (for example add mechanic) and "save" the file, the first save doesn't take the change immediatly?

**Comment by Tiplish** [comment]
It's what i've done. The point which disapoint me is : I've do this and when i've saved the file, it hasn't take the changes that i've done on the web interface... :(

**Comment by Zicerite** [comment]
I'm not really sure what to say about that.
You have tried refreshing the page and trying again, and you have made sure you did /class reload, when putting the class file on your server?

**Comment by Tiplish** [comment]
I have make many check but not the file himself.  That's why i linked a wrong file :p I will try some test (and check if with the defense buff for skills it works).
