### ISSUE TITLE
suddenly all of my {attr:level} & {attr:cost} in skill lores stoped working

### ISSUE THREAD

**Issue by Lix3nn53** [Eniripsa96/SkillAPI#334]
icon-lore: 
  - '&5{name} &b({level}/{max})'
  - '{req:level}Gerekli Seviye: {attr:level}'
  - '{req:cost}Gerekli Yetenek Puani: {attr:cost}'

they are always 0 in all of my skills. It was working but I changed lore of some skills then it stopped working.

**Comment by Zicerite** [comment]
Duplicate of #305

**Comment by Eniripsa96** [comment]
Resolving in favor of #305
