### ISSUE TITLE
If a mob is disguised (like in Mythicmob), you could heal him

### ISSUE THREAD

**Issue by Tiplish** [Eniripsa96/SkillAPI#335]
Hi,

On our server, we use Mythicmob and Disguise. The problem is, when players have a heal spell suppose to only touch ally, it heals ennemis when they are disguised.

**Comment by Eniripsa96** [comment]
What are the enemies disguised as?

**Comment by Tiplish** [comment]
It's a zombie disguised as bat

**Comment by Zicerite** [comment]
I guess that would make sense if, healing passive mobs (or whatever the setting is called) is set to True.

**Comment by Tiplish** [comment]
I have done some tests. It seems that the "followrange" parameters of mythicmob is the issue.

If i'm too far from the mob, it detects it as an ally. So i think i could close the issue (i will reopen it if i have another issue like this).
