### ISSUE TITLE
[Premium] Small request, change to Buff display values.

### ISSUE THREAD

**Issue by TerraPrimal** [Eniripsa96/SkillAPI#336]
Would it be possible to have an option to drop the 0. from the Defense Buff etc when displaying it in the skill info?

As stated in the skill '(e.g. a 5% defense buff would be a multiplier or 0.95, since you would be taking 95% damage)'

However, when you set it to the right amount, its quite confusing on the users end as they see it as 0.95% not 95%.

Example
![Fix me daddy](https://i.gyazo.com/63e4d27cf196ad37a4b5891e9047323e.png)

Thanks!

**Comment by Eniripsa96** [comment]
I normally just set up a separate mechanic on an initialize trigger to control what exactly is shown, though for this case, since I don't think anyone would want to show the decimal variant, I can look into changing it.

**Comment by Eniripsa96** [comment]
After thinking about this feature more, I've decided not to implement it. There's ways to get the same display mentioned above and other people will want the decimal variation (e.g. "Attack deals 4x damage" instead of "Attack deals 400% damage").
