### ISSUE TITLE
[Request] Condition: Grounded

### ISSUE THREAD

**Issue by Zicerite** [Eniripsa96/SkillAPI#337]
I suppose Condition: Mid-air, would work too, but anyway...

I have been using the Condition: Block -> On Air, for almost 2 years now, and I have realized that there are real issues with it if you are wanting to check for the targets to see if they are on the ground or in mid-air.
If you are standing over an edge of a block, its considered you being in mid-air.
Same problem with Slabs. If you are standing on the lower part of a slab that isn't on top of something, it reads it as in mid-air.
Additionally, for Condition: Block -> On Air to read, you have to be at least 1 whole block in the air for it to register. 

I would like a Grounded condition to properly check whether or not the target is actually grounded, or in mid-air.

**Comment by Zicerite** [comment]
So... added in 1.85, but is missing in the editor, along with the other additions in 1.85 lol

**Comment by Eniripsa96** [comment]
Try refreshing your browser
