### ISSUE TITLE
[Bug] The Projectile mechanics don't ignore NPC's

### ISSUE THREAD

**Issue by Zicerite** [Eniripsa96/SkillAPI#339]
I have Ignore-NPC's on, and works for seemingly everything, except for Particle Projectile.

It appears the settings for the Particle Projectile itself doesn't matter, and they all trigger the NPC's.

**Comment by Zicerite** [comment]
After some more testing, Also happens with Projectile and Item Projectile.

**Comment by Eniripsa96** [comment]
Fixed in 1.79
