### ISSUE TITLE
1.12.2 Support

### ISSUE THREAD

**Issue by RedstoneLeaf** [Eniripsa96/SkillAPI#342]
When I install the newest skillapi, every time I run it the plugin doesnt register in my spigot minecraft server.

**Comment by Zicerite** [comment]
It works with 1.12.2, and works the best in that version.
You are likely forgetting something, like installing McCore. https://dev.bukkit.org/projects/mccore

**Comment by RedstoneLeaf** [comment]
Must it be the latest version of mccore to work?

**Comment by RedstoneLeaf** [comment]
Also is mccore required for the config files to show?

**Comment by Zicerite** [comment]
McCore is required for the plugin to work.
If you are using the Free version of Skillapi, try using McCore version 1.64
If you are using the premium version, use the latest verson of McCore, which is 1.67

**Comment by Eniripsa96** [comment]
Closing since it seems to be resolved. Thanks, @Zicerite for helping out.

**Comment by Zicerite** [comment]
Happy to help
