### ISSUE TITLE
[Premium] Damage Buffs not working

### ISSUE THREAD

**Issue by RacerN2O** [Eniripsa96/SkillAPI#345]
Damage Buffs seem to be flat-out not working for me. Here's an example of one of our skills where we don't end up dealing additional damage with.
[Blessing of Power.zip](https://github.com/Eniripsa96/SkillAPI/files/2233027/Blessing.of.Power.zip)

**Comment by Zicerite** [comment]
Are you using the premium version? Only the premium version can use the BUFF mechanic.
If you are using the free version, use Damage Buff.

**Comment by RacerN2O** [comment]
Interesting, defense buffs work for me, but damage buffs just won't at all.

**Comment by Eniripsa96** [comment]
Are you expecting them to work immediately or on later attacks?

**Comment by RacerN2O** [comment]
Later attacks. For some reason any use of damage Buffs doesn't work while defensive buffs work (but not immediately).

**Comment by Eniripsa96** [comment]
Tested both flat and multiplier damage buffs on subsequent attacks on the latest version and they appear to work. Update the plugin and make sure the mechanics are being hit. Closing the issue.
