### ISSUE TITLE
[Premium] Attribute Attack-Speed Major Bug

### ISSUE THREAD

**Issue by EnergizedBlast** [Eniripsa96/SkillAPI#346]
Upon using /class reload, my "Cunning" attribute seems to internally multiply; the attack speed stat bonus, provided by attribute, adds to itself every time /class reload is done to an infinite amount. The reason I know this is happening is because the ever speeding swing with tools and the attack speed NBT data shown on every tool. This persists even when the stats are taken back, the player resets their class, and even when ALL plugins are removed. The only fix for this issue, from a glance, is to delete the person's player-data file itself. No other stats are duping, though (health, mana, move-speed, etc.).

https://pastebin.com/bpQ3pZ28

**Comment by Eniripsa96** [comment]
Should be fixed in 1.80. Let me know if you're still having issues.
