### ISSUE TITLE
Console Error with 1.13 - PlayerCastSkillEvent

### ISSUE THREAD

**Issue by Zicerite** [Eniripsa96/SkillAPI#349]
The error triggered when casting the skill below. I saw that world guard was in the error at the same time when casting the skill, so idk what that means.
It is a click combo type skill.

[error.txt](https://github.com/Eniripsa96/SkillAPI/files/2241435/error.txt)

[Light Combo Swordsman.zip](https://github.com/Eniripsa96/SkillAPI/files/2241440/Light.Combo.Swordsman.zip)

**Comment by Eniripsa96** [comment]
Do you use WorldGuard? If so, is there a specific build? The error got past the "is WorldGuard loaded" check but couldn't find a class it adds, which seems weird.

**Comment by Zicerite** [comment]
Yes, I had worldguard. Build version 1722, the latest build version (as of replying this message).
The dev builds are from here: 
http://builds.enginehub.org/job/worldguard?branch=string-ids

**Comment by Eniripsa96** [comment]
Fixed in 1.81
