### ISSUE TITLE
[Request] Stackable Attribute mechanics

### ISSUE THREAD

**Issue by RacerN2O** [Eniripsa96/SkillAPI#350]
I've been messing around more with Attribute mechanics recently and they've been super helpful. The only issue I've run into is that they don't seem to be stackable, limiting the ability of making certain types of skills.
I can however also see how stacking could become problematic with passive abilities, but there should be a way of making them stack more easily than messing around with values, I think.

**Comment by Eniripsa96** [comment]
Added in 1.81
