### ISSUE TITLE
Premium [1.7.10] Console error on /class reload

### ISSUE THREAD

**Issue by Demonyte** [Eniripsa96/SkillAPI#351]
When I moved from version 1.77 to 1.78 and above, every time I load my skills.yml and classes.yml and do a /class reload command, SkillAPI breaks and stop working, with this error below. On 1.77 version of plugin everything works good, on 1.78 and above-plugin don't want to work and load my skills/classes, with error.
![screenshot_1](https://user-images.githubusercontent.com/41943583/43444507-8ecbb5a6-94ac-11e8-9459-8f2bb7568e99.png)

**Comment by Eniripsa96** [comment]
Think I've narrowed it down to the generic method reference I added to TriggerHandler. I'll remove that in the next patch and hopefully that will fix it for you.

**Comment by Eniripsa96** [comment]
Removed the likely culprit in 1.81. Let me know if it's fixed for you.

**Comment by Demonyte** [comment]
I updated MCCore just a few minutes ago, and now everything work good. But now I don't know...the thing was this culprit what you said, or old MCCore on my server...But now everything works
