### ISSUE TITLE
[PREMIUM] Particle Effect - Errors with BLOCKCRACK

### ISSUE THREAD

**Issue by EnergizedBlast** [Eniripsa96/SkillAPI#352]
https://pastebin.com/1qq5pmZL (Log)
https://pastebin.com/wZRkKxwy (Skill)

The error seems to throw regardless of whatever block material I set (Unless I'm doing something horribly wrong data wise in the mechanic of the skill).

**Comment by Eniripsa96** [comment]
Looks like a capitalization issue. Will fix.

**Comment by Eniripsa96** [comment]
Fixed pre-1.13 in 1.81. Will fix 1.13+ in a later update.

**Comment by Eniripsa96** [comment]
Fixed in 1.82
