### ISSUE TITLE
[Both Versions] Click Combo issues

### ISSUE THREAD

**Issue by Zicerite** [Eniripsa96/SkillAPI#353]
I have found (and/or gathered) information relating to click combos from both myself and the skillapi community.  Below I have listed inconsistencies or issues with them. 

Note: I have been on other servers (Ie: Wynncraft, and I am aware they use a custom system, and not any existing public-available plugin) that didn't have any of the left click issues. I, however, can not confirm that with Right Clicks though, because of reasons.

-Left Clicks: 
Don't trigger when hitting mobs. (With and without an item in either hand)
Don't trigger when hitting terrain. (With and without an item in either hand)

-Right Clicks:
Do trigger when right clicking the terrain, but not the air without an item (I'm told this might be do to a packet issue with vanilla, but because I am not sure, I put it here anyway.)

-Q (Drop) Clicks:
I'm told they don't work at all. I couldn't get them to work either, so I am not sure if that is because of user error, or plugin bug. 

Update: Tested in Adventure mode. Left clicks are only broken in Adventure mode.

**Comment by Eniripsa96** [comment]
Fixed in 1.81
