### ISSUE TITLE
Events called by a damaging skill

### ISSUE THREAD

**Issue by Indyuce** [Eniripsa96/SkillAPI#357]
Hey,
I am working on a plugin that listens to EntityDamageByEntityEvents and I am having issues with adding compatibility for SkillAPI, specifically damaging SkillAPI skills.

I noticed that when a skill damages an entity, three EntityDmgByEntityEvents get called with a damage value of 1, followed by the SkillDamageEvent and then a EntityDmgByEntityEvent again.

These are the events that are called when using a damaging skill (at least from the debug plugin I made)
![2018-08-03_17 18 35](https://user-images.githubusercontent.com/29358517/43651844-c67365be-9743-11e8-8622-b361fd102a5c.png)

I need some way of checking if an EntityDmgEvent is caused by a skill. I could use SkillDamageEvent to temporarily disable the listening of EntityDmgEvents, but the problem is that with this method, there is no way to check if the first 3 events are also due to a skill. Is there any other method I can use, like some method that returns a boolean to check if the entity is currently a skill target?

Are these 3 events safety checks to make sure the entity is damageable by checking is the event is cancelled? I know plugins that do that and that do have the spell target boolean method aside from that, it works just fine.

Thank you in advance.
Cheers

**Comment by Lix3nn53** [comment]
`if(e.getCause().equals(DamageCause.CUSTOM)){
    return;
}`

This will ignore those fake 1.0 damages. They are skillapi's friendly checks.

**Comment by Indyuce** [comment]
Works fine. Thanks a lot for your answer!

**Comment by Zicerite** [comment]
If the issue has been resolved, then you can close this issue.
