### ISSUE TITLE
Request: Took Skill Damage/skill damage triggers - new value option

### ISSUE THREAD

**Issue by Devillion** [Eniripsa96/SkillAPI#36]
I'd like to be able to select which skill will trigger the child components.

**Comment by Eniripsa96** [comment]
Skill-specific effects can be done by modifying said skill. This is a specific request that has a workaround. Due to this, I will not be adding this.

**Comment by Devillion** [comment]
hmm

Here's an example:

Let's say I make a skill called, Condemn.

Now, I want to make a passive skill that gives protection against anyone that tries to cast only Condemn on that player.

How am i able to do that by modifying said skill?

As far as I can tell, you can only detect if the player was hit by "any" skill and not just one specific skill.

**Comment by Eniripsa96** [comment]
Set a flag on yourself for the passive. Condemn would only apply to targets without that flag.
