### ISSUE TITLE
[Enhancement] Binded skill indicator in UI

### ISSUE THREAD

**Issue by demonslayer147** [Eniripsa96/SkillAPI#364]
I let players either have a choice to use SKILL BAR or BIND system to activate skill. When player using BIND command, is it possible to show something in _/class skill_ on that particular skill that have been binded to some item?

For example, if SpellA is bound with a diamond axe, then underneath SpellA information in the _/class skill_ GUI will show **Bound with diamond axe** or something like that

**Comment by Eniripsa96** [comment]
Added in 1.87
