### ISSUE TITLE
[Bug] Mana draining caster, not remembered target

### ISSUE THREAD

**Issue by Zicerite** [Eniripsa96/SkillAPI#365]
Using Version 1.83

[Nrik-Gunman.zip](https://github.com/Eniripsa96/SkillAPI/files/2281472/Nrik-Gunman.zip)

This skill used to damage mana from a target when using the Remember target in the way shown in the skill, but instead drains the caster's mana.

**Comment by Eniripsa96** [comment]
Fixed in 1.85
