### ISSUE TITLE
[Console Error] UnsupportedOperationException: null

### ISSUE THREAD

**Issue by Zicerite** [Eniripsa96/SkillAPI#366]
[ConsoleError.txt](https://github.com/Eniripsa96/SkillAPI/files/2281571/ConsoleError.txt)

Happened after reloading the class files. I think it is caused by this passive.
[Decay Shield.zip](https://github.com/Eniripsa96/SkillAPI/files/2281574/Decay.Shield.zip)

Edit: Error still spams console after everyone is offline, so idk what is causing it then :/
Reloading the class files using /class reload, just seems to break skills, classes, and for some reason the gui edits you make in /class customize, now.

Console error stops after restarting the server though.

**Comment by Eniripsa96** [comment]
Fixed in 1.84
