### ISSUE TITLE
[Console Error] ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Zicerite** [Eniripsa96/SkillAPI#367]
[Log Error.txt](https://github.com/Eniripsa96/SkillAPI/files/2285779/Log.Error.txt)

Caused by this skill:
[Horn Rush.zip](https://github.com/Eniripsa96/SkillAPI/files/2285782/Horn.Rush.zip)

Simply casting this skill causes that error. Seems to be the push mechanic with the delay, being the cause of the issue.

**Comment by Eniripsa96** [comment]
Fixed in 1.86
