### ISSUE TITLE
Request: Run command as player

### ISSUE THREAD

**Issue by RogerPlaysMC** [Eniripsa96/SkillAPI#37]
Currently the command mechanic allows you to run as OP or console. Could you add to run as player as well?  I use boosCooldowns, and all hot bar skills will bypass the cool downs unless run as a command from the player (OPs bypass the plugin altogether).

**Comment by Eniripsa96** [comment]
OP just makes them have op permissions temporarily, but runs it as the player. It should work fine.

**Comment by RogerPlaysMC** [comment]
It does run the command as the player, but with a temporary OP status, which bypasses the other plugin.

**Comment by Eniripsa96** [comment]
Skills manage cooldowns already, I'm not sure why you need boosCooldowns to handle it. You can even use flags to make other cooldowns for it.

**Comment by RogerPlaysMC** [comment]
I solved it.  In com.sucy.skill.dynamic.mechanic -> CommandMechanic.java I added
`                else if (type.equals("player"))`
`                {`
`                	p.chat(filtered);`
`                }`
 starting at line 77 and it seems to work as I needed.
