### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by B4TT3RY** [Eniripsa96/SkillAPI#371]
[![Youtube Video](https://img.youtube.com/vi/1x0D2Qw5uhY/0.jpg)](https://youtu.be/1x0D2Qw5uhY)

Hello, I have a one question about Plug-in.
could you please kindly help to support on my problems ?

I made the permission settings for the skill that i made as 'true'.

However, as you see the attached problem video,
when the authority is 'false', although the skill spaces are empty and you do not have permission to do so, when I clicked on an empty space, then  the skill is acquired.

How can I solve this problem ? please advise.

**Comment by Eniripsa96** [comment]
Fixed in 1.87
