### ISSUE TITLE
Passive doesn't work

### ISSUE THREAD

**Issue by survetman** [Eniripsa96/SkillAPI#372]
Hello, I have a problem when I want to create a passive. 
As you can see in my file, I use the triger Initialize on myself to do my passive with Value condition to do different things if the passive is activated or desactivated. In the same time I use the trigger Cast to set the value 1 or 0 to activate or desactivate the passive. 
But there is a problem with this. When I cast the skill to activate the passive, it works but then when I cast an other time the skill, it desactivates and reactivates directly the passive. And I don't understand why it does this. So can I have some help about this ?

[Test.zip](https://github.com/Eniripsa96/SkillAPI/files/2299737/Test.zip)

**Comment by Eniripsa96** [comment]
For your cast trigger, you have the mechanics to set the value to 0 which then passes the second condition, running both.

To make this much simpler, remove the value usage to toggle the passive, and just use "Flag Toggle" which handles all the toggling for you. It will end up looking like this:

[Test.zip](https://github.com/Eniripsa96/SkillAPI/files/2299759/Test.zip)
