### ISSUE TITLE
Request: Ranged Damage Attribute?

### ISSUE THREAD

**Issue by lilbudgotswag** [Eniripsa96/SkillAPI#375]
So theres skill damage attributes and physical damage attributes but no bow related attributes?
I'm not sure how hard of an issue this is to fix, but I would really love to see this.

**Comment by Zicerite** [comment]
The newest Skillapi Premium update that released some hours ago added a vanilla projectile damage and defense type attribute possibility.

**Comment by Eniripsa96** [comment]
As Zicerite said, this was just added in the Premium version. Closing the issue since it now exists.
