### ISSUE TITLE
Request/suggestion/problem with ally feature

### ISSUE THREAD

**Issue by havencraftmc** [Eniripsa96/SkillAPI#38]
My issue is this:  I want to allow pvp and have pvp plugins manage that which means I need to force all players to be enemies on the server.  This makes it impossible to distinguish negative and positive targets for status effect spells and healing spells using the ally and enemy flags.  Is it Possible to implement a feature using the party plugin which would force all players in a party back to the ally status?  This would mean I could cast a spell targeted at an ally and be able to heal players in my party but not outside of it.  It probably wouldn't be too hard to code in.  If there is any other way to get around this I'd be interested in learning how to get this done. Thanks in advance

**Comment by Eniripsa96** [comment]
There's the "all or nothing" categories which you are talking about in the config, but SkillAPI also determines a player to be an "ally" if any other plugin stops the players from attacking one another. So any sort of plugin or system you may have that stops certain players from attacking one another will work.
