### ISSUE TITLE
[Question] Does melee & projectile damage attributes effect...

### ISSUE THREAD

**Issue by Lix3nn53** [Eniripsa96/SkillAPI#380]
Does melee & projectile damage attributes effect skills with "physical" damage classification?

If it doesnt can you make them effect them?

**Comment by Eniripsa96** [comment]
They do not. Skills don't have the concept of physical at all, and even projectiles themselves don't have innate damage. However, you can use dynamic modifiers to target the damage effects you want, so there is a way to do it currently. For that reason, I'll likely leave this alone.
