### ISSUE TITLE
(Dynamic Editor) Potion Condition doesn't work

### ISSUE THREAD

**Issue by Vyrgax** [Eniripsa96/SkillAPI#385]
Potion Condition in the dynamic condition doesn't work. When I try to add it I can't choose the potion type, and neither can I click on 'Done'. If I switch to another ability the menu is still there. I tried it on different computers and browers to make sure; Neither on Google Chrome or Firefox does it seem to work.

**Comment by Zicerite** [comment]
So... im guessing its fine then?
You shouldn't randomly close an issue report.

**Comment by Eniripsa96** [comment]
This was fixed, I just forgot to update the issue before he closed it.
