### ISSUE TITLE
SkillAPI and KCauldron

### ISSUE THREAD

**Issue by GlassSpirit** [Eniripsa96/SkillAPI#39]
Is there any way to fix item lore bonus attributes and particle system on KCauldron 1.7.10?

**Comment by GlassSpirit** [comment]
And have you heard about minecraft Sponge platform?

**Comment by Eniripsa96** [comment]
I'm not sure of the internal differences between Sponge and normal NMS/Bukkit, so I don't know of a way I would fix them, though Item Lore just uses the normal API which should still work. Make sure you enable all related settings for those.

Also, I know of Sponge, just last time I checked, it wasn't far enough along for me to convert the project to it.

**Comment by GlassSpirit** [comment]
Yeah, sorry, item lores are my config fault.
By the way, in latest version it deletes "icon lore" line in class config. Take a look at it pls.
