### ISSUE TITLE
Ally 

### ISSUE THREAD

**Issue by KookaiPLZ** [Eniripsa96/SkillAPI#399]
Hey, I wanted to ask how the ally thingie works.
It doesnt work with scoreboards tho, would be really cool if that was added

**Comment by Tiplish** [comment]
I you can't hit someone, it's an ally :) you could use Parties to make team.

**Comment by KookaiPLZ** [comment]
Yeah, but how? How do I add someone to my ally? xd

**Comment by Eniripsa96** [comment]
As Tiplish is hinting at, you need to use another plugin to set players as allies. SkillAPI out of the box does not define allies or teams.
