### ISSUE TITLE
[Suggest] Is it possible to add a Heal lore?

### ISSUE THREAD

**Issue by Tiplish** [Eniripsa96/SkillAPI#403]
Hello, i would know it's possible to add a Heal lore like damage lore mechanic? Thanks :)

**Comment by Zicerite** [comment]
You can use Value Lore to get the same effect.

**Comment by Eniripsa96** [comment]
Value Lore
Heal (set value to the key from Value Lore)

See https://github.com/Eniripsa96/SkillAPI/wiki/_Tutorial-Advanced-Values for more details
