### ISSUE TITLE
[Question] Basic Abilities

### ISSUE THREAD

**Issue by EquinoxTheEdgy** [Eniripsa96/SkillAPI#408]
I'm wondering if it's possible to make class-based abilities that are automatically learned when you select a class, and can't be unlearned?

**Comment by Zicerite** [comment]
Yeah, that's one of the key things this plugin does.
You should look through the wiki.

**Comment by EquinoxTheEdgy** [comment]
I couldn't find it - any pointers?

**Comment by EquinoxTheEdgy** [comment]
If it was in the skills section, that's blank now for some reason :P

**Comment by Eniripsa96** [comment]
Make the cost of the skill 0 and the level requirement 1. Skills with cost 0 will automatically unlock and the level 1 requirement makes it happen as soon as you profess as a class.
