### ISSUE TITLE
[Suggestion] Toggle Skill Bar/Hot Bar

### ISSUE THREAD

**Issue by EquinoxTheEdgy** [Eniripsa96/SkillAPI#409]
I'm wondering if it'd be possible to have an option added to toggle your skill bar or hotbar?  So, you can switch between the two, essentially.

**Comment by Eniripsa96** [comment]
Enabling combat bars (enable the Casting section and the "combat" option under it) lets players swap by pressing 9 (9th slot is an item that toggles between the two).

**Comment by EquinoxTheEdgy** [comment]
As I said in the other one, sorry for being an idiot in that case.
