### ISSUE TITLE
[Suggestion/Premium] Add cosmetic items to GUIs

### ISSUE THREAD

**Issue by EquinoxTheEdgy** [Eniripsa96/SkillAPI#410]
The title says it all, I think.  Basically, the ability to add non-clickable items to the GUIs to make them look a bit neater.  For instance, a glass border.

**Comment by Eniripsa96** [comment]
This is possible in premium already. Add items to "tool.yml" and then use "/class customize" to arrange it.

**Comment by EquinoxTheEdgy** [comment]
I'm an idiot in that case, sorry.
