### ISSUE TITLE
[Question] Passive that increases max Mana

### ISSUE THREAD

**Issue by EquinoxTheEdgy** [Eniripsa96/SkillAPI#413]
Sorry I'm asking so much, but I couldn't find a way to make a passive that increases your max mana, is it possible?

**Comment by Tiplish** [comment]
You could make an attribute which increase you max mana and give this attribute with the buff mechanic.

**Comment by Zicerite** [comment]
Make an attribute that increases max-mana, then use an Attribute Mechanic under a passive.

**Comment by Eniripsa96** [comment]
This seems to be solved as the attributes are the way to do it. Closing this issue.
