### ISSUE TITLE
[Question] Play sound when cast fails

### ISSUE THREAD

**Issue by EquinoxTheEdgy** [Eniripsa96/SkillAPI#414]
I can't seem to get it to work, so I'm wondering if I could get help?  Here's the file.
https://www.dropbox.com/s/4htzszthqp3pysi/Backstab%20%2836%29.yml?dl=0

**Comment by Eniripsa96** [comment]
Else conditions should be after other conditions. In the editor, drag and drop the Else condition onto the trigger to move it to the end, and you should be good to go.
