### ISSUE TITLE
[Question] Dodge Chance/Block Chance Attribute?

### ISSUE THREAD

**Issue by EquinoxTheEdgy** [Eniripsa96/SkillAPI#418]
Is it possible to make an attribute that gives you a chance to ignore damage on hit?  And one that gives you a chance to reduce damage on hit?

**Comment by Eniripsa96** [comment]
Reduce damage on hit can just use "physical-defense" or "skill-defense" stats to reduce damage. In premium, there's also "melee-defense" and "projectile-defense".

A chance to ignore damage can't be done with only attributes, but if you give everyone a skill that uses attributes to determine the chance, you could do it that way. It would look something like:

Value Attribute mechanic
Value Multiply mechanic (depending on how much % you want per point)
Chance condition
> Cancel

And that would be on the Took Physical Damage trigger (or skill damage if you want skills)
