### ISSUE TITLE
Bug: Color codes being overwritten

### ISSUE THREAD

**Issue by Devillion** [Eniripsa96/SkillAPI#43]
If you look at my lore here for a skill, you'll see that the color of the text does not match with what I use in my icon lore for my skill.

http://i.imgur.com/tWYxr0U.png

**This is what I have**

`&f - &e{req:level}Level: &f{attr:level}
&f - &e{req:cost}Cost: &f{attr:cost}
&f - &eMana: &f{attr:mana}
&f - &eCooldown: &f{attr:cooldown}`

The "Level:" should be &e (yellow), but it shows up as green and the attribute level shows up as gold instead of white.

I assume you have hard coded these colors in  your code and the color codes that I add are being overwritten. 

Can you fix this?

**Comment by Eniripsa96** [comment]
This is not a bug. The {req:level} filter is part of the language config and is a color itself (green for requirement met, red for requirement not met by default). Either remove that filter or change those colors there.
