### ISSUE TITLE
Inventory item lores

### ISSUE THREAD

**Issue by GlassSpirit** [Eniripsa96/SkillAPI#44]
Can I get a lore of equipped armor or item in special slot number in inventory and use it for Value skill mechanics?
Anyway, checking for item lore in specific inventory slot would be useful feature with some other plugins like InventoryPlus or RPGInventory.

**Comment by Devillion** [comment]
I like this request, it's something I've been meaning to suggest as well.

It would let us setup ring slots and some other cool uses.

**Comment by Eniripsa96** [comment]
Added in latest version
