### ISSUE TITLE
Bug: Health goes to default after reconnect

### ISSUE THREAD

**Issue by GlassSpirit** [Eniripsa96/SkillAPI#45]
The health amount goes to default after player reconnect to server.
For example, I have 50 default hp and 30 more from attributes and equipment. After I reconnect to server my hp is 50/80 in any cases. It's really annoying, because of low rate of hp regeneration and ext. Can you fix this pls?

**Comment by Devillion** [comment]
happens to me also

**Comment by sheeeeeeets** [comment]
Same here

**Comment by CorporalBruno** [comment]
I concur, on a bungee network switching servers that both share SKILLAPI the health is reset to lowest possible amount, also doesnt remember if you have hearts set to show real or fake hearts. Have to switch classes to get the hearts to adjust. If you are hungry its guaranteed death for low level players. Our player start with 3 hearts, so this is incredibly cumbersome.

I hope to get it fixed as soon as possible. 

Thanks for looking into this.

**Comment by Eniripsa96** [comment]
Should be fixed in 3.89
