### ISSUE TITLE
Damage stacks

### ISSUE THREAD

**Issue by Vyrgax** [Eniripsa96/SkillAPI#452]
When holding a weapon, such as a diamond sword, and cast a skill which inflicts damage, the damage stacks, meaning it deals the base damage of the skill + the damage of the sword.

This actually breaks the entire 'damage' mechanic.

**Comment by xxJinxedxx** [comment]
This is what is suppose to do, its perfectly accrued. You should tweak your skill if you want it not to do the damage of the weapon or something. But there is noting game breaking here.
