### ISSUE TITLE
Bug: Issue with the hot bar mode

### ISSUE THREAD

**Issue by Devillion** [Eniripsa96/SkillAPI#46]
If you open your inventory and right click on the seeds they dissappear.

Using the /class bar command to enable/disable that bar doesn't get them back.

only way to get the icons back is to /class reload

**Comment by GlassSpirit** [comment]
It's meant to be so, couse it's a skillApi feature. Just right click 1 more time and it will appear again

**Comment by Eniripsa96** [comment]
This is indeed a feature. Right clicking allows players to toggle a slot between a regular item slot and a skill slot so that they can customize where they are and how many there are. To make this not happen, you must "lock" the slots in the config.
