### ISSUE TITLE
BUG:  Casts skill in slot 1 upon zoning into portal or respawning

### ISSUE THREAD

**Issue by sheeeeeeets** [Eniripsa96/SkillAPI#47]
I noticed that when I zone my server, it auto casts whatever skill is in my first slot.  It also casts skill in first slot anytime you spawn, in the End, Nether, or respawn from dying.

Was testing my Mage and the fireball that catches everything on fire spell i made killed me, respawned in wooden house, and annihilated my house also....

I noticed the problem when I was testing other skills, thought nothing of it, placed fireball in skill slot 1 like an idiot, everything was burnt...

**Comment by Eniripsa96** [comment]
I've talked to others about this issue and it seems only some people are experiencing this. Please provide more information such as what server you are using, whether or not it still happens with just SkillAPI/MCCore installed, or any other possibly related information.

**Comment by sheeeeeeets** [comment]
Will try to create a server with just SkillAPI and MCCore today when I get home and test to see if it still happens.

![plugins](https://cloud.githubusercontent.com/assets/18426335/15289140/1bc22818-1b3e-11e6-9173-d28d14f1ee9f.PNG)
