### ISSUE TITLE
"Purge" Mechanic Error

### ISSUE THREAD

**Issue by xxJinxedxx** [Eniripsa96/SkillAPI#472]
SkillAPI Premium v1.87
Server version: paper spigot 1.8.8-R0.1

Issue: Applying "Purge" to a target, error. (tested on mob only)
https://pastebin.com/EuafdJyb

**Comment by Zicerite** [comment]
This is a confirmed bug, but an easy work around is to put a condition of what you are trying to purge, then use the purge mechanic.

If you have any further questions, there is a discord link on the main page to get support.

**Comment by xxJinxedxx** [comment]
Hmm, i already have 2 conditions "Entity Type" & "Chance".
I'll experiment a bit more then, most importantly i wanted to report the issue first. I'm in the discord too, but since it was an bug i saw no use of saying anything there.
Thanks for the help.

**Comment by xxJinxedxx** [comment]
For anyone that has this issue:
Till the current date of the post, the bug is still present. Check Spigot or Discord for followup's.
Since the bug is known, there is no point of keeping the ticket open.
