### ISSUE TITLE
Trigger: Physical Damage + Mechanic: Launch Issue

### ISSUE THREAD

**Issue by xxJinxedxx** [Eniripsa96/SkillAPI#475]
SkillAPI Premium v1.87
Server version: paper spigot 1.8.8-R0.1

Issue: When the trigger is set to "Target Caster: False" and there is a launch mechanic, the "Upward Speed" of the launch mechanic is inconstant to applying it to the target.

From my tests i came to the conclusion that is due the vanilla "knockback effect" when you hit the entity.
 - If there is no knockback effect when you do the hit, the Launch mechanic "Upward Speed" **will work correctly**
 - If upon hitting the entity there was a knockback applied to it (vanilla) due the hit, the "Upward Speed" **will not work**.

P.S. - I manage to get a workaround it by adding a Delay mechanic to it.

The example skill - https://pastebin.com/GGXh8cBc

**Comment by Eniripsa96** [comment]
There's not a way around that. I'll leave it as is since the workaround of adding a delay works.
