### ISSUE TITLE
"Potion" Condition Issue

### ISSUE THREAD

**Issue by xxJinxedxx** [Eniripsa96/SkillAPI#478]
SkillAPI Premium v1.88
Server version: paper spigot 1.8.8-R0.1

Issue: With a "Potion" condition set to "Not Active" _(poison)_ and mechanic Potion _(poison)_ to affect the target i get this error:

 - http://pasted.co/791e695d

_This is the only configuration i have tested_

**Comment by Eniripsa96** [comment]
should be fixed in 1.89
