### ISSUE TITLE
RPGItem damage stacking issue

### ISSUE THREAD

**Issue by Vyrgax** [Eniripsa96/SkillAPI#479]
RPGItem is a popular weapon/armour plugin which allows players to create their own weapons with custom damage. A diamond sword can have 10 damage, or 1, or even have a range (random between 4 and 8 for example). 

When casting a skill which inflicts damage, the damage is applied on the target, as well as the damage the weapon does. This leads to gamebreaking skill combos.

I would really appreciate it if this would be looked into.
I do must thank you for your recent patches on the 1.13 version of SkillAPI premium, almost everything works fine and makes the wait to the Kotlin rewrite much more bearable since we have a working version for 1.13 now.

**Comment by xxJinxedxx** [comment]
This is basically the same thing that you have mentioned in [#452(https://github.com/Eniripsa96/SkillAPI/issues/452).

**Comment by Eniripsa96** [comment]
I don't think I can really do anything about this, as I wouldn't be able to discern between RPGItem tweaking the damage incorrectly or someone else correctly tweaking the damage for any reason. You may need to get RPGItem to not apply it's damage modification for skill damage.

I provide the method "Skill.isSkillDamage()" for this reason.
