### ISSUE TITLE
Request:  Get experience from kills with spells

### ISSUE THREAD

**Issue by sheeeeeeets** [Eniripsa96/SkillAPI#48]
Sorry, I must be viewed as a nag :(

I made a magician class who uses Lightning Strike and Fireball (Ghast projectile + Explosion), and when the explosion or lightning kills something, the Mage doesn't get experience for it.

Can we get this changed, or could I be doing something wrong?

**Comment by Eniripsa96** [comment]
This is something that is not part of the plugin currently, but there are plans of adding support for them.

**Comment by sheeeeeeets** [comment]
I will close this then, since its in the books.  Thanks for the re-assurance :)

Mages can just suffer until then!

**Comment by Eniripsa96** [comment]
Can leave it open until it's added as a reminder for myself.

**Comment by bloggy** [comment]
It's been a long time. When will you add it?

**Comment by Eniripsa96** [comment]
I've been looking into experience-related issues but they are fairly complex. I will add them when I figure them out.

**Comment by Eniripsa96** [comment]
Should be fixed in the latest version
