### ISSUE TITLE
One question

### ISSUE THREAD

**Issue by DoloStar** [Eniripsa96/SkillAPI#49]
Excuse me can you make config for skill can set:
x: 
  name: 'y'
now must be the same
y:
 name: 'y'

**Comment by Eniripsa96** [comment]
Why would you need something like that?

**Comment by DoloStar** [comment]
Because I use marco/keybind mod to bind skills, then I use the Chinese, that mod can not read Chinese.
But I'll just solved this problem XD

**Comment by DoloStar** [comment]
Sorry,i want know maybe can set a trap?
Placed in a block,when player walking on the block will trigger skills

**Comment by Eniripsa96** [comment]
There's not block-specific activation, but if you do a Block mechanic and then an Offset target with a Repeat mechanic and Area target, you can do something like a trap.

**Comment by DoloStar** [comment]
ty
