### ISSUE TITLE
Classes and Skills

### ISSUE THREAD

**Issue by TempleOfLegends** [Eniripsa96/SkillAPI#51]
I replaced the classes.yml and the skills.yml in and put loaded to true but they aren't working. Any help?

EDIT: the classes are fixed , but the console says the skills are invalid
e.g. [13:39:14 ERROR]: Invalid skill for class Knight - Avenger's Smite

**Comment by TempleOfLegends** [comment]
The classes are fixed , but the console says the skills are invalid
e.g. [13:39:14 ERROR]: Invalid skill for class Knight - Avenger's Smite

**Comment by TempleOfLegends** [comment]
Also my loaded skills aren't giving any effects.

**Comment by Eniripsa96** [comment]
The "loaded" option should be false when making changes, not true. When it's set to true, that's telling the plugin it already loaded the file so it can skip it.

**Comment by TempleOfLegends** [comment]
We found out the problem! But we set it to false before
