### ISSUE TITLE
Skills issue

### ISSUE THREAD

**Issue by TempleOfLegends** [Eniripsa96/SkillAPI#52]
The console tells me that the skills for the classes are invalid, (they were all made via Dynamic Editor and put in the dynamic folder replacing the old skills.yml.) however other skills work perfectly. Any tips? Ex. [13:39:18 ERROR]: Invalid skill for class Rouge - Paralyzing Strike.

**Comment by Eniripsa96** [comment]
That message means the skill wasn't loaded. Either it wasn't added to the server properly or you need to stop/start your server. Make sure you follow the instructions here when adding individual skills: https://github.com/Eniripsa96/SkillAPI/wiki/_Tutorial-Adding-to-Server
