### ISSUE TITLE
Hitbox Issues with Particle Projectiles on Mobs >1 Blocks Tall

### ISSUE THREAD

**Issue by PandasaurusR** [Eniripsa96/SkillAPI#56]
Hey Eni,

I have an issue that particle projectiles do not register a hit when aimed at the top portion of mobs. This can be seen in the screenshots below.
[http://prntscr.com/bl8kks](http://prntscr.com/bl8kks)
[http://prntscr.com/bl8lu7](http://prntscr.com/bl8lu7)

I am using the latest version 3.89 of SkillAPI

P.S. I love your mod, its really dynamic and so versatile :+1:

**Comment by Eniripsa96** [comment]
Thinking about it, I can see why that would occur. I'll have to adjust my collision detection. Thanks for letting me know.

**Comment by Eniripsa96** [comment]
Fixed in v1.11
