### ISSUE TITLE
Skill bar placeholder icons cannot be changed in config

### ISSUE THREAD

**Issue by PandasaurusR** [Eniripsa96/SkillAPI#57]
The default placeholder icon for an empty skill slot cannot be changed from the pumpkin seeds. While the text/name of the icon is responding to changes in the config.yml file, the icon does not change when the "material: 'X'" is changed. This is the case with both object IDs and NBT tags. 

P.S. The ability to add lore text to the placeholder icons would also be a useful addition. This way a summary of how to bind skills can be written when mousing over the icon.

**Comment by Eniripsa96** [comment]
Make sure you are using a valid Bukkit material name for the placeholder material. The lore is something I can agree with and will likely add.

**Comment by Eniripsa96** [comment]
Added in premium v1.1
