### ISSUE TITLE
how can i use one of the skills by my plugin.i should use which method and in which java class

### ISSUE THREAD

**Issue by DDMCloud** [Eniripsa96/SkillAPI#59]
how can i use one of the skills by my plugin
i should use which method and in which java class

i am a developer
please give me the example java code

**Comment by SettingDust** [comment]
There are some em. already.BTW,ur poor en. is prove sth.XD

**Comment by SettingDust** [comment]
There are some em. already.BTW,ur poor en. is prove sth.XD

**Comment by DDMCloud** [comment]
what is “em”
my english is not very well。。。。
can you give me some example code？

**Comment by SettingDust** [comment]
sorry 4 my short of example(em),chinese?japanese?plz find the code from offical webpage(bukkit.org)

**Comment by DDMCloud** [comment]
chinese.so...can we talk by a software like QQ/MSN？I think talk in the github is too trouble

**Comment by DDMCloud** [comment]
https://github.com/Eniripsa96/SkillAPI/wiki/Code-API

is it the em code you say？
i can find my question's answer from it....
please help me...

**Comment by DDMCloud** [comment]
i want to use the skill by:

XXXXX.skill1();
XXXXX.skill2();

what should i do？

and how can i add players'quality like health/mana？
i shou make a plugin for my server

**Comment by SettingDust** [comment]
WTF,MSN???sry 4 ur en. i think its 2 difficult 2 understand 4 a normal hunmanXDDD,maybe u can ask help in mcbbs????????dont use issues plz

**Comment by DDMCloud** [comment]
in china...not many people will answer question........

you just tell me how can a plugin ask a player use a skill is enough

**Comment by SettingDust** [comment]
cant understand,wt?can cast skill?wtf?condition?

**Comment by SettingDust** [comment]
make a player cast skill?wtfking god

**Comment by SettingDust** [comment]
u must hv no basic,plz read example&tutorial

**Comment by DDMCloud** [comment]
the em is the way to create new skill and occupation......

my idea is create a new equipment/item to add players'quality

**Comment by SettingDust** [comment]
plz ask these questions on mc bbs ​,ok?

**Comment by Eniripsa96** [comment]
Read the tutorials here for help with coding your own skills:
https://github.com/Eniripsa96/SkillAPI/wiki/Code-API
