### ISSUE TITLE
How?

### ISSUE THREAD

**Issue by SettingDust** [Eniripsa96/SkillAPI#63]
I just want to introduce this plugin in Chinese and I'll provide this download link of your page.I'll only provide the language.yml、config.yml etc. with Chinese to them.
I'm really want to know what should I do to get your trust.
And can you rebuild with Maven like my pull requestXD.
Thanx for read.

**Comment by Eniripsa96** [comment]
As long as you don't claim it as your own, and keep the download link pointed to my project pages it's fine.

**Comment by SettingDust** [comment]
Of course I will and you can check it. There is your link on bukkit.org.
Now, can I? I'll send the link to you.

2016-08-22 1:08 GMT+08:00 Steven <notifications@github.com>:

**Comment by SettingDust** [comment]
And I just provide the yml files in zh_CN. The download link is still point
to your project.

2016-08-24 22:58 GMT+08:00 夕尘 <settingdust@gmail.com>:
