### ISSUE TITLE
SkillAPI Premium - Obtaining spell item when pressing Q 

### ISSUE THREAD

**Issue by PandasaurusR** [Eniripsa96/SkillAPI#65]
Hey Eniri,
Our network recently purchased SkillAPI Premium and immediately an issue was noted by me while developing for the premium version of the plugin. There are several issues I will post here, the first of which is:
When the book is left clicked to bring up a hotbar of spell shortcuts, should a spell item be attempted to be thrown out of the inventory with the Q button, the item is instead placed in the player's inventory.

**Comment by Eniripsa96** [comment]
Fixed in Premium v1.4
