### ISSUE TITLE
SkillAPI Premium - Relogging provides duplicate skill books

### ISSUE THREAD

**Issue by PandasaurusR** [Eniripsa96/SkillAPI#66]
Hey Eniri,
The second issue is as follows.
Should a player relog with the skill book in any slot other than the slot which activates the spell organising GUI, the plugin provides the player with another skill book and proceeds to remove the item already in that slot.

**Comment by Eniripsa96** [comment]
This is because the book is expected to remain in the original slot, not able to be moved. This itself is not an issue.
