### ISSUE TITLE
SkillAPI Premium - Left/Right Click skill cycling spell items can be removed wholly from the slot and added to the player inventory

### ISSUE THREAD

**Issue by PandasaurusR** [Eniripsa96/SkillAPI#68]
Hey Eniri,
The fourth issue is as follows:
When the skill bar is disabled and the cycling option enabled where the spells are cycled with left & right click, the items in the slot can be removed enmasse with a simple left click in the inventory window. This is similarly problematic when viewed with the item removal issue when the skill bar is enabled in the first issue submitted.

**Comment by Eniripsa96** [comment]
Fixed in Premium v1.4
