### ISSUE TITLE
SkillAPI Premium - Legacy spellcasting format is missing. /class bar etc.

### ISSUE THREAD

**Issue by PandasaurusR** [Eniripsa96/SkillAPI#69]
Hey Eniri,
The final issue for now is the inability to use the legacy casting system at all. /class bar has been removed from the plugin and the old method of casting spells was a dependable one that players liked and have gotten used to. If this could be reenabled as an option that would be greatly appreciated.
Whilst the newer methods are definately elegent, they are poorly implemented as of current we have had to return to the free version as it has a more dependable casting system.

Hope these can be addressed ASAP. Thanks a lot :)

**Comment by AngDrew** [comment]
do you will grant anything that i want about skillapi if i have premium
version???

**Comment by Eniripsa96** [comment]
Do you have the premium casting systems disabled?

**Comment by PandasaurusR** [comment]
Right, it turns out a restart needs to be initiated before the legacy casting system returns. Thanks :)

**Comment by Eniripsa96** [comment]
Alright, glad it's working.
