### ISSUE TITLE
/class bar command not working anymore

### ISSUE THREAD

**Issue by bloggy** [Eniripsa96/SkillAPI#71]
Hey there,
just downloaded the latest premium version of SkillAPI and the /class bar command does not work for me anymore. I already tried it with a fresh config. class bar option is enabled in config.

When I enter /class bar only the help menu shows up.

In the previous version (free one) it worked for me, but still was buggy. For example I could only add 1 skill at a time to my bar, not more. 

Also the scoreboard does not update itself anymore nor does the nameplate level number.

**Comment by Eniripsa96** [comment]
Make sure you do not have the premium casting enabled (enabled under "Casting"). If that's enabled, skill bars are disabled regardless of their settings.

There was an MCCore patch that fixes the scoreboard update.

**Comment by bloggy** [comment]
Thank you. That seem to fix it. Hope you can get up the wiki for the premium features soon, because I have no idea what these features are doing and we are about to migrate to your plugin on our RPG server :-)
