### ISSUE TITLE
Bug with /class reload

### ISSUE THREAD

**Issue by bloggy** [Eniripsa96/SkillAPI#74]
**1.) BUG** 
Using the latest SkillAPI Premium version.

Steps to reproduce:

1.) Join a class
2.) Give yourself some experience
3.) Enter /class bar
4.) Put a skill into 1st slot of your hotbar
5.) Enter /class reload

You will receive the item representing the skill. It will be put in the last spot of your hotbar and you can use it like a normal block.

**2.) BUG** 

Also using /class reload I get a skill book every time I execute that command.

**3.) BUG**
Another bug:

We made a Jump-Skill ( http://hastebin.com/uxolowugen.bash )
When you cast the skill the moment you die, you can still jump (while you're dead). After respawn you get kicked because of "Fly":
[17:38:37] [Server thread/WARN]: Grappa was kicked for floating too long!
And when you reconnect to the server you are in fly mode!

**Comment by Eniripsa96** [comment]
Should be fixed
