### ISSUE TITLE
Unable to get spell to work

### ISSUE THREAD

**Issue by wabysab** [Eniripsa96/SkillAPI#75]
**The spell has two indented triggers, one that flags the player receiving damage from the castor, and the other that deals damage to the player after a 4 second channel. For a reason I am not aware of, the spell does not effect any other players or mobs after the channel is complete.**

[Quivering Palm.txt](https://github.com/Eniripsa96/SkillAPI/files/504713/Quivering.Palm.txt)

**Comment by Eniripsa96** [comment]
The only thing I noticed here was the Physical Damage Taken trigger was set to target the caster, not the target, so the target would never have the flag.
