### ISSUE TITLE
Silence & Stun: Not effecting Repeat Skill

### ISSUE THREAD

**Issue by TagCraftMC** [Eniripsa96/SkillAPI#76]
Hi Eniripsa96,

Not sure if this is intended, but when the repeating skill is active it does not take into account if the player is silenced or stunned.

If this is not intended, checking if the caster is silenced/stunned at the start of the scheduler should be a fairly easy fix.

I tested with a skill that sent a message every second for 60 seconds, then whilst it was running stunned and silenced the person for 5 seconds, the expected result would be the repeat skill would miss 5 seconds/messages instead it continued on.

Thanks

**Comment by Eniripsa96** [comment]
It wasn't intended to stop lingering effects. If that's behavior you want, add a condition in your repeat mechanic. It's more flexible as-is and in my opinion makes more sense without stopping effects part-way through.
