### ISSUE TITLE
skillapi and Citizens2

### ISSUE THREAD

**Issue by Ivsqt8** [Eniripsa96/SkillAPI#79]
my server is PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest
lang is cn
if i create a npc name with chinese
then   skillapi cann't save to sql

**Comment by Ivsqt8** [comment]
if i fight npc
then skillapi will error
http://hastebin.com/upomuyexit.bash
if npc is creative the skillapi haven't error

**Comment by Ivsqt8** [comment]
save to sql error
http://hastebin.com/fayamiloti.bash

**Comment by Eniripsa96** [comment]
Fixed in v1.14
