### ISSUE TITLE
Status Skill: Incorrect Target With Item Projectile

### ISSUE THREAD

**Issue by TagCraftMC** [Eniripsa96/SkillAPI#80]
When using the Item Projectile Skill along with the Status Skill, the status is applied to the caster if no target is hit.
This does not seem to be the valid response, if no targets are hit then no targets are effected by the child skills of Item Projectile.
An example below;
|> Cast
|> Message
|> Sound
|> Item Projectile
|>> Damage = 10
|>> Status = Stun
- When a target is hit by the Item Projectile, they take the damage and the Status.
- When no target is hit, the caster takes no damage but takes the Status. The caster should not be receiving the stun if no target was hit.

Thank You.

**Comment by Eniripsa96** [comment]
Odd, not sure why/how this would happen, but I can look into it.
