### ISSUE TITLE
Suggestion: BossBar Mechanic

### ISSUE THREAD

**Issue by TagCraftMC** [Eniripsa96/SkillAPI#81]
Small suggestion,

It would be great to see a BossBar Mechanic added to the SkillAPI software.
I would be great if it had a "timer/animation" option, much like the Particle Animation or Channeling system, it would stay up for X time and ever second loss a % of the bar.

|> Trigger: Cast
|> Target: Self
|> Mechanic: BossBar
|>> Settings for BossBar
|>> Name: Cast Time
|>> Color: PURPLE
|>> Start Percentage: 100
|>> Timer: 10 (seconds)
|>> Percent Lost Per Time: Yes
_----------------------------------_
.................................Cast Time
@10 Seconds [##########]

.................................Cast Time
@5 Seconds [#####...............]

.................................Cast Time
@1 Seconds [#......................... ]

I am sure if you accept this idea and get what I mean you could implement it in a much better way, although I don't have the premuim version yet. I am sure it would be a great addition to it.

Sorry for the weird .'s and |'s. Github really hates spaces in the formatting.

**Comment by Eniripsa96** [comment]
I'll have to think about this one. Boss bars for a more specific purpose such as this seem a little out of place.
