### ISSUE TITLE
Suggestion: Remember Target Mechanic, .getName()

### ISSUE THREAD

**Issue by TagCraftMC** [Eniripsa96/SkillAPI#82]
Super simple suggestion, when using Remember Targets (Mechanic) and putting it's value in a Message Mechanic it shows the Player Object, it would be great if adding .name to the end of the value showed just the name.

{skillTarget) shows;
![Image](https://i.gyazo.com/039f22f6bbbdede71be448e7659bab64.png)

{skillTarget.name) shows;
![Image](https://i.gyazo.com/22d00bcb1e436659fb9b51c8e0c90ffc.png)

If this is already a implemented, a point to where this is described on the wiki/thread would be greatly appreciated.

**Comment by Eniripsa96** [comment]
This is not implemented. I may not require ".name" at the end since people can use that for their own naming conventions for values/targets. Instead, I could just fetch the name of a target when using in a message, either player name or the display name of a mob defaulting to their entity type.

**Comment by Eniripsa96** [comment]
Added in v3.97 and will be included in next premium release
