### ISSUE TITLE
Suggestion: Status Mechanic, Fumbling.

### ISSUE THREAD

**Issue by TagCraftMC** [Eniripsa96/SkillAPI#83]
Another Idea (I am sure you're nearly sick of them by now), a new status effect called Fumbling.
When the target has this effect on them, every 5 ticks their hotbar slot changes to a random selection.

It would exclude any hotbar slots taken up by skills so they're not used up (or maybe they are).
Would be a great "come get premuim" addition. I have added a small demo below to show what I mean.

![image](https://i.gyazo.com/14816fb75db6dff249edb7994145c4f7.gif)
(ignore the other crap show, just quickly added an example to the latest project I had opened)

````
//in a 5 tick Runnable/Scheduler. What ever floats your goat.
int slot = random.nextInt(8);
player.getInventory().setHeldItemSlot(slot);
````

**Comment by Eniripsa96** [comment]
Interesting, though I could make it a little more generic and just have a mechanic to set your slot. Couple that with Value Random and the Repeat mechanic, and you'd accomplish the same thing.

**Comment by AngDrew** [comment]
but it can makes the target use skill on skill bar?

**Comment by Eniripsa96** [comment]
I would have it not switch to a skill slot.

**Comment by AngDrew** [comment]
what about if the target changed to skill slot the skill will gone? (triggering skill slot when right clicked)

**Comment by Eniripsa96** [comment]
Added in latest version
