### ISSUE TITLE
Value Lore Mechanic - Issue

### ISSUE THREAD

**Issue by bloggy** [Eniripsa96/SkillAPI#84]
There seems to be a bug: I have set the value lore (example: Damage: 5). Holding the item with that lore I deal 5 damage to the other player. Now when clear my inventory (no more item with any lore in my inventory), I still deal 5 damage to the other player. Somehow the plugin remembers the last dealt damage?! Instead there should be a default value that I could set somewhere. 

How would I define the default / base value of a skill's effect which is used when the player does NOT have the required item that buffs the skill's effect?

**Comment by AngDrew** [comment]
create this:
condition item
check item: true
item: air

child:
value set value-name set to 1 or 0

or

child:
damage buff
multiplier type
with value 0
so the player wont deal any damage

**Comment by bloggy** [comment]
I don't understand this. Can you give me an example?!

**Comment by AngDrew** [comment]
use value set mechanic
inside it put your damage value
if you got your damage value by using value lore
then use that key for the value set
put that key in value

i cant give you examples im not currently on pc
i used my phone to reply you..

**Comment by bloggy** [comment]
I don't understand what you are trying to say. Could you be more specific? 
Here is a screenshot of the editor:
http://i74.photobucket.com/albums/i263/myspaceye/2016-10-19_17-47-18.png
Is this correct so far?

What do I have to type in: 
VALUE LORE -> Key
VALUE SET -> Key & Value
SPEED -> Duration

Trying to make skill where the player has speed 2.0 for 5 seconds when casting the skill without the item that contains the lore "Flitzer: 10"

If the player holds the item with the lore "Flitzer: 10" then he should get speed 2.0 for 10 seconds.

**Comment by AngDrew** [comment]
im on pc :D 
try this:
![tutor](https://cloud.githubusercontent.com/assets/20359911/19554175/99c87374-96e1-11e6-9014-00026ae082b9.PNG)

**Comment by AngDrew** [comment]
if it not work use condition else (premium only)
if you wont use condition item and set to air, but if the player wear non air they will damage the same as your value lore

**Comment by AngDrew** [comment]
another options:
YOU HAVE DAMAGE from VALUE LORE
then add DELAY MECHANIC AND SET THE DELAY TO 0.1 SEC THEN DRAG THE VALUE SET TO DELAY.

please read carefuly!

**Comment by bloggy** [comment]
Sry but I still don't understand this. It makes no sense to me. I think I have to wait for the author to respond and clearify this. 

But thanks for trying to help!

**Comment by AngDrew** [comment]
well im trying my best =='
but you dont understand what i mean...
sorry
maybe its because my RIP english :(

**Comment by AngDrew** [comment]
but its not a bug
its about how you create the skill

the value will not gone after they are set to a player except if the player are relogin(the value will gone after player relog)
you just need to think how to make the value to 1 after player hit something then if the player hit again without that weapon they will deal damage as same as what you want.

**Comment by Eniripsa96** [comment]
Value Lore - doesn't change the number when item is missing

Value Set and then Value Lore - the set number becomes your default, and Value Lore applies only if you have the right item

Dealing damage using the value's key will then apply it.

General layout (add them in this order):

Value Set (Key = "someKey", Value = 3 or some default number you choose)
Value Lore (Key = "someKey", Regex = "Damage: {value}", Multiplier = 1)
Damage (Value = "someKey")

Hope this helps.

**Comment by bloggy** [comment]
THanks, this works! But I have an additional question:
Is it possible to use the Value Set - value and then ADD or MULTIPLY it with the Value Lore - value (if player has the specific item in his hand) instead of only overwriting values?

**Comment by Eniripsa96** [comment]
Yes, Value Add and Value Multiply will modify, not overwrite, values. Just use them after the Set/Lore ones and they will work together.
