### ISSUE TITLE
Unable to level up with default minecraft level system while SKillAPI is installed

### ISSUE THREAD

**Issue by bloggy** [Eniripsa96/SkillAPI#85]
I want to level up with the default minecraft leveling system but also have SkillAPI installed and activated the same time. How would this be possible?

**Comment by AngDrew** [comment]
i think its impossible
because when you take a class then you will have the exp and level

**Comment by bloggy** [comment]
But this is very annoying. When enchanting an item in enchanting table it takes the levels from your mana instead from minecraft's level system. This should be fixed or changed so that you can choose if you want to use the default minecraft level system.

**Comment by Eniripsa96** [comment]
As long as you don't use the experience bar in any of the SkillAPI GUI options, it should be fine. As soon as you use the experience bar for level or mana or something, it will override the vanilla experience because the bar is directly tied to it.
