### ISSUE TITLE
Paid and not working

### ISSUE THREAD

**Issue by QueenKisaki** [Eniripsa96/SkillAPI#87]
Hey, I've tried messaging on spigot over a week ago but bought the plugin, installed it and absolutely nothing happens but getting the skill book. I've followed all instructions and installed Mccore as well I can type /skill and see all the info there, type /skill customize to only see the example class but unable to click it, it acts as an item in the gui. I've done this on 2 servers and get the same thing. Any suggestions or will I need to request a refund for it not working? I run spigot 1.10.2.

**Comment by Eniripsa96** [comment]
Going to close this issue, but feel free to contact me again if anything else comes up.
