### ISSUE TITLE
Bug: Register events at skill instantiation

### ISSUE THREAD

**Issue by skyybender** [Eniripsa96/SkillAPI#89]
Hey Eniripsa96,

we are starting to code our own skills at the moment and recoginzed that our event handlers in the skill classes are not registered by the plugin manager. In your wiki you told us that you take care about registering events at the instantiation of the skill classes. The example skill [in your wiki](https://github.com/Eniripsa96/SkillAPI/wiki/_Tutorial-Coding-Skills) should be buggy as well.

We are using the latest version of SkillAPI premium with spigot 1.10.2. Could you please fix that issue. Registering the events in that static context by ourself is not that easy.

**Comment by skyybender** [comment]
Here one skill example with a listener that never is getting registered:
http://hastebin.com/uharehetod.java

**Comment by Eniripsa96** [comment]
It looks like I accidentally removed that functionality. I will add this back in, sorry about that.

**Comment by Eniripsa96** [comment]
Should be fixed in v3.97, will be included in next premium version as well.
