### ISSUE TITLE
Infinite ammunition with arrow as skill icon

### ISSUE THREAD

**Issue by skyybender** [Eniripsa96/SkillAPI#90]
If you set any kind of arrow as an skill icon you will have infinite arrows when shooting with a bow. The bow is taking the "special arrow icon" as ammunition and the plugin will reload its skill bar so the arrow returns... and so on :(

**Comment by Eniripsa96** [comment]
I removed arrows from the icon list in the tool due to this. It's not something I can fix, you just can't use arrows as icons.
