### ISSUE TITLE
Bug: Non-cast Triggers

### ISSUE THREAD

**Issue by AmbriusMC** [Eniripsa96/SkillAPI#92]
**Issue:** Non-cast Triggers

**Patch:** 1.8 Nov 13, 2016

**Bug:** The triggers _Crouch, Kill, Land, Launch, Physical Damage, Skill Damage, Took Physical Damage,_ and _Took Skill Damage_ all fail to apply their child components. This is despite the patch released on November 2 claiming to have fixed the issue.

**Replication:** Simply attempt to apply any sort of child using a non-cast trigger such as _Physical Damage_.

**Comment by Eniripsa96** [comment]
Fixed in 1.12
