### ISSUE TITLE
Bug: Cooldown Mechanic

### ISSUE THREAD

**Issue by AmbriusMC** [Eniripsa96/SkillAPI#93]
**Issue:** Cooldown Mechanic

**Patch:** 1.8 Nov 13, 2016

**Bug:** The _Cooldown_ mechanic doesn't quite seem to be working. Decreasing the cooldown of a skill works just fine, however when it comes to increasing it the mechanic seems to function highly inconsistently. You cannot increase the cooldown of a skill additionally while it already being on cooldown, and when it is off cooldown the effect only seems to apply after having used the skill once. This issue applies to both when using the mechanic on all skills and a particular skill.

**Comment by Eniripsa96** [comment]
Looking at the code, there does seem to be some needless restrictions and one method does seem to be simply incorrect. I will fix this in the next version.

**Comment by Eniripsa96** [comment]
Should be fixed in v1.11
