### ISSUE TITLE
Bug: Profess GUI

### ISSUE THREAD

**Issue by AmbriusMC** [Eniripsa96/SkillAPI#95]
**Issue:** Profess GUI

**Patch:** 1.8 Nov 13, 2016

**Bug:** When doing _/Class profess_ and clicking on any of the buttons to select a class nothing happens and the following error is shown in the console. While browsing the list of current bugs I did notice a similar issue "#67" and seeing as I'm using VentureChat as well I figured that perhaps that was the cause of it too. However the issue appears to persist regardless of VentureChat being disabled.

> 15.11 17:58:26 [Server] INFO ... 15 more
15.11 17:58:26 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot1.10.jar:git-Spigot-6016ac7-10c10b3]
15.11 17:58:26 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
15.11 17:58:26 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
15.11 17:58:26 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_66]
15.11 17:58:26 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
15.11 17:58:26 [Server] INFO at com.sucy.skill.listener.ToolListener.onClick(ToolListener.java:51) ~[?:?]
15.11 17:58:26 [Server] INFO at com.sucy.skill.tools.GUIHolder.handleClick(GUIHolder.java:89) ~[?:?]
15.11 17:58:26 [Server] INFO at com.sucy.skill.gui.DetailsHandler.onClick(DetailsHandler.java:36) ~[?:?]
15.11 17:58:26 [Server] INFO Caused by: java.lang.ClassCastException: com.sucy.skill.dynamic.DynamicClass cannot be cast to com.sucy.skill.api.player.PlayerClass
15.11 17:58:26 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
15.11 17:58:26 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [spigot1.10.jar:git-Spigot-6016ac7-10c10b3]
15.11 17:58:26 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [spigot1.10.jar:git-Spigot-6016ac7-10c10b3]
15.11 17:58:26 [Server] INFO at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot1.10.jar:git-Spigot-6016ac7-10c10b3]
15.11 17:58:26 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:733) [spigot1.10.jar:git-Spigot-6016ac7-10c10b3]
15.11 17:58:26 [Server] INFO at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot1.10.jar:git-Spigot-6016ac7-10c10b3]
15.11 17:58:26 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_66]
15.11 17:58:26 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_66]
15.11 17:58:26 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot1.10.jar:git-Spigot-6016ac7-10c10b3]
15.11 17:58:26 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot1.10.jar:git-Spigot-6016ac7-10c10b3]
15.11 17:58:26 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot1.10.jar:git-Spigot-6016ac7-10c10b3]
15.11 17:58:26 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1850) [spigot1.10.jar:git-Spigot-6016ac7-10c10b3]
15.11 17:58:26 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot1.10.jar:git-Spigot-6016ac7-10c10b3]
15.11 17:58:26 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot1.10.jar:git-Spigot-6016ac7-10c10b3]
15.11 17:58:26 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot1.10.jar:git-Spigot-6016ac7-10c10b3]
15.11 17:58:26 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot1.10.jar:git-Spigot-6016ac7-10c10b3]
15.11 17:58:26 [Server] INFO org.bukkit.event.EventException
15.11 17:58:26 [Server] ERROR Could not pass event InventoryClickEvent to SkillAPI v1.8

**Plugins in use:** 
> MCCore, WorldEdit, OldCombatMechanics, PlaceholderAPI, ViaVersion, Vault, ViaBackwards, WorldGuard, ProtocolLib, LibsDisguises, LuckPerms, Citizens, Sentinel, SkillAPI, Denizen, Parties, SuperVanish

**Comment by Eniripsa96** [comment]
Fixed in 1.9
