### ISSUE TITLE
Cooldown Issues and Cooldown in API

### ISSUE THREAD

**Issue by Olf96** [Eniripsa96/SkillAPI#96]
Hey,
i found out that the Cooldown will reset after rejoining the Server. 
For Example: I cast a skill with 40 seconds cooldown, rejoin and now the cooldown is 0 and i can cast it immediately again.

I checked the SkillAPI.getPlayerData(player) function for possible solutions but didn't find anything about the players skill cooldowns.

Is there any method to reset single or the whole skillset of a player to maximum cooldown? Then i could just create some onJoin event and reset the players cooldowns.

**Comment by Eniripsa96** [comment]
You're probably looking for "PlayerSkill.startCooldown()". You would get the player data like you had above, then get any particular skill (or all of them) from the player data, and call that method on each. I will likely be adding in preserving cooldowns on logout though, so this workaround wouldn't be necessary.

**Comment by Eniripsa96** [comment]
Fixed in v1.11
