### ISSUE TITLE
Console errors

### ISSUE THREAD

**Issue by popoverde** [Eniripsa96/SkillAPI#97]
So i used to ran a forge server, no we moved to  Kcauldron 1.7.10 and we cant use your beautiful plugin anymore, lastest version (or even older ones gave us errors)

Mccore 1.26 (old)
SkillAPI v3.98 (lastest)

As u can see at least mccore loads... and skillsapi bring errors:

> [19:54:25 INFO]: [MCCore] Enabling MCCore v1.26
> [19:54:25 INFO]: [MCCore] Logger => This server is running Thermos | https://git
> hub.com/CyberdyneCC/Thermos | 1.7.10-R0.1-SNAPSHOT | 1.7.10-1614.58 (MC: 1.7.10)
> 
> [19:54:25 INFO]: 1.7.10
> [19:54:25 INFO]: Version: 10710
> [19:54:25 INFO]: [MCCore] Created a new folder for config files
> [19:54:25 INFO]: [EssentialsProtect] Enabling EssentialsProtect v2.13.1
> [19:54:26 INFO]: [SkillAPI] Enabling SkillAPI v3.98
> [19:54:26 ERROR]: Error occurred while enabling SkillAPI v3.98 (Is it up to date
> ?)
> java.lang.NoClassDefFoundError: com/rit/sucy/config/CommentedConfig
>         at com.sucy.skill.data.Settings.<init>(Settings.java:73) ~[?:?]
>         at com.sucy.skill.SkillAPI.onEnable(SkillAPI.java:110) ~[?:?]
>         at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[J
> avaPlugin.class:1.7.10-1614.58]
>         at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader
> .java:368) [JavaPluginLoader.class:1.7.10-1614.58]
>         at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManage
> r.java:410) [SimplePluginManager.class:1.7.10-1614.58]
>         at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.jav
> a:438) [CraftServer.class:1.7.10-1614.58]
>         at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.
> java:372) [CraftServer.class:1.7.10-1614.58]
>         at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.jav
> a:519) [MinecraftServer.class:?]
>         at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.jav
> a:493) [MinecraftServer.class:?]
>         at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.jav
> a:453) [MinecraftServer.class:?]
>         at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(Dedicated
> Server.java:337) [lt.class:?]
>         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643) [M
> inecraftServer.class:?]
>         at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
> 

Doesnt matter wich version we try to use, check the next errors:

we installed LASTEST version of skillsapi and mccore:

MCCore v1.58
SkillAPI v3.98

> [19:59:55 INFO]: [MCCore] Enabling MCCore v1.58
> [19:59:55 INFO]: Server version: 10710
> [19:59:55 WARN]: java.lang.ClassNotFoundException: net/minecraft/server/v1_7_R4/
> Packet
> [19:59:55 WARN]:        at java.lang.Class.forName0(Native Method)
> [19:59:55 WARN]:        at java.lang.Class.forName(Unknown Source)
> [19:59:55 WARN]:        at com.rit.sucy.reflect.Reflection.init(Reflection.java:
> 61)
> [19:59:55 WARN]:        at com.rit.sucy.MCCore.onEnable(MCCore.java:94)
> [19:59:55 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlug
> in.java:316)
> [19:59:55 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(
> JavaPluginLoader.java:368)
> [19:59:55 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(Si
> mplePluginManager.java:410)
> [19:59:55 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin
> (CraftServer.java:438)
> [19:59:55 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlug
> ins(CraftServer.java:372)
> [19:59:55 WARN]:        at net.minecraft.server.MinecraftServer.func_71243_i(Min
> ecraftServer.java:519)
> [19:59:55 WARN]:        at net.minecraft.server.MinecraftServer.func_71222_d(Min
> ecraftServer.java:493)
> [19:59:55 WARN]:        at net.minecraft.server.MinecraftServer.func_71247_a(Min
> ecraftServer.java:453)
> [19:59:55 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_7
> 1197_b(DedicatedServer.java:337)
> [19:59:55 WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftSer
> ver.java:643)
> [19:59:55 WARN]:        at java.lang.Thread.run(Unknown Source)
> [19:59:55 ERROR]: Error occurred while enabling MCCore v1.58 (Is it up to date?)
> 
> java.lang.IllegalStateException: Failed to initialize reflection utility
>         at com.rit.sucy.reflect.Reflection.init(Reflection.java:69) ~[?:?]
>         at com.rit.sucy.MCCore.onEnable(MCCore.java:94) ~[?:?]
>         at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[J
> avaPlugin.class:1.7.10-1614.58]
>         at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader
> .java:368) [JavaPluginLoader.class:1.7.10-1614.58]
>         at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManage
> r.java:410) [SimplePluginManager.class:1.7.10-1614.58]
>         at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.jav
> a:438) [CraftServer.class:1.7.10-1614.58]
>         at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.
> java:372) [CraftServer.class:1.7.10-1614.58]
>         at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.jav
> a:519) [MinecraftServer.class:?]
>         at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.jav
> a:493) [MinecraftServer.class:?]
>         at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.jav
> a:453) [MinecraftServer.class:?]
>         at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(Dedicated
> Server.java:337) [lt.class:?]
>         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643) [M
> inecraftServer.class:?]
>         at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
> Caused by: java.lang.ClassNotFoundException: net/minecraft/server/v1_7_R4/Packet
> 
>         at java.lang.Class.forName0(Native Method) ~[?:1.8.0_111]
>         at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_111]
>         at com.rit.sucy.reflect.Reflection.init(Reflection.java:61) ~[?:?]
>         ... 12 more
> 
> 
> 
> [19:59:57 INFO]: [SkillAPI] Enabling SkillAPI v3.98
> [19:59:57 ERROR]: Error occurred while enabling SkillAPI v3.98 (Is it up to date
> ?)
> java.lang.NullPointerException
>         at com.rit.sucy.scoreboard.BoardManager.setTextBelowNames(BoardManager.j
> ava:145) ~[?:?]
>         at com.sucy.skill.manager.ClassBoardManager.registerText(ClassBoardManag
> er.java:162) ~[?:?]
>         at com.sucy.skill.SkillAPI.onEnable(SkillAPI.java:125) ~[?:?]
>         at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[J
> avaPlugin.class:1.7.10-1614.58]
>         at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader
> .java:368) [JavaPluginLoader.class:1.7.10-1614.58]
>         at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManage
> r.java:410) [SimplePluginManager.class:1.7.10-1614.58]
>         at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.jav
> a:438) [CraftServer.class:1.7.10-1614.58]
>         at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.
> java:372) [CraftServer.class:1.7.10-1614.58]
>         at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.jav
> a:519) [MinecraftServer.class:?]
>         at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.jav
> a:493) [MinecraftServer.class:?]
>         at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.jav
> a:453) [MinecraftServer.class:?]
>         at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(Dedicated
> Server.java:337) [lt.class:?]
>         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643) [M
> inecraftServer.class:?]
>         at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
> 

So if we try very old versions, they load, but dont work on Kcauldron 1.7.10
Commands throw us errors:

[20:06:44 INFO]: [SkillAPI] Loading SkillAPI v2.43
[20:06:50 INFO]: [MCCore] Enabling MCCore v1.26
[20:06:50 INFO]: [MCCore] Logger => This server is running Thermos | https://git
hub.com/CyberdyneCC/Thermos | 1.7.10-R0.1-SNAPSHOT | 1.7.10-1614.58 (MC: 1.7.10)

[20:06:51 INFO]: [SkillAPI] Enabling SkillAPI v2.43
[20:06:51 INFO]: [SkillAPI] Loaded 0 skills and 0 skill trees

[20:20:05 INFO]: 1 issued server command: /class reload
[20:20:05 INFO]: [SkillAPI] Disabling SkillAPI v2.43
[20:20:05 INFO]: [SkillAPI] Enabling SkillAPI v2.43
[20:20:05 INFO]: [SkillAPI] Loaded 0 skills and 0 skill trees
[20:20:11 INFO]: 1 issued server command: /class profess
[20:22:33 INFO]: 1 issued server command: /class reload
[20:22:33 INFO]: [SkillAPI] Disabling SkillAPI v2.43
[20:22:33 INFO]: [SkillAPI] Enabling SkillAPI v2.43
[20:22:33 ERROR]: Error occurred while enabling SkillAPI v2.43 (Is it up to date
?)
java.lang.IllegalArgumentException: No enum constant com.sucy.skill.api.skill.Sk
illType.DYNAMIC
        at java.lang.Enum.valueOf(Unknown Source) ~[?:1.8.0_111]
        at com.sucy.skill.api.skill.SkillType.valueOf(SkillType.java:6) ~[?:?]
        at com.sucy.skill.api.dynamic.DynamicSkill.update(DynamicSkill.java:71)
~[?:?]
        at com.sucy.skill.RegistrationManager.initialize(RegistrationManager.jav
a:90) ~[?:?]
        at com.sucy.skill.SkillAPI.onEnable(SkillAPI.java:221) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[J
avaPlugin.class:1.7.10-1614.58]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader
.java:368) [JavaPluginLoader.class:1.7.10-1614.58]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManage
r.java:410) [SimplePluginManager.class:1.7.10-1614.58]
        at com.sucy.skill.command.admin.CmdReload.execute(CmdReload.java:27) [Sk
illAPI%20(8).jar:?]
        at com.rit.sucy.commands.ConfigurableCommand.execute(ConfigurableCommand
.java:469) [MCCore%20(3).jar:?]
        at com.rit.sucy.commands.ConfigurableCommand.execute(ConfigurableCommand
.java:476) [MCCore%20(3).jar:?]
        at com.rit.sucy.commands.ConfigurableCommand.execute(ConfigurableCommand
.java:449) [MCCore%20(3).jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:18
1) [SimpleCommandMap.class:1.7.10-1614.58]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServe
r.java:740) [CraftServer.class:1.7.10-1614.58]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPl
ayServer.java:1370) [nh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPl
ayServer.java:1107) [nh.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(
C01PacketChatMessage.java:38) [ir.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(
C01PacketChatMessage.java:53) [ir.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java
:245) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:
181) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.jav
a:1023) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(Dedicated
Server.java:432) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.jav
a:841) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [M
inecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
[20:22:35 INFO]: 1 issued server command: /class profess

Thanks

**Comment by Eniripsa96** [comment]
Cauldron is unfortunately not supported since it breaks any sort of reflection I need to use to accomplish certain features. With it also being an abandoned project and minecraft now being 4 major versions ahead of it, I don't think support will be added to it. Sorry for the inconvenience.

**Comment by evernife** [comment]
Same to me... really bad that is not supported T.T

**Comment by evernife** [comment]
@Eniripsa96 if Thermos fix "the sorts of reflection" you need, it would work?

They think that even if they fix that it will not work :/ so i can't arg against them...
