### ISSUE TITLE
Bug: Item Projectiles

### ISSUE THREAD

**Issue by AmbriusMC** [Eniripsa96/SkillAPI#98]
**Issue**: Item Projectile Mechanic

**Patch**: _SkillAPI Premium_ 1.11 Nov 27, 2016

**Bug**: When hitting an entity item projectiles work flawlessly, however if the projectile hits the ground, the item will glitch and cannot be interacted with until it's eventually cleared. Additionally the item projectile will not select the block hit as its target to apply the designated child affects to. The only case I've found where it has worked, has been when hitting slabs, fence, fence gates, and trap doors.

**Replication Skill**: [Test.yml.zip](https://github.com/Eniripsa96/SkillAPI/files/617224/Test.yml.zip)

**Comment by Eniripsa96** [comment]
Fixed in v1.14
