### ISSUE TITLE
Bug: Area Targeting by Projectile

### ISSUE THREAD

**Issue by AmbriusMC** [Eniripsa96/SkillAPI#99]
**Issue**: _Area Targeting_ when being a child of a projectile (Projectile/Item Projectile/Particle Projectile)

**Patch**: SkillAPI Premium 1.11 Nov 27, 2016

**Bug**: _Area Targeting_ appears to be applying the child effects twice to its targets when triggered by a projectile of any sort. 

**Replication Skill**: [Test.yml.zip](https://github.com/Eniripsa96/SkillAPI/files/617217/Test.yml.zip)

**Comment by Eniripsa96** [comment]
Fixed in v1.14
